### ISSUE TITLE
Recent Items Not Usable or Mouseoverable

### ISSUE THREAD

**Issue by PaulVlahosCS** [Cidan/BetterBags#100]
https://i.imgur.com/5zs10v7.png

Sometimes when a new item is obtained and goes into the recently obtained items section at the top, they are not useable or even give a tooltip on mouseover. This is fixed with a /reload but is still annoying as it will affect potions from the cauldron in raid.

Unfortunately, it also isn't throwing any error either. I do see some sort of number overlap and I'm not sure what both numbers are. For context in this picture, I bought 7 epic battle pet stones.

**Comment by Cidan** [comment]
This is a bug in the current rendering engine, and is slated to be fixed in the next few days.

**Comment by Cidan** [comment]
Fixed in 0.1.0
