### ISSUE TITLE
[BUG] Currencies are visually bugged and text is unreadable

### ISSUE THREAD

**Issue by ildallo** [Cidan/BetterBags#110]
![image](https://github.com/Cidan/BetterBags/assets/69390497/26409d52-64db-4066-aae1-bf5dbbab49e4)
Currencies are defective both visually and textually. Unchecking and selecting again seems to solve the problem, but after loading or after opening the inventory the problem recurs.

**Comment by Cidan** [comment]
This is fixed in the next release. Thank you!
