### ISSUE TITLE
Add category for Junk items compatible with Scrap addon

### ISSUE THREAD

**Issue by OrsonWorkshop** [Cidan/BetterBags#111]
Would it be possible to get the category for junk item compatible with scrap addon list? It was working in AdiBags before. :)

**Comment by rodalpho** [comment]
I custom sort items into the junk category also, typically non-grey items that I know I want to delete manually.

**Comment by NiTr0-at** [comment]
Would be nice if additionally, I could define a iLvl threshold and everything below this iLvl would also considered as Junk (if not matched by another category)

**Comment by zeptognome** [comment]
'Comparability' with Scrap would mean a version of Scrap written to use the BetterBags API - so perhaps the author will do that. As commented above, you can add any items to a 'Junk' custom category and they will merge with the built-in Junk (gray items)

**Comment by OrsonWorkshop** [comment]
Adding each item second time to a junk category would be very tedious. Wouldn't it be possible to just set the junk category so it can use the junk list of scrap?

**Comment by zeptognome** [comment]
> Adding each item second time to a junk category would be very tedious. Wouldn't it be possible to just set the junk category so it can use the junk list of scrap?

How would BetterBags know that non-gray items were junk unless you or the Scrap addon told it so?
Gray items are auto marked as junk unless another category claims it.

The solution, as far as I understand, has to start from the Scrap addon supporting BetterBags
