### ISSUE TITLE
null pointer 

### ISSUE THREAD

**Issue by HereticalHermit** [Cidan/BetterBags#113]
Was using adi, switched over to betterbags. Unable to open bank or if I switch to list instead of grid. This error will not resolve even with a reload. It just keeps repeating and prevents the bank from opening.

73x BetterBags/data/equipmentsets.lua:31: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@BetterBags/data/equipmentsets.lua"]:31: in function `Update'
[string "@BetterBags/data/items.lua"]:116: in function `RefreshBank'
[string "@BetterBags/frames/bag.lua"]:168: in function `Refresh'
[string "@BetterBags/frames/bagslots.lua"]:111: in function <BetterBags/frames/bagslots.lua:107>
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by HereticalHermit** [comment]
Agreed. I am on retail version of game. The issue is that the sets variable on line 27 is nil so when attempting to cycle through pairs , the table is empty. I can work around with a nil check something like 
if sets ~= nil then return end

but that is likely not the ideal solution.

**Comment by Cidan** [comment]
I am trying to figure out how this happened in the first place -- this technically shouldn't ever happen, and I can't reproduce it. I'll add a guard regardless, but I have no idea why the API is returning invalid data here.
