### ISSUE TITLE
[Feature Request] Desaturate items in mail

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#115]
**Current behavior:**
When attaching items to mail, there is no way of knowing which items exactly have been attached to the mail. For example think of having many stacks of something but you want to attach a smaller subset of those and quickly click on them to attach them. Sometimes WoW will skip items because of lag and it's hard to find which stack has been missed.
![WowClassic_2uZvgyaNfu](https://github.com/Cidan/BetterBags/assets/16212271/6e2ee45f-841d-4fc7-813d-6d9e260f6057)

**Expected behavior:**
When attaching items to mail, the attached items should be desaturated in color to give feedback which items have been attached yet. (See default behavior of bags when sending mail in attached screenshot)
![WowClassic_jFo6jnhLAk](https://github.com/Cidan/BetterBags/assets/16212271/f8d773dd-92c5-4fc7-80eb-00a0748d61b4)
Left mana potion is not attached to mail, right one is.

**Comment by mastersuleman** [comment]
This also affects auction house

**Comment by zeptognome** [comment]
fixed a while back
