### ISSUE TITLE
[Feature Request] Better indication of # of free bag slots 0 vs 1

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#116]
**Disclaimer**
I'm pretty sure this is on your list of todos already, but I thought I would open a ticket for completeness.

**Current Behavior**
When you have 1 or 0 empty bag space (Bag or bank) there is no way of knowing if there is any left since it shows the same. When `#free slots > 1` there is a little number on the bottom right to indicate the amount of free space.

**Expected Behavior**
Multiple ways are possible here. The easiest would probably be to be consistent and just show a little '1' when there is one empty slot left. However fro
m UX perspective zero empty bag slots as this:
![WowClassic_0ullVp7Xps](https://github.com/Cidan/BetterBags/assets/16212271/8deb7d59-9f08-4eb1-85ee-d8856ef368f7)
might still not be ideal. 

So a combination could be a good approach:
- Show a little '1' for 1 bag slot left
- Adjust the color of the slot to be red to indicate no empty space left
- Alternatively show a little '0' for no bag slots left

Examples:
![WowClassic_0ullVp7Xps](https://github.com/Cidan/BetterBags/assets/16212271/c4049d68-9db2-4d11-8566-3d52884f2099)
![WowClassic_8kjC7vsXAj](https://github.com/Cidan/BetterBags/assets/16212271/dc161e78-5092-4fa9-a494-b5f7651fd9f9)
![WowClassic_tPifS5ol6adak](https://github.com/Cidan/BetterBags/assets/16212271/6fc8b24b-0597-46c9-9051-7954e196cd60)

**Comment by AMaribo** [comment]
Free spaces now show a 1 or 0 on the Free Space slot where there are 1 or 0 slots open.
