### ISSUE TITLE
Right clicking a section header should deposit or withdraw all items from the header

### ISSUE THREAD

**Issue by Cidan** [Cidan/BetterBags#118]

**Comment by ItsDandyDigital** [comment]
+1 for both deposit/withdraw as well, if vendoring, right clicking the category header would sell the items.

**Comment by Booggg** [comment]
Yes pls Adibags was this way and I miss it. 

It also makes it much easier to keep your raid gear (sets tab) away from junk items you get from farming old raids, so you can hide the raid gear (sets tab) as most of that gear you will be keep for the whole tier, making all you valuable gear hidden, so you can quickly vender all junk gear without worry you will miss sell something.

**Comment by AMaribo** [comment]
This has been implemented with v0.1.90.
