### ISSUE TITLE
lua error with ElvUI

### ISSUE THREAD

**Issue by bardthebowman** [Cidan/BetterBags#131]
14x ElvUI/Core/Modules/Tooltip/Tooltip.lua:901: bad argument #1 to 'strmatch' (string expected, got nil)
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:901: in function <ElvUI/Core/Modules/Tooltip/Tooltip.lua:898>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetCurrencyToken'
[string "@BetterBags/frames/currency.lua"]:85: in function <BetterBags/frames/currency.lua:83>

Locals:
(*temporary) = nil
(*temporary) = "currency:(%d+)"
(*temporary) = "string expected, got nil"

**Comment by Cidan** [comment]
This is an elvui error, please report this to them.
