### ISSUE TITLE
Caged pets should show Pet image not cage 

### ISSUE THREAD

**Issue by woodrikj** [Cidan/BetterBags#132]
When you have a caged pet, adibags used to show the image of what pet it was not the cage image. Currently better bags only shows the cage. 
![image](https://github.com/Cidan/BetterBags/assets/10760299/f8a9aeb0-f8fa-4878-9848-aaad5dffc93d)
![image](https://github.com/Cidan/BetterBags/assets/10760299/16a94973-d80e-4ba9-89c5-4aae26c4653c)

**Comment by tsracing** [comment]
Additional, pet names cannot be searched for (probably because of same bug why cage is shown?)

**Comment by Gil-ER** [comment]
Battle pet will always return 'Pet Cage' for name using GetItemInfo(id) you have to get the details from the tooltip

	local tooltipData = C_TooltipInfo.GetBagItem(bag, slot) -- or C_TooltipInfo.GetGuildBankItem( tab, slot )
	if tooltipData then
		TooltipUtil.SurfaceArgs( tooltipData )
		if tooltipData.battlePetSpeciesID then
			-- tooltipData.battlePetSpeciesID
			-- tooltipData.battlePetLevel
			-- tooltipData.battlePetBreedQuality
			-- tooltipData.battlePetMaxHealth
			-- tooltipData.battlePetPower
			-- tooltipData.battlePetSpeed
			-- tooltipData.battlePetName
		end
	end

This is a deal breaker for me.

**Comment by Cidan** [comment]
This is on the list of things to get done. There is a more elegant way of getting the information needed than the tooltip -- it'll get done in the near future.

**Comment by zeptognome** [comment]
fixed in #316
