### ISSUE TITLE
[Feature]: Add armour subtype category. 

### ISSUE THREAD

**Issue by kbuczynski-nashpl** [Cidan/BetterBags#133]
### Describe the feature

As a user, I would like to split my gear in bag by its sub type category [wrists, chests, 2h, 1h, trinkets]. 

### Describe the implementation

when i go into options to pick a category i would like to be able to select split by gear sub type only.

**Comment by Inf8989** [comment]
this is the biggest feature I'm looking for as well

**Comment by zeptognome** [comment]
I believe this is generally covered by 'Equipment Location'
More refined options are being developed
