### ISSUE TITLE
[Masque] Skin Error

### ISSUE THREAD

**Issue by SheffyWoW** [Cidan/BetterBags#134]
### Addon Version

v0.1.5

### World of Warcraft Version

Retail

### Describe the bug

If you use the Masque Skin "Clean Icons - Original" all item icons in your bags are being displayed in different colours instead of the actual item icon.
![Bild_2024-02-19_192115873](https://github.com/Cidan/BetterBags/assets/59845533/0706102f-cd3e-40e6-959c-01db86072270)

### Steps to reproduce

1. Masque installed (and Elvui?)
2. Skin: "Clean Icons - Original" installed
3. Open bags

**Comment by Cidan** [comment]
I was able to reproduce this, but this isn't a bug in BetterBags. CleanIcons hasn't been updated in 4 years, and it does not do the correct thing for IconBorders, which is what those squares are. You'll have to reach out to the author and see if they are willing to update the addon.

**Comment by Cidan** [comment]
Just FYI, I implemented a hackfix for this, will be released in the next release.
