### ISSUE TITLE
[Feature]: Add the ability to bind clicks to different actions on the bag frame bag button.

### ISSUE THREAD

**Issue by kbuczynski-nashpl** [Cidan/BetterBags#138]
### Describe the feature

Right clicking on a bag window is not very UI friendly and there is no quick stash all reagent button either

### Describe the implementation

As a user i would like 2 buttons somewhere on  a bank bag window
1. to switch between reagent tab and normal bank window
2 . to quick deposit reagent items

**Comment by kbuczynski-nashpl** [comment]
I realised last night that the one thing i missed from AdiBags is a button to deposit all regents to a bank with single click.

**Comment by zeptognome** [comment]
>     1. to switch between reagent tab and normal bank window
This exists as tabs on the bank window as of TWW.

>        2 . to quick deposit reagent items
This has existed as a menu option on the bank window bag button for a while.
![image](https://github.com/user-attachments/assets/7a62e897-51a9-4e81-a7bd-dd28959721ee)

Might be added(or moved) to the Reagent Bank tab in the future
