### ISSUE TITLE
[FeatureRequest]: Add option to jump straight to search

### ISSUE THREAD

**Issue by int3ro** [Cidan/BetterBags#141]
### Describe the feature

I'd really love if there was the option to straight up jump into the search box when i'm opening my bags. So I can start typing and searching immediatelly.

### Describe the implementation

An option in the settings to opt in (disabled by default).

This would work best if it only focuses the search box when I'm using the hotkey (B) to open the search. Not when the bags are openend by context (e.g. vendor).

**Comment by Cidan** [comment]
There is an "open to search" hotkey already in the key bindings for BetterBags in the wow keybindings configuration. You can just bind "B" to it, though it won't close your bag if you type it again. I might augment this down the line so it does.
