### ISSUE TITLE
Sorting bags vs manually locked items

### ISSUE THREAD

**Issue by zeptognome** [Cidan/BetterBags#143]
### Addon Version

v0.1.5

### World of Warcraft Version

Retail

### Describe the bug

When sorting the backpack via right-click on the bag button, locked items are re-stacked with similar, but unlocked items and the lock is reapplied based on the status of the first item encountered resulting in a stack of locked items or a stack of unlocked items.

I would prefer locked item/stacks to never be stacked with unlocked items.
I would think that not moving locked items would be acceptable/preferable.

### Steps to reproduce

Simplified example:
![image](https://github.com/Cidan/BetterBags/assets/158738380/5d8c6399-304b-4860-a157-0953adfe0f84)
->
![image](https://github.com/Cidan/BetterBags/assets/158738380/5e0701e7-1a74-4c5d-a8f3-0083956f3c85)

![image](https://github.com/Cidan/BetterBags/assets/158738380/5549b28b-3c06-430d-a62b-1ccce7a7f421)
->
![image](https://github.com/Cidan/BetterBags/assets/158738380/692281db-e71b-40e1-8258-e725e12d1033)

**Comment by Cidan** [comment]
Oh this is a really good catch! I'll take a look at this -- this might get really complicated because of the way item locking works.
