### ISSUE TITLE
Using an item causes the game to hitch for a brief moment. 

### ISSUE THREAD

**Issue by ninjalink99** [Cidan/BetterBags#146]
### Addon Version

0.15

### World of Warcraft Version

Retail

### Describe the bug

when i use an item that is in my inventory, mainly consumables, the game takes a split second to freeze then gets moving again. i am unsure as to why it is doing this, but i can say with certainty that it happens every time i use a consumable. 

### Steps to reproduce

use a consumable item at all, it will cause your game to hitch for a split second.

**Comment by Cidan** [comment]
This currently happens if the bag is very full, as right now I do a full rescan when bags change. I am going to improve this and change some things around to make this faster.
