### ISSUE TITLE
[Feature]: Option to change fill order when using multiple columns

### ISSUE THREAD

**Issue by Dezarius** [Cidan/BetterBags#149]
### Describe the feature

Currently when using multiple comlumns the window gets filled from left to right and then top to bottum. When using multiple columns i would prefere that they get filled top to bottum first and then left to right. (like it was in Adibags)
How it is now:
![zfZTNHX](https://github.com/Cidan/BetterBags/assets/9378482/cb346cdd-4db9-4bc3-add4-01ab1840fcbb)
How it was: (and how I would like it also be an option in BetterBags)
![jDLDOTU](https://github.com/Cidan/BetterBags/assets/9378482/81cca899-c20e-4b8c-8baf-48fc1530d1c7)

### Describe the implementation

guess like this xD
![do13izs](https://github.com/Cidan/BetterBags/assets/9378482/af3d63a4-8c75-45d4-9301-eb2ce8ba9f26)

**Comment by zeptognome** [comment]
Was implemented back in May
