### ISSUE TITLE
Lua Error. From addons took off AdiBags from Start up. 

### ISSUE THREAD

**Issue by luisperezart** [Cidan/BetterBags#151]
### Addon Version

AdiBags issue.

### World of Warcraft Version

Retail

### Describe the bug

After removing addon AdiBags from startup at login to game I get this Lua Error. Does not happen when I also turn off vendor addon.

### Steps to reproduce

After removing addon AdiBags from startup at login to game I get this Lua Error.

**Comment by luisperezart** [comment]
Message: ...endor/systems/extensionmanager/extension_adibags.lua:161: Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'AdiBags'.
Time: Mon Feb 19 16:33:56 2024
Count: 1
Stack: ...endor/systems/extensionmanager/extension_adibags.lua:161: Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'AdiBags'.
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:151: in function `GetAddon'
[string "@Interface/AddOns/Vendor/systems/extensionmanager/extension_adibags.lua"]:161: in function <...endor/systems/extensionmanager/extension_adibags.lua:159>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Vendor/systems/extensionmanager/internalextensions.lua"]:88: in function `RegisterInternalExtension'
[string "@Interface/AddOns/Vendor/systems/extensionmanager/extensionmanager.lua"]:31: in function <...Vendor/systems/extensionmanager/extensionmanager.lua:23>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Vendor/sys/systems.lua"]:283: in function `InitTarget'
[string "@Interface/AddOns/Vendor/sys/systems.lua"]:66: in function `Next'
[string "@Interface/AddOns/Vendor/sys/systems.lua"]:80: in function <Interface/AddOns/Vendor/sys/systems.lua:66>
[string "@Interface/AddOns/Vendor/sys/systems.lua"]:241: in function <Interface/AddOns/Vendor/sys/systems.lua:241>

Locals: (*temporary) = "Usage: GetAddon(name): 'name' - Cannot find an AceAddon 'AdiBags'."

**Comment by Cidan** [comment]
You have another addon that is trying to access AdiBags. This has nothing to do with this team -- it looks like "Vendor" is causing this.

**Comment by luisperezart** [comment]
Thank you!
