### ISSUE TITLE
manual locks broken by AH

### ISSUE THREAD

**Issue by zeptognome** [Cidan/BetterBags#154]
### Addon Version

v0.1.5

### World of Warcraft Version

Retail

### Describe the bug

AuctionHouse does not respect BB's manually locked items

Multiple issues here:
Manually locked items can be added to the AH 'sell' window via right-click
Manually locked items are no longer locked when removed from the AH 'sell' window and are in a visually inconsistent state. (unlocked but appear locked with red padlock) 

Locked items can be actually auctioned either directly via right-click method above or via addition by using a quantity > 1 after attempting to sell an unlocked version.

### Steps to reproduce

Manually lock an item with middle-click
add item to AH 'create auction' via right click
remove item from sell window or by closing the AH. This locked item is now in an inconsistent state of showing the manual lock overlay, but is no longer locked.

![image](https://github.com/Cidan/BetterBags/assets/158738380/51941aaa-b4f4-4724-b666-fa3137e5ee72)

**Comment by Cidan** [comment]
The lock item API is not a BetterBags API -- it's actually a WoW client API. Blizzard controls what is locked, what isn't, and what actions you can take with a locked item. I do want to fix the visual aspects of it though, as that is a bug.
