### ISSUE TITLE
[Feature]: Peddler integration

### ISSUE THREAD

**Issue by Spennig** [Cidan/BetterBags#155]
### Describe the feature

I use Peddler for my quick-selling, but it relies on being able to see what items I have flagged as "for sale/junk" - it adds a stack of coins in a corner to indicate which I'd like to sell. 

Peddler is found on Curseforge or here https://github.com/Cartas/Peddler

![PeddlerCoins](https://github.com/Cidan/BetterBags/assets/111753362/7383cbac-91a5-43e4-bb2e-dcfe22a71d46)

### Describe the implementation

I'd like to be able to tag something for sale (alt-click in my case) and have it show the coins so I know it will be sold at next vendor visit.

**Comment by zeptognome** [comment]
I think this is in progress if not already released on the Peddler side:
https://github.com/Cartas/Peddler/commit/a39fabca2453d534e4128019bc2203d05874ebc6

**Comment by zeptognome** [comment]
I think this is being handled by the Peddler Author
https://github.com/Cartas/Peddler/commit/a39fabca2453d534e4128019bc2203d05874ebc6

**Comment by Spennig** [comment]
Just as a note, this still isn't showing. The functionality from Peddler works, but the coin icon doesn't show in the bag. 

Adibags:
![image](https://github.com/Cidan/BetterBags/assets/111753362/9344d720-999d-414c-b8b7-1ac0158bc2c4)

BetterBags:
![image](https://github.com/Cidan/BetterBags/assets/111753362/fae7f40c-ada0-4643-bd54-cfb1d7e74a63)

**Comment by zeptognome** [comment]
> Just as a note, this still isn't showing. 

He hasn't published a retail version of his addon with support (yet?)

![image](https://github.com/Cidan/BetterBags/assets/158738380/4f854d3f-ca83-41b2-8f93-abcbf2d4bb85)

**Comment by Cartas** [comment]
Hi old chaps!

Apologies for the wait - hopefully Peddler now works with BetterBags as expected.  🥳
