### ISSUE TITLE
1. Masque Error 2. Custom Categories doesnt work

### ISSUE THREAD

**Issue by Jaidy88** [Cidan/BetterBags#161]
### Addon Version

v01.1.6

### World of Warcraft Version

Retail

### Describe the bug

First Erro: Unfortunately, Masque does not work together with Better Bags, all items are black. 

Second Error: I can create custom categories, but I can't assign items to them. what am I doing wrong? Drag and drop doesn't work, putting an item in a free slot doesn't work either....

### Steps to reproduce

If I switch off Masque, all items look normal

**Comment by Cidan** [comment]
Please make two issues for these two items, as they are unrelated to each other.

Thanks!
