### ISSUE TITLE
Custom Categories doesnt work

### ISSUE THREAD

**Issue by Jaidy88** [Cidan/BetterBags#163]
### Addon Version

v01.1.6

### World of Warcraft Version

Retail

### Describe the bug

 I can create custom categories, but I can't assign items to them. what am I doing wrong? Drag and drop doesn't work, putting an item in a free slot doesn't work either....

### Steps to reproduce

1. Open options
2. open Custom Categories
3. new category
4. https://i.gyazo.com/f0268ec4667ad2704cdc5922dddbf021.png
5. drag and drop doesnt work

how can i add items or put them in a free slot?

**Comment by Cidan** [comment]
You need to drag and drop, not pick up an item and put it down. You can't let go of the mouse button before you move it over the drop frame. This will be fixed in a later release, see #129

**Comment by Jaidy88** [comment]
https://gyazo.com/802bebcbae311c76cb6a8104acb1a17a

i try but, i can't get it, i don't let go of the left button, where should i drag the item to
