### ISSUE TITLE
Currency Tracker obscured by Crest Tracker

### ISSUE THREAD

**Issue by peoii** [Cidan/BetterBags#164]
### Addon Version

0.1.6

### World of Warcraft Version

Retail

### Describe the bug

When adding currencies to the tracker in bags, the crest tracker overlays on top of the list.
![image](https://github.com/Cidan/BetterBags/assets/68097/e1febe45-3264-4fdb-952b-a69b0accc597)

As seen in the screenshot, I attempted to resolve this for daily use by tracking aspect crests to pad it out, but obviously this isn't ideal.

### Steps to reproduce

1. Open Bag
2. Open Currency tracker
3. Track currency
4. Repeat as required :P

**Comment by peoii** [comment]
error on my behalf, not a part of this addon, too many tabs.

**Comment by xathian** [comment]
> error on my behalf, not a part of this addon, too many tabs.

Can you elaborate what you mean by this? I have this same problem and can't solve it

**Comment by Cidan** [comment]
The crest tracker is part of Plumber, not BetterBags. I do plan an integration soon to fix this, even though it's not strictly an issue with BetterBags.

**Comment by xathian** [comment]
> The crest tracker is part of Plumber, not BetterBags. I do plan an integration soon to fix this, even though it's not strictly an issue with BetterBags.

Ahhh yes thank you. I was skimming my addon list for anything remotely named "crests" or similar, completely forgot what plumber was.
