### ISSUE TITLE
Bag click to open

### ISSUE THREAD

**Issue by Milky063** [Cidan/BetterBags#166]
### Describe the feature

So i notice their is only one way to open the bags when you mouse over click. You have to click the main bag. Can you make it so you can click on any bag will open the window. Thank you

### Describe the implementation

Add this option maybe into the settings.

**Comment by Cidan** [comment]
Can you show me a screenshot of what you mean?

**Comment by Milky063** [comment]
[cid:09978126-6ccb-4e28-99ee-b8310b71ead5]

When i try to click on any of the 5 bags to the right of the main bag, it wont open the bag window. the only way to open bags is by clicking on the main bag only. I notice if you SHIFT + click it will open up the bag window. Is there a way to turn that off so you can just click on any bag to open the window.
________________________________

**Comment by Cidan** [comment]
No, this isn't something that is in scope as BetterBags intentionally hides the bag buttons.

**Comment by Milky063** [comment]
but my bags are not hidden, how do you hide all the bags but only show the main one?
________________________________
