### ISSUE TITLE
Does not show transmog status checkmarks from CanIMogIt

### ISSUE THREAD

**Issue by dennyau** [Cidan/BetterBags#172]
### Addon Version

v0.1.6

### World of Warcraft Version

Retail

### Describe the bug

CanIMogIt and Adibags (v1.10.24) work together to show all my items in the one bag with the tiny checkboxes in on the item icons to show if I have the transmog.

I recently moved to BetterBags since the latest AdiBags update told me to.

However, the BetterBags display does not show the checkbox from CanIMogIt - which removes my ability to look at a sorted portion of my bag and determine what to mail to my alts for transmog collection.

### Steps to reproduce

1. Install AdiBags v1.10.24 from Curse
2. Install "Can I Mog It?" v10.1.5v1.53 from Curse
3. Launch WoW retail, log into character and view bag: armour had the green-checkmark/other icons from Can I Mog It?
4. Disable/Uninstall AdiBags
5. Install BetterBags v0.1.6 from Curse
6. Launch WoW retails, log into character and view bag.  Same armour icons will be missing checkmarks.

**Comment by radhaz** [comment]
I'm not sure if it matters but initially came to this github to make this bug report. It sucks that it's happening but I am glad I'm not the only one that noticed.

**Comment by Cidan** [comment]
CIMI has a specific plugin just for AdiBags: https://github.com/TorelTwiddler/CanIMogIt/blob/master/Plugins/adibags.lua

This is something the CIMI author needs to implement. We'll leave this bug open to track it on our end.

**Comment by Wisdawn** [comment]
I also came here to point this out. I really hope the passionate team coding BetterBags sort this out soon, as I do like BetterBags's general look.

**Comment by TuttiRH** [comment]
Here is a small update the team from "Can i mog it" is working on this =)
https://gitlab.com/toreltwiddler/CanIMogIt/-/issues/314

**Comment by radhaz** [comment]
It's working for me with the latest release of each addon, can someone confirm and if so should this be closed/marked as completed?

**Comment by Frici42** [comment]
This has been working correctly for me for a while now, But I don't really make more than cursory use of **CanIMogIt**.
So not sure what work is missing still.
