### ISSUE TITLE
Gems show an ilvl over the stack count

### ISSUE THREAD

**Issue by fyperia** [Cidan/BetterBags#173]
### Addon Version

0.1.6

### World of Warcraft Version

Retail

### Describe the bug

Dragonflight crafted gems have an ilvl over their icon (rank 3 are 415, unsure if lower ranks are a different ilvl) despite gems themselves not having an actual in-game ilvl; this display conflicts with the actual stack count. For example if you have 2 of the same gem it shows as 4152.
![image](https://github.com/Cidan/BetterBags/assets/10620314/fcbdc0d3-0953-4a0b-955a-c22af2efbd8b)

### Steps to reproduce

Have Dragonflight gems in your inventory.

**Comment by Cidan** [comment]
Interesting -- this is what the API returns. I'll look into this.

**Comment by Cidan** [comment]
So, gems do actually have an item level, however if the stack is more than 1 right now, I hide the item level text. I did recently fix a bug with item level display however, which might have been causing some of this, though I'm not sure. I'll close this with the release of the next patch, and if it's broken still, feel free to re-open it.

Thanks!
