### ISSUE TITLE
[Feature]: Ability to "refresh" new/recent items into the sorted inventory (like adibags)

### ISSUE THREAD

**Issue by radhaz** [Cidan/BetterBags#176]
### Describe the feature

Could we get a button (or even a hotkey I suppose) that when initiated automagically moves the items from the new/recent items list into their sorted categories?

### Describe the implementation

In adibags if you hit the N button in the top right all items in the recent item category are automatically shuffled into their allotted categories. I am hoping for something similar in BetterBags, this feature is useful when farming for specific items as it allows you to shuffle down all the existing items so you can easily see what you're looking for rather than a very large swathe of items to wade through.

**Comment by Cidan** [comment]
Right click the bag icon at the top left of your bags.

**Comment by Cidan** [comment]
you're good -- this is actually something i need to make more clear, as i get this question a lot!

**Comment by MGraefe** [comment]
This doesn't work for me in Cata Classic using most recent version. Has this changed?

**Comment by silverhawke249** [comment]
bumping to say that right clicking doesn't work in cata classic.
