### ISSUE TITLE
[Feature]: More in depth search function?

### ISSUE THREAD

**Issue by radhaz** [Cidan/BetterBags#177]
### Describe the feature

Is there a way to get the search function "deeper" into an item such as the text for its use?

### Describe the implementation

An example would be the item [Curio of Abundant Happiness](https://www.wowhead.com/item=139808/curio-of-abundant-happiness) it's one of a myriad of "legacy" items that are used for Legion Champions. In adibags if I search "champion" the item is highlighted; however, in BetterBags the item is not highlighted. I am uncertain to what level BetterBags search goes(if it extends beyond title/item type) and realize the deeper the search has to go the more resources it would consume/the longer it would take. 

Would it be possible to make a function to search deeper into items?

**Comment by Cidan** [comment]
oh that's interesting -- that should show up. this might be a bug. i'll take a look at this.

**Comment by radhaz** [comment]
> oh that's interesting -- that should show up. this might be a bug. i'll take a look at this.

It also doesn't work when searching for "follower" from the Draenor Garrison items (example https://www.wowhead.com/item=114808/fortified-armor-enhancement ) if that helps narrowing down the troubleshooting process

**Comment by radhaz** [comment]
Closed to make a bug report
