### ISSUE TITLE
[Feature]: Abbreviate where possibl

### ISSUE THREAD

**Issue by prathmell** [Cidan/BetterBags#182]
### Describe the feature

Dragon Flight, Wrath of the Lich King, and so on are so long the majority of the name is cut off.  How about abbreviating the expansion name -e.g. DF, WotLK, MoP etc instead of spelling out each name in full.  Many other categories are very long as well and could be abbreviated, for example, Reputation Insignia could be simply Rep, Miscelllaneous could be Misc

### Describe the implementation

Not a config issue I think it's a core issue.

**Comment by Cidan** [comment]
This will never be done, as we do not make decisions on what category text looks like. All labels are from the Blizzard API and not generated by the addon.
