### ISSUE TITLE
[Feature]: put the version in the addon somewhere, perhaps in the help section

### ISSUE THREAD

**Issue by prathmell** [Cidan/BetterBags#186]
### Describe the feature

It may already be there, but I had to close the game and go to curse to get the version number for a bug report.

### Describe the implementation

In config, in the help, put the version number

**Comment by SpareSimian** [comment]
Desirable, but as a rule I just look in an addon's TOC file.

**Comment by Cidan** [comment]
I agree with this suggestion. I'll add it to the options window at a menu item on the left.
