### ISSUE TITLE
Unable to Purchase Reagent Bag Section in Bank

### ISSUE THREAD

**Issue by Rhinocrunch1** [Cidan/BetterBags#196]
### Addon Version

v0.1.7

### World of Warcraft Version

Retail

### Describe the bug

The option to purchase the Reagent Bag Bank Section is not possible.  The Reagent section opens as if you own it, even if you don't. 

### Steps to reproduce

Attempting to Purchase the Reagent bag in the Bank Window.

**Comment by AMaribo** [comment]
The reagent bank can now be purchased by clicking on the reagent bank tab on a character that does not own the tab yet.
