### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by GeorgeAtMOD** [Cidan/BetterBags#198]
### Addon Version

v0.1.7

### World of Warcraft Version

Retail

### Describe the bug

I open BetterBags.  I SHIFT+LEFTCLICK to search, and nothing happens.

### Steps to reproduce

1. Open BetterBags
2. SHIFT+LEFTCLICK

**Comment by Cidan** [comment]
What are you shift left clicking on? Can you show me a screenshot?

Also, do you have BugGrabber/BugSack enabled and installed?

**Comment by Cidan** [comment]
This issue is being closed as stale. If you can provide more info, please re-open the bug and we'll take a look at it!

Thank you!

**Comment by GeorgeAtMOD** [comment]
Sure, I'll show you a screenshot later today.

This is my work email, so I'll be replying from my personal email, ***@***.***

Thanks,
George      
________________________________
