### ISSUE TITLE
Bag only binds to the toggle open key, should bind to other open and close functions.

### ISSUE THREAD

**Issue by MyGamesDevelopmentAcc** [Cidan/BetterBags#20]
Hi, I got release 0.17, bank icon is missing when the addon is enabled, as well as shortcut does not open the addon. The only way I was able to see bag is when I talked to a merchant.
Cheers

**Comment by MyGamesDevelopmentAcc** [comment]
Why is the bug button hidden/removed?

**Comment by Cidan** [comment]
General hygiene of the UI — don’t worry, an option to unhide it is coming soon :)

**Comment by Cidan** [comment]
I've added an option to hide and show the bag button, with it defaulting to show. I've also added better handling of the 'esc' key. Unfortunately, the only way to keep the bags working as they are supposed to, is to only bind on Show All Bags, which will toggle the bag. Any other bind is somewhat hacky and unreliable.

Thanks for the report!
