### ISSUE TITLE
[Feature]: I would like to be able to customize the currency shown on the bottom left of the bag

### ISSUE THREAD

**Issue by lunamoth** [Cidan/BetterBags#201]
### Describe the feature

I would like to be able to customize the currency shown on the bottom left of the bag

If this feature was supported, I would be able to use BetterBags well instead of AdiBags.

### Describe the implementation

It would be nice to be able to select and use a currency that looks like the current AdiBags.

**Comment by peoii** [comment]
You can right now.  Click the bag icon in the top left -> Show Currencies and select the ones you wish to show in the feed in bottom left.
