### ISSUE TITLE
Empty tooltip after item was moved and cursor stays in the same position

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#206]
### Addon Version

v0.1.8

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

When moving an item between inventories or selling them, if you don't move your mouse after that, there will be an empty tooltip the same size as it was before. It will stay until you are no longer hovering the item slot.
![grafik](https://github.com/Cidan/BetterBags/assets/16212271/b8780b43-b2aa-4987-b300-0421e6535b36)
![grafik](https://github.com/Cidan/BetterBags/assets/16212271/d00d3177-7e99-42b9-8115-61b93e0d126a)

### Steps to reproduce

- Open bag and bank (or vendor, ..)
- Click item but don't move mouse

**Comment by zeptognome** [comment]
This was fixed long ago
