### ISSUE TITLE
Add a “vendor lock” option for individual items

### ISSUE THREAD

**Issue by Cidan** [Cidan/BetterBags#21]
Add a vendor lock option such that locked items can’t be sold or interacted with at all.

**Comment by Vilaric** [comment]
Cidan I don't know if you plan on adding the auto deposit reagent feature like you had in adibags, but would love a lock like this also for that feature as sometimes you don't want everything to deposit (ie Projection Prism)

**Comment by Cidan** [comment]
Lock has been added. I can't control what is deposited via deposit all reagents, and it looks like the Blizzard API ignores locks when it comes to depositing via the deposit all API.
