### ISSUE TITLE
[Feature]: Remove ilvl from gem icons 

### ISSUE THREAD

**Issue by GirlPlays** [Cidan/BetterBags#211]
### Describe the feature

Is there a way to add a feature to remove the ilvl from gems altogether? I know there was a fix recently to keep stack count and ilvl count from overlapping, but I would prefer the gems to not have an ilvl listed. 

### Describe the implementation

I would like to have the ilvls removed from the gems/icons; I wasn't even aware gems had ilvls before I downloaded BetterBags.

**Comment by AMaribo** [comment]
This was fixed. Gems no longer have item levels displayed.
