### ISSUE TITLE
[Feature]: Having Gear consolidated options to clear clutter inside Bags

### ISSUE THREAD

**Issue by Yozshura** [Cidan/BetterBags#213]
### Describe the feature

![image](https://github.com/Cidan/BetterBags/assets/12401590/84ce1950-ed3a-469a-9d81-371223f6ce41)

Hello, in previous addon Adibags, we had the option to consolidate the Gear Section, rather than having them separated. This would eliminate a lot of clutter inside our bags and we would have 1 big section for Gear and then all the small customization and types+ subtypes for other items would follow. I really hope this feature would get implemented. BetterBags looking extremely good so far. Thank you for your amazing work as always.

### Describe the implementation

Adding an extra option to have GEAR section consolidated.

**Comment by grumpypbear** [comment]
This is basically the only thing holding me back from going all in with BB atm. Not having all armour, weapons, legendaries, basically gear boe/bop etc all in the same area drives me bonkers lol. 

I love they can be divided up into type/sub-type, I just wish all gear was in the same general area of the bag. (Eg. atm armour -leather -cloth -misc etc is top left of bag and weapons are bottom right. And that's not including the way the addon sometimes shoves random stuff up between alphabetized sorting just to save space. I actually have A-leather > A-mail > Consumable-other > jewlcrafting > A-misc in my top row. And if more items are added to any of those categories their placement moves around. Compaction is set to none, which I thought would allow for empty space and neat lines with nothing being moved around but it does not.)

-----
This applies to other categories too. My bags have herbalism stuff on the right and mining stuff on the left, mining is higher up than herbs, and there's a bunch of other non-related categories between them.

It seems like subtypes aren't kept together with overall type. Ideally though I'd probably just like to be able to manually arrange types/subtypes. Drag them to where you want them in the bag and not have them reordered/shuffled around. (But I do also understand this is a new addon and there's a crazy amount of stuff to be triaged.)

**Comment by AMaribo** [comment]
As of June, you can now group categories by pinning them to the top of the bag.
To do so, click on the bag icon in the top-left of the bag, then click `Configure Categories`. In the list that appears to the left of the bag, click and drag categories to the top `Pinned` section to have them appear first in whatever order you designate. Shift-left click any items in this menu to move them to the top of the pinned section.
