### ISSUE TITLE
Deposite Reagents not working

### ISSUE THREAD

**Issue by karaktaka** [Cidan/BetterBags#217]
### Addon Version

v0.1.7

### World of Warcraft Version

Retail

### Describe the bug

When opening the bank and pressing "Deposite all Reagents" one can hear a sound of items being moved, but nothing is actually happening.

### Steps to reproduce

Go to the bank and open it. Have some depostiable items in bag and click on "Deposite all Reagents" in bank Tab.

**Comment by Cidan** [comment]
I can't reproduce this at the moment -- can you double check you actually have reagents to deposit? Also, do you have buggrabber and bugsack installed?

Also note, BetterBags does not actually trigger the move or make decisions on what to deposit. Depositing is done by a Blizzard API.

**Comment by karaktaka** [comment]
I had depositable Items in my bag, yes. I even took some more out of the reagent bank and pressed the button again. Closed/Opened the bank and tried again with the same result.

I do have buggrabber and bugsack installed, but they do not report any errors.

**Comment by Cidan** [comment]
Can you try the latest alpha build? I can't reproduce this at all no matter how much I try. I can also confirm the Blizzard API is being called.

**Comment by Rhaevyn** [comment]
I have a similar ask, I am not seeing a reagent tab in my bank window. I have bags turned off in ElvUI, is there another setting I need to look at? I can't even access my reagent bank, although asking it to deposit does work for me. Halp?

**Comment by Cidan** [comment]
@Rhaevyn Check the tooltip for the bank bag button at the top left of the bag a little bit closer :)

**Comment by karaktaka** [comment]
> Can you try the latest alpha build? I can't reproduce this at all no matter how much I try. I can also confirm the Blizzard API is being called.

Unfortunately not much of a difference with the latest alphabuild (v0.1.8-2-gca2d17b).
Btw, is it intentional that the bag does not open if I open the bank? Afair my other bag addons did that. (not sure if it was a setting, though)

**Comment by karaktaka** [comment]
Update: So that's a weird one. I tried with one of my other characters and it's working just fine there. Only my Evoker is affected by this bug it seems. Even after a full reset of the interface, the Evoker is the only one, that can not deposit Reagents to the Bank

**Comment by Rhaevyn** [comment]
> @Rhaevyn Check the tooltip for the bank bag button at the top left of the bag a little bit closer :)

Hahaha, I will, haven't logged in yet. Being blind is one of my specialties!

**Comment by Cidan** [comment]
@karaktaka Well, didn't expect that one. I don't have an evoker, but I'll make one and test -- been meaning to do their intro for a while anyway.

As for not opening when you hit the bank, yes, that's currently a bug that's on the bug list to fix.

**Comment by karaktaka** [comment]
Hey, in which release version is this implemented? I'm currently using 0.1.38 and I cannot confirm it working again. :(
