### ISSUE TITLE
Ghost items after selling items with Dejunk Addon

### ISSUE THREAD

**Issue by TuttiRH** [Cidan/BetterBags#219]
### Addon Version

v0.1.7-5-ga690f71

### World of Warcraft Version

Retail

### Describe the bug

Had a full inventory and i'm selling items automatic with the Addon "Dejunk".

Two times these two LUA Errors happens today with the new Alpha.
But not everytime i'm selling items.

### Steps to reproduce

1x BetterBags-Appearances/main.lua:318: bad argument #1 to 'upper' (string expected, got nil)
[string "=[C]"]: in function `upper'
[string "@BetterBags-Appearances/main.lua"]:318: in function `isUsableByCurrentClass'
[string "@BetterBags-Appearances/main.lua"]:353: in function `func'
[string "@BetterBags/data/categories.lua"]:137: in function `GetCustomCategory'
[string "@BetterBags/frames/item.lua"]:379: in function `GetCategory'
[string "@BetterBags/views/gridview.lua"]:87: in function `Render'
[string "@BetterBags/frames/bag.lua"]:213: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

--------------------------------------------------

35x BetterBags/views/gridview.lua:154: attempt to index field '?' (a nil value)
[string "@BetterBags/views/gridview.lua"]:154: in function `Render'
[string "@BetterBags/frames/bag.lua"]:213: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
view = <table> {
 Render = <function> defined @BetterBags/views/gridview.lua:61
 itemCount = 94
 itemsByBagAndSlot = <table> {
 }
 sections = <table> {
 }
 defer = false
 freeReagentSlot = <table> {
 }
 freeSlot = <table> {
 }
 kind = 2
 Wipe = <function> defined @BetterBags/views/gridview.lua:35
 content = <table> {
 }
}
bag = <table> {
 menuList = <table> {
 }
 searchBox = <table> {
 }
 sections = <table> {
 }
 toRelease = <table> {
 }
 currentView = <table> {
 }
 slots = <table> {
 }
 toReleaseSections = <table> {
 }
 currencyFrame = <table> {
 }
 moneyFrame = <table> {
 }
 isReagentBank = false
 drawOnClose = false
 views = <table> {
 }
 currentItemCount = 0
 kind = 0
 bottomBar = Frame {
 }
 frame = BetterBagsBagBackpack {
 }
 drawAfterCombat = false
 resizeHandle = Button {
 }
}
dirtyItems = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
}
sizeInfo = <table> {
 itemsPerRow = 15
 columnCount = 1
 height = 638.419067
 opacity = 100
 scale = 100
 width = 739.205383
}
categoryChanged = true
extraSlotInfo = <table> {
 freeReagentSlotKey = ""
 emptySlotByBagAndSlot = <table> {
 }
 emptySlots = 16
 emptyReagentSlots = 0
 totalItems = 92
 freeSlotKey = "4_28"
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Armor - Cloth = <table> {
 }
 Gem - Artifact Relic = <table> {
 }
 Battle Pet = <table> {
 }
 Armor - Miscellaneous = <table> {
 }
 Consumable - Flasks & Phials = <table> {
 }
 Armor - Leather = <table> {
 }
 Free Space = <table> {
 }
 Unknown - Demon Hunter = <table> {
 }
 Quest - Quest = <table> {
 }
 Armor - Mail = <table> {
 }
 Armor - Plate = <table> {
 }
 Hearthstones = <table> {
 }
 Junk = <table> {
 }
}
(for control) = "Armor - Leather"
sectionName = "Armor - Leather"
section = <table> {
 view = 2
 title = FontString {
 }
 fillWidth = false
 frame = Frame {
 }
 content = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 3_2 = <table> {
 }
 4_11 = <table> {
 }
 3_13 = <table> {
 }
}
(for control) = "3_2"
slotkey = "3_2"
_ = <table> {
 NormalTexture = BetterBagsItemButton524NormalTexture {
 }
 Stock = BetterBagsItemButton524Stock {
 }
 LockTexture = BetterBagsItemButton524LockButton {
 }
 isFreeSlot = false
 ilvlText = FontString {
 }
 Count = BetterBagsItemButton524Count {
 }
 button = BetterBagsItemButton524 {
 }
 IconQuestTexture = BetterBagsItemButton524IconQuestTexture {
 }
 frame = BetterBagsItemButton524parent {
 }
 Cooldown = BetterBagsItemButton524Cooldown {
 }
 IconTexture = BetterBagsItemButton524IconTexture {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 NormalTexture = BetterBagsItemButton524NormalTexture {
 }
 Stock = BetterBagsItemButton524Stock {
 }
 LockTexture = BetterBagsItemButton524LockButton {
 }
 isFreeSlot = false
 ilvlText = FontString {
 }
 Count = BetterBagsItemButton524Count {
 }
 button = BetterBagsItemButton524 {
 }
 IconQuestTexture = BetterBagsItemButton524IconQuestTexture {
 }
 frame = BetterBagsItemButton524parent {
 }
 Cooldown = BetterBagsItemButton524Cooldown {
 }
 IconTexture = BetterBagsItemButton524IconTexture {
 }
}
(*temporary) = 49
(*temporary) = 60.999985
(*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = 17.999992
(*temporary) = <userdata>
(*temporary) = 17.999992
(*temporary) = 0
(*temporary) = "attempt to index field '?' (a nil value)"
database = <table> {
 SetDefaultModuleLibraries = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Migrate = <function> defined @BetterBags/core/database.lua:293
 ItemCategoryExists = <function> defined @BetterBags/core/database.lua:230
 SetItemLevelEnabled = <function> defined @BetterBags/core/database.lua:120
 GetItemLock = <fu

**Comment by Cidan** [comment]
Thanks for the report! I just pushed a new Alpha build that fixes this -- if this comes up again, please reopen this bug.

**Comment by TuttiRH** [comment]
Installed the new release v0.1.8 and get that Error again.

2x BetterBags-Appearances/main.lua:318: bad argument #1 to 'upper' (string expected, got nil)
[string "=[C]"]: in function `upper'
[string "@BetterBags-Appearances/main.lua"]:318: in function `isUsableByCurrentClass'
[string "@BetterBags-Appearances/main.lua"]:353: in function `func'
[string "@BetterBags/data/categories.lua"]:137: in function `GetCustomCategory'
[string "@BetterBags/frames/item.lua"]:379: in function `GetCategory'
[string "@BetterBags/views/gridview.lua"]:87: in function `Render'
[string "@BetterBags/frames/bag.lua"]:213: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Cidan** [comment]
This is related to the BetterBags-Apperance plugin, which is not written by us -- disable that addon and reach out to the author.
