### ISSUE TITLE
Add a context menu for items.

### ISSUE THREAD

**Issue by Cidan** [Cidan/BetterBags#22]
Shift-left clicking an item will bring up a context menu so actions can be taken on individual items.

**Comment by steven-fuller** [comment]
just a note that 'shift-left click' is normally used for splitting stacks and might be confusing if inconsistent

**Comment by Cidan** [comment]
Solid advice, thanks.

**Comment by Cidan** [comment]
This is not feasible without taint, or at least, a lot of hacks that may taint. Obsolete.
