### ISSUE TITLE
Opening BetterBags also opens my normal bag

### ISSUE THREAD

**Issue by pcg79** [Cidan/BetterBags#224]
### Addon Version

v0.1.7

### World of Warcraft Version

Retail

### Describe the bug

I assume this is a bug and not a feature request.  But if it's working as intended, please consider this a feature request.

Opening BetterBags also opens my normal bag.  I assume like AdiBags that it's not supposed to.  I don't see an option to not do that.

### Steps to reproduce

1. hit "b" to open my bags
2. BetterBag and normal bag both open.

**Comment by zeptognome** [comment]
>     2. BetterBag and normal bag both open.

Is your 'normal' bag the Elv UI bag by any chance? You can turn that off in Elv if so.

**Comment by Cidan** [comment]
As mentioned, this is because you have another addon opening the bags as well. Disable the bags in Elv or whichever other addon you use.
