### ISSUE TITLE
[Feature]: In-bag creation of new custom categories

### ISSUE THREAD

**Issue by zeptognome** [Cidan/BetterBags#227]
### Describe the feature

I think adding a feature to create a custom category without going to the options screen would be a nice QoL improvement.

### Describe the implementation

- User hits a hotkey, button, or menu item while the in bag/bank/reagantbank view and a 'New Category' section is added to the container window similar to the 'free space' virtual section that would offer a drag target for the user to insert the first item.

- This section would be displayed either first or last in the container window. 

- This target should look like the 'free space' display, but might have the text 'New' or a target icon or such instead of a count.
 
- Once a single item is added, the section is treated like a normal category section wrt all functions.
 
- If the virtual section is not used to create a category before the container window is closed, the section is thrown away and no category is created.
 
- If a custom category name of 'New Category' already exists, a uniquing digit is appended automatically.
 

In conjunction with the eventual drag and drop to re-categorize items, plus the renaming of categories from the bag window, the need to use the options screen for category management is greatly diminished.

**Comment by Cidan** [comment]
I'll refine this, but yes, making a new category from the bag is a good idea. Stay tuned!
