### ISSUE TITLE
Non-clickable ghost item in bank (Show Bags view only)

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#230]
### Addon Version

v0.1.8

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

After moving some items around between bank and bag on my bank char, I got this ghost item which is only visible in "Show Bags" mode. I cannot click it, move it or hover it. Also no lua error happening. Reloading did not fix it either.
![grafik](https://github.com/Cidan/BetterBags/assets/16212271/5fc1d369-87b9-4385-9eaf-c2b0a754e909)
The missing item here is a stack of wool cloth.

**Some additional info after posting**
I was not able to entirely get rid of this. Disabling and enabling BetterBags did not help. Relogging at least brought back the correct icon for it, but I can still not click on it or move it in the "Show Bags" view.

### Steps to reproduce

Didn't find out any details. Just moved some items from bank to bag and vice versa in regular "Category" mode. Then wanted to check how much next bag slot would cost and saw this.

**Comment by Cidan** [comment]
Can you test
