### ISSUE TITLE
Always empty slot

### ISSUE THREAD

**Issue by psykzz** [Cidan/BetterBags#232]
### Addon Version

v0.1.8

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

![image](https://github.com/Cidan/BetterBags/assets/1134201/f2705697-2442-4cff-80bb-95b630925a1d)

If you fill every slot, you'll still be shown a slot which can confuse you in knowing if the slot is free or not.

Visually there is no difference between 1 slot free, and 0 slots free.

The default bag UI does show the correct value however.

![image](https://github.com/Cidan/BetterBags/assets/1134201/fbd62fd8-424d-4816-9bf7-b0a31b18ecab)

### Steps to reproduce

Fill every slot

**Comment by DJSchaffner** [comment]
Duplicate of #116

**Comment by psykzz** [comment]
ah i thought it was about something else.
