### ISSUE TITLE
[Feature]: Sort bags to stack any stackables

### ISSUE THREAD

**Issue by psykzz** [Cidan/BetterBags#233]
### Describe the feature

When clicking sort bags, attempt to first stack any stackable items.

### Describe the implementation

During "sort" first loop through and find items that are not max stack.
Stack items
Continue with sort.

### Expectation

I would expect clicking sort bags to have stacked all this wool cloth.

![image](https://github.com/Cidan/BetterBags/assets/1134201/cd390a05-13f9-4a7f-9340-2418ba37c8d8)

**Comment by Cidan** [comment]
In Classic this is because Blizzard removed the API from Classic to sort bags entirely, to make sure Classic was authentic, bag management headaches and all.
