### ISSUE TITLE
[Feature]: Hiding category

### ISSUE THREAD

**Issue by bloerwald** [Cidan/BetterBags#236]
### Describe the feature

The ability to hide item categories is useful for 
- "I always need this item in my bag but the effect is passive" (dark moon faire book, WoD pickaxe/herbalism gloves) or 
- "I use this item a lot and won't ever move it out of bags, but I have the effect bound somewhere" (teleport items, goblin gliders)

### Describe the implementation

A checkbox in the category options, or a "visibility" sub-menu on the bag button. A context menu on the category won't work for toggling visibility back on. The sub-menu is likely better UX since it allows for rather quick toggling instead of having to crawl through options in a separate window.

**Comment by ropp5pop** [comment]
This is the only reason I'm still on Adibags, and have been checking this issue regularly for any changes so figured I'd make a comment.
I don't think users in general realize the scope of the advantages this bring so I get it's not a priority.
When I open my bags i only see what I actually need to see, which aren't really that many.

### How I hide stuff:
I've got a number of custom **[Categories]** I often keep hidden.  Right now I've got 29 different items over maybe 35 slots that generally are hidden in my Bag-view.

- **[1. Hide]** ~10 items like Hearthstone, Jeeves, Wrap of X, Gnomish Army Knife etc  - Always hidden unless adding new item etc.
- **[2. Flask/Lxr/Pot]** ~5 different liquid consumables also bandages. - Toggle on visibility when managing stacks.
- **[3. Misc. C]** ~10 items like Flares, Drums, Vanishing Powder. - Toggle as above.
- **[4. Tabards]** ~3 - Toggle only when switching.
- And some more like the above. The estimated number is in the Bag-view but in the Bank I often got more.

I also hide the junk and add items as junk as I play. I auto-sell everything there.

Thank you for putting in the work of developing a great addon.

**Comment by Cidan** [comment]
This is definitely being worked on -- the last little bit of UI changes needed to make this happen are finishing up now. It's going to be part of the new category sort menu that was just released. Sit tight.

**Comment by AMaribo** [comment]
Categories can be hidden as of v0.1.71. Right click on the category in the Configure Categories slideout menu to hide the category.
