### ISSUE TITLE
AdiBags compatibility: Custom Filter widget broken

### ISSUE THREAD

**Issue by bloerwald** [Cidan/BetterBags#237]
### Addon Version

v0.1.8

### World of Warcraft Version

Retail

### Describe the bug

With AdiBags v1.10.24 and BetterBags v0.1.8 both installed, modifying AdiBags categories is no longer possible, probably due to reusing the AceConfig widget partially. In AdiBags, the widget always claims to be completely empty:

![image](https://github.com/Cidan/BetterBags/assets/2866005/2204bf57-d446-4c74-8808-5c667167860f)

### Steps to reproduce

Install both addons, open AdiBags options > Filters > custom.

**Comment by SpareSimian** [comment]
Good guess. Based on your hint, I changed the name of the custom ItemList control to BBItemList and AdiBags started displaying item lists against. Here's a patch:

```
diff --git a/BetterBags/config/config.lua b/BetterBags/config/config.lua
index 297ff4c..1da3e01 100644
--- a/BetterBags/config/config.lua
+++ b/BetterBags/config/config.lua
@@ -140,7 +140,7 @@ end
 function config:OnEnable()
   self.helpText = {}
   self:CreateAllHelp()
-  GUI:RegisterWidgetType("ItemList", config.CreateItemListWidget, 1)
+  GUI:RegisterWidgetType("BBItemList", config.CreateItemListWidget, 1)
   LibStub('AceConfig-3.0'):RegisterOptionsTable(addonName, function() return self:GetOptions() end)
   self.frame, self.category = LibStub("AceConfigDialog-3.0"):AddToBlizOptions(addonName, "BetterBags")
   LibStub("AceConfigDialog-3.0"):SetDefaultSize(addonName, 700, 800)
diff --git a/BetterBags/config/customcat.lua b/BetterBags/config/customcat.lua
index 0cade21..0742f68 100644
--- a/BetterBags/config/customcat.lua
+++ b/BetterBags/config/customcat.lua
@@ -26,7 +26,7 @@ function config:CreateCustomCategoryConfig(category)
       items = {
         type = "multiselect",
         name = L:G("Items"),
-        dialogControl = "ItemList",
+        dialogControl = "BBItemList",
         order = 1,
         values = DB:GetItemCategory(category)
       },
```

**Comment by zeptognome** [comment]
Closing this as Adibags support has been discontinued, and additionally, BetterBags is moving away from using the AceConfig for custom category item lists
