### ISSUE TITLE
Add gear set sections

### ISSUE THREAD

**Issue by Cidan** [Cidan/BetterBags#24]
Add automatic gear set section breakout with a toggle to enable or disable it.

**Comment by FlyingDiver** [comment]
Also, I just did LFR on that toon and got some new pieces.  I set them up in my gear sets, but the groups would not show in the bag frame.  /reload did not help.  I had to log out and back in to get the groups to show up.

**Comment by Cidan** [comment]
So it's a bit deceptive, but they are sorting correctly.  The columns sort left to right by the number of sections, so if you look at the first column, 2 sections down, and the second column, 2 sections down, you'll see they sort correctly (compaction non-withstanding). I do this because it keeps sorting deterministic -- if I did it based on the sizes of sections, then sections would dramatically shift based on the size of the section. The non-deterministic sorting is what AdiBags did, and was a chief complaint of folks from all sorts of feedback channels.

That being said, I do plan to add a tighter compaction algorithm that sorts things as closely as possible, however that still won't promise that like sections will sort together. I could spend more time on this, but N-dimensional sorting is a non-trivial bit of work that, while can be done, would take up more time than I care to spend right now. This is probably the single most complex topic of the addon, and I'll revisit it down the line, as there's a multitude of opinions to take into account here.

For your second point, things not showing up in a gear set -- are you saying you added a new item to a gear set, and it didn't show up in the inventory, or you made a new gear set, and it didn't show up? It not working without a full quit and restart is very, very odd -- a /reload completely eliminates all state and addons can't hold onto state in memory across reloads, so that's very surprising. If possible, a reproduction case would be extremely useful here.

Thanks!

**Comment by FlyingDiver** [comment]
This seems to be implemented as intended.
