### ISSUE TITLE
Items disappear 

### ISSUE THREAD

**Issue by TuttiRH** [Cidan/BetterBags#245]
### Addon Version

v0.1.8-3-g819b191 (2024-02-25)

### World of Warcraft Version

Retail

### Describe the bug

Important:
This only happens after first login or Reload. Don't do other steps!

1. Open Betterbag
2. Left Click on the Bag and set "Show Bags"
3. Left Click on the Bag -> Open Options Screen
4. Go to "Backpack"
5. Switch Sorting from "Alphabetically" -> "Size Descending" -> "Size Ascending"
6. Same happens when you use the "Item Sorting" Section
7. Same happens when you use the "Display" Section

### Steps to reproduce

<img width="588" alt="25-02-2024_19-48-24" src="https://github.com/Cidan/BetterBags/assets/3890415/745b8447-95b6-4736-920a-9ed3fdc5d21b">
<img width="584" alt="25-02-2024_19-51-32" src="https://github.com/Cidan/BetterBags/assets/3890415/290359a3-5849-4d6d-9c9f-3d25db3d87ea">

**Comment by Cidan** [comment]
Thanks, Fixed this in the next patch.
