### ISSUE TITLE
Unable to Drag and Drop into Custom Categories

### ISSUE THREAD

**Issue by perks** [Cidan/BetterBags#246]
### Addon Version

v0.1.8

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

No stacktrace errors.

When creating a custom category, the Drag and Drop feature does not seem to work
![image](https://github.com/Cidan/BetterBags/assets/1820298/ec6e4fd8-2706-416d-afb7-52e22b2fa5ec)

### Steps to reproduce

Create a new category

Attempt to add an item

**Comment by Cidan** [comment]
You need to drag, hold, and drop. It can't just be pick up and drop -- this is a known issue and it will be resolved in a later update.
