### ISSUE TITLE
Add manual sections

### ISSUE THREAD

**Issue by Cidan** [Cidan/BetterBags#25]
Add manual sections that can be named and configured. Manual sections always sort first.

**Comment by SpareSimian** [comment]
It would be nice if I could import the manual configuration from AdiBags. I've got a lot of work put into that.

**Comment by Cidan** [comment]
> It would be nice if I could import the manual configuration from AdiBags. I've got a lot of work put into that.

We won't be doing this, unfortunately. It's a feature that would be used by a fraction of a fraction of one percent of folks for something that will take me many more times the hours than it being worth.

The manual section creation feature will be significantly improved over the current one, with a cleaner workflow that is easier to use and faster all around. Setting categories back up shouldn't be anywhere near as time consuming as it was in AdiBags.

Thanks!

**Comment by SpareSimian** [comment]
Ok, I might end up writing it myself. It's really the only customization I use. 

A couple of ones I've set up are "Container" for anything that can be looted (so it doesn't disappear and I forget to open it) and the Shadowlands "currencies" like anima and relics that have to be turned in to turn them into the actual currency. I've got a section for grey cosmetic items which normally end up in the Junk category.

**Comment by MyGamesDevelopmentAcc** [comment]
The main advantage of AdiBags were sections, and an ability to categorize yourself certain things. If this is what your aim still is, to create a next gen AdiBags, then I do think this one, this ticket should be a priority.
In my opinion manual sections are ok to initially be only sorted first. As in for the long term it would be best to allow users to drag and organize sections themselves or configure them somewhere. This is one of the lacking things in AdiBags, where you do not really have a control over order, apart from trying to put them under some sections (which are unknown by default what is the display priority) and then to use alphabet. Instead of that all sections could be allowed to be manually, by users, configured for their priority. I do believe that would be something which would make this addon shine among all the other bag addons.

**Comment by Cidan** [comment]
> If this is what your aim still is, to create a next gen AdiBags, then I do think this one, this ticket should be a priority.

Yes, this is the plan. We've been discussing it on Discord and it's well under way in a branch -- please see the most recent commits for more information.

> In my opinion manual sections are ok to initially be only sorted first.

I probably won't do this.

>  As in for the long term it would be best to allow users to drag and organize sections themselves or configure them somewhere. 

I may get to this, I'm undecided if I'm going to implement this. More below.

> This is one of the lacking things in AdiBags, where you do not really have a control over order

I agree fully on this one, however it leads to some really interesting problems between what users think they want, versus what they actually want. AdiBags bin packs sections such that they fit into the bag window as tight as possible. Without some sort of bin packing, you are left with huge, giant gaps in your bags in a need to maintain a specific order. This creates a really weird/bad bag experience overall where sometimes up to half of your bag frame is just blank space.

What I've opted to do with BetterBags is a bit cleaner for the short to medium term and offers a balanced middle ground, such that sorting is deterministic in all cases, but the order is still decided by the user via various sorting algorithms. I've also optionally added a compact mode, in which a section that can fit into a row above it will do so. The combination of these two mechanism has produced really nice, and consistent results. There are also sane defaults which communicate this on first install.

Over time, I plan to slowly tweak this, and I may add a non-deterministic sorting mode for sections. However, N-dimensional bin packing is a non-trivial problem to solve computationally, and while I do have some prototypes, the solutions are all O(n^2) and not optimized yet, i.e. dynamic programming and/or genetic algorithms (maybe).

Ultimately, this is an area where I spend a significant amount of my time and energy in research and development, and will probably continue to do so for quite some time.

>I am attaching screenshots for visibility of differences I have between AdiBags and BetterBags.

I think BetterBags looks much better :)

**Comment by MyGamesDevelopmentAcc** [comment]
I am sorry if I am too dumb, but can you please explain why there is a
n-dimensional bin packing problem?
Maybe I am trivilizing this in my head, but for me first there is a sorting
of categories. Then each category has a number of items in it. Sorting of
categories is nlogn (not that it matters in the number of N we are facing
here), then you look into a number X constrained by user - ie. width
(number of items in category till it starts to fold to next line). If in
category there is less than X, check next category whether to draw it to
save space. If next category also does not break line, ie combined items
with the previous one still is lower than X, draw it on the right. If not,
go below UNLESS this would be a breaking category ie. category that by
default should start from the top, then start creating next column.
Number of columns would be determined by reaching a breaking category, not
by "constrain" setup by the user <- that is how I would like to use it as
then I would not have to look where my category has landed this time. So I
would by default have always certain categories for each column. (This also
happens now when categories grow -> with better bags I had issues with
lower number of categories where the top went outside of view as the
category had so many items in it, and I couldnt do anything about it as
menu was far above.)
If you do not want to create something like this, then I think maybe it
could be possible to draw till the end, then check how many rows were
created, and divide to have a proper number of columns.
I am sorry if I am overtrivilizing this, just sharing how I thought of
creating something like this in the past, so as I havent started coding
this there most likely is a ton of things I just dont see. But happy to
help if you have time and want to explain the challange with n dimensions
or give me a link to discord if it was explained there :P

Cheers, and keep up the great work!

sob., 9 gru 2023 o 17:49 Antonio Lobato ***@***.***>
napisał(a):

**Comment by Cidan** [comment]
You’re definitely not dumb at all, please don’t ever say that about yourself!

> with better bags I had issues with
lower number of categories where the top went outside of view as the
category had so many items in it, and I couldnt do anything about it as
menu was far above.

This is an immediate concern, outside of anything else. This physically should not be possible anymore, as I constrain a rectangle around the menu button to be on screen at all times, irrespective of the size of the bag window. Can you reproduce a case where this isn’t so?

Aside from that, what you described is n-dimensional — that is, sorting based on multiple dimensions (section name, maximum row width in a section, number of rows in a section). However, manually setting sections is not explicitly what I was talking about there — I apologize, I should have been clear that was unrelated to manual sorting. BetterBags is broken down into a column and grid concept, with no strict row abstraction as I rely on a sorted table to determine the row. I take the position of a section within the table mod the number of rows and position it in the correct column. I sort the section table with that in mind.

I already do compress columns “upward” if they can fit side by side on the section above it. This is an optional setting in the menu, and I do this in a similar manner as you described. The main reason I am hesitant on implementing user positional sorting is I actually had this implemented in a branch of AdiBags and tried it out for a while. I ran into two distinct UX issues, chiefly what to do with new sections as they appear. Remember that I don’t keep a list of sections — all sections are derived in real time from the item’s category or other information from the Blizzard API. This led to an awkward usability problem in which users were constantly having to re-sort sections, which was further compounded by some sections disappearing and no longer being available to sort. The other problem is that user sorting led to massive wide open gaps in the bag. This is because I was not allowed to touch manual sorts, so in some cases you would end up with awkward positions, especially if sections came and went. It ended up being even worse than AdiBags default sorting in some cases!

I explicitly do not want to keep track of or sort sections that the add on has seen, as these sections have changed in the past, more than once, and I refuse to get into the management of Blizzard API data as it’s a real chore.

Ultimately, for the time being, I won’t be adding custom sorting of sections based on user input today. Right now the bag is very usable for new players and casual users, which is 99.9% of the players using AdiBags today. I had the chance to talk to a good chunk of users face to face at TwitchCon this year, including some big name streamers, to get some really solid feedback on where to go. Where we are going right now strikes a good balance that overall, the majority of users are going to be happy with.

Thanks for your feedback!

**Comment by Cidan** [comment]
Oh, one thing I forgot to add — something I considered for a while and did try, was putting a slightly larger space between items on the vertical axis, such that I could fit entire sections end to end in one long chain, and still leave room for the section title. It worked, but the cognitive benefits of having item sections were completely lost. I decided not to go ahead with that implementation.
