### ISSUE TITLE
iLvl on items retains old values when swapping to new gear

### ISSUE THREAD

**Issue by Kuipo** [Cidan/BetterBags#252]
### Addon Version

v0.1.9

### World of Warcraft Version

Retail

### Describe the bug

When I swap out to a new item with a higher iLvl, the old item that it replaced gets put in it's place in the bag but with the original item's iLvl.  You can see in this screenshot that I've equipped the 306ilvl item but the icon in the bag that I'm hovering is still showing 306 instead of 246.
![image](https://github.com/Cidan/BetterBags/assets/6427669/5a3c38e7-9806-4724-ac48-19a035e0e273)

### Steps to reproduce

1. Have an item that you want to equip in your bag that has a different ilvl than your equipped item
2. Open your bags and take note of the iLvl of the item you have equipped vs what you are going to equip
3. Right click item to equip it
4. Note the iLvl of the item that has now taken place of the item you just equipped

**Actual Results**
The item in the bag will still show the ilvl of the item you just equipped

**Expected Results**
The item in the bag should be updated and show the correct ilvl

**Comment by Frici42** [comment]
I used to be able to have this issue often but have not been able to replicate since a few versions now, Does it still happen? 🤔
