### ISSUE TITLE
add filters tab in settings and manual filtering

### ISSUE THREAD

**Issue by G1ak1** [Cidan/BetterBags#254]
### Describe the feature

hey there. long time fan of adibags. can u add the filters tab in addon settings and the chance to make manual filters like adibags has???

would be amazing. great job btw

thank u <3

### Describe the implementation

addon settings
filters
manual filtering
to add my own categories

**Comment by Cidan** [comment]
This has been implemented for a while now. Please check the options screen (click on the bag icon in the bag), or type `/bb` in chat.
