### ISSUE TITLE
Bag doesn't close with same button to open

### ISSUE THREAD

**Issue by mattlinsky** [Cidan/BetterBags#255]
### Addon Version

0.1.9

### World of Warcraft Version

Retail

### Describe the bug

It seems like when pressing the hotkey to open bags ("b" for me) you can't press the same button to close them.
Pressing escape still works

### Steps to reproduce

press b
press b
press escape

**Comment by Cidan** [comment]
What action do you have bound to B in your client key bindings?

**Comment by mattlinsky** [comment]
Toggle bag 1 (default)
It works properly with Open all bags. Didn't have that issue with any other bag addons. Not sure if you want to change or not on your end. Either way thank you.

**Comment by Cidan** [comment]
F8 F9 F10 F11 are the defaults for toggling bag 1-4 in the WoW client. B and F12 toggle the backpack, and shift+b opens all bags. We intentionally don't listen on the toggle bag 1-4 binds, as they are meaningless in this context.

Thanks for the report!
