### ISSUE TITLE
[Feature]:  Toggle currency to show when bags open

### ISSUE THREAD

**Issue by Faulkal** [Cidan/BetterBags#262]
### Describe the feature

I would love to see currency displayed whenever i open my bags.

some other options. 
-hide any 0 currency items
-configure what you want to show or hide. time warp badges shown but ancient mana hidden even when above zero 

### Describe the implementation

In a menu to choose which currency to hide/show

**Comment by AMaribo** [comment]
You are able to select which currencies to show at the bottom of the bag (up to 7), by left-clicking the bag icon in the top-left corner of the bag, choosing `Currencies`, then left-clicking on any currencies you want shown at the bottom of the bag.
