### ISSUE TITLE
Significant Lag on Removing Item from Bag

### ISSUE THREAD

**Issue by thejames76** [Cidan/BetterBags#264]
### Addon Version

v0.1.6

### World of Warcraft Version

Retail

### Describe the bug

When completing a dragon riding race, the screen freezes for about 1-2 seconds. I can replicate this issue every time with no other addons running. My hard drive is a M2 evo-something or other for all my games (for lack of specifics on that).

Additionally, I will see random freezes of a similar nature doing various quests and now I believe these freezes are attributed to BetterBags writing to whatever files it needs during game play.

### Steps to reproduce

1 - Disabled ALL addons except BetterBags
2 - Go do a Dragonriding Race in the Dragon Isles (starting it will give you an item to reset the race)
3 - On completion of the race, screen freezes when the item is removed.

**Comment by Cidan** [comment]
You are on an old version of the addon. This has been resolved in the later updates.
