### ISSUE TITLE
'BetterBags' tried to call the protected function 'CastSpell()'

### ISSUE THREAD

**Issue by nilscroes** [Cidan/BetterBags#265]
### Addon Version

v0.1.10

### World of Warcraft Version

Retail

### Describe the bug

Can't disenchant items.

`6x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterBags' tried to call the protected function 'CastSpell()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `CastSpell'
[string "@FrameXML/SpellBookFrame.lua"]:720: in function <FrameXML/SpellBookFrame.lua:660>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
`

### Steps to reproduce

1. Open spellbook
2. Click on disenchant
3. Error pops up

**Comment by Cidan** [comment]
I can't reproduce this locally -- can you try this with all other addons disabled just to test?
