### ISSUE TITLE
"Show bags" still showing items in show-bags layout even after it is toggled off

### ISSUE THREAD

**Issue by tmmgeekette** [Cidan/BetterBags#267]
### Addon Version

v0.1.11

### World of Warcraft Version

Retail

### Describe the bug

betterbags toggling of "show bags" does not always work as expected. 

![Xnip2024-03-03_15-03-44](https://github.com/Cidan/BetterBags/assets/20545285/846dfadc-1816-45a6-9881-0a4b7f5760fc)

Wow retail on macbook pro.  installed the addon for first time today. 

### Steps to reproduce

1. Open bank full of items with betterbags enabled.   
2. click on 'show bags' and the bags become viewable on upper left of window.  Items also show up separated by bags as expected.     
3. Click "show bags" again to toggle it off and the bags on upper left disappear.  But all items still show up separated by bags.  It does not return to previous, non-show-bags layout.    It is still stuck this way after closing all bags and clicking on banker again.    

I got it to return to normal by playing around and opening and closing windows, clicking the toggle on and off, etc.   Then it returned to normal.      But repeating the above steps broke it again.

**Comment by tmmgeekette** [comment]
i also have a buttload of reagents that won't show up in this view in their respective bags...  but I'm assuming you already have a ticket for that somewhere

**Comment by Cidan** [comment]
Confirmed, will push .12 out today with a fix.

**Comment by Cidan** [comment]
.12 pushed to all addon sites.

**Comment by Cidan** [comment]
Correction, out with .13

**Comment by tmmgeekette** [comment]
still broken.    I installed bugsack hoping to catch an error but it's not getting any.

**Comment by Cidan** [comment]
I can't reproduce this anymore -- what part is broken? Bags continue to stay broken out?

**Comment by tmmgeekette** [comment]
yes..  banker bags stay broken out.  bugsack has errors now too.  trying to figure out how to share these.

**Comment by Cidan** [comment]
please do -- I'll fix them right away. you're on .13?

**Comment by Cidan** [comment]
Also you can just copy/paste the errors in here

**Comment by tmmgeekette** [comment]
yes i'm no .13.    trying something first.

**Comment by tmmgeekette** [comment]
Ok that was strange.   I deleted betterbags and it's 2 dozen plugins, made sure it was gone from Interface/AddOns, then reinstalled it WITHOUT all the addons.   Now I get no bugsack errors but the banker bag started out broken out from the get go.    I never restarted wow, just did reload from the cli so maybe something was loaded into memory .    gonna try restarting.  
![Uploading Xnip2024-03-03_17-12-47.jpg…]()

**Comment by tmmgeekette** [comment]
![Xnip2024-03-03_17-12-47](https://github.com/Cidan/BetterBags/assets/20545285/ca91f775-0fa6-424a-866c-965e48470ff6)

**Comment by Cidan** [comment]
that's actually a known issues, toggle the bag show button and it will fix itself. deleting an addon doesn't delete the data for it, that's in a different folder in the wow folder. it looks like it might have been a plugin that was broken -- you may want to reach out to that author if you figure out which one.

**Comment by tmmgeekette** [comment]
figures.   I logged in with a character i never used betterbags with and it still opens the bank bags broken out.       so you're saying i should toggle 'show bags' ON and then do what, log out?  resrtart the game?

**Comment by Cidan** [comment]
turn it on then off, and it should go back to normal bags -- i have a patch for bags being broken out on boot w/o the window showing soon.

**Comment by tmmgeekette** [comment]
tried that.  hasn't worked for me.   where is data for it stored?  perhaps deleting that will fix it?

**Comment by Cidan** [comment]
let me put out .14 with the proposed fix -- i would rather try to get you out of this broken state the "right" way in case this affects other people. give me like 2 min.

**Comment by Cidan** [comment]
Okay, just pushed .14. If for whatever reason this doesn't work, `_retail_\WTF\Account\<your account name>\SavedVariables\BetterBags.lua` has the settings file you can delete.

**Comment by tmmgeekette** [comment]
cool.  the update did not fix it, but deleting the shared files for betterbags did.  thanks!

My other issue is that my reagents won't show up in 'show bags' view.  and breaking bags in the "reagent bank" doesn't do much.  it still shows everything in one big bucket.    I looked around and I think i see a ticket for that?  altho it states that depositing reagents doesn't work.  it works, just can't see it.

**Comment by Cidan** [comment]
so this is by design -- this is because the way the Blizzard API works for banks is weird. you have to switch "tabs" under the covers, and that is what decides where right clicking an item in your backpack goes. I can't hijack either and make it magically deposit correctly, so I decided to make it explicit. there's no fix for that currently, and I expect it to get even more confusing with warband bags, unless blizzard redoes the API.

**Comment by tmmgeekette** [comment]
Ah I didn't know that.  maybe there's a way to hide reagent bags and show then in the "reagent bank" side but broken up.   

at any rate.  thanks for the work you put into this addon.   as it is, I still have to switch between this one and bagnon.
