### ISSUE TITLE
Can't add items to custom categories

### ISSUE THREAD

**Issue by Fizgig1973** [Cidan/BetterBags#271]
### Addon Version

v0.1.14

### World of Warcraft Version

Retail

### Describe the bug

Attempting to add items to custom categories doesn't seem to be working. It tells me to drag an item to the new category, however it doesn't drop in, or do anything else but stay on the mouse.  

Only BetterBags addon installed.

### Steps to reproduce

Create a custom category and attempt to populate it.

**Comment by Cidan** [comment]
You need to click, drag, and hold + let go over the text in the text box. You can't click and pick up. Right now, the text area is small, but this is slated to be fixed in another issue and is a limitation of the library used to make that menu.
