### ISSUE TITLE
Can't drag items to a newly created custom category.

### ISSUE THREAD

**Issue by blzrkr** [Cidan/BetterBags#273]
### Addon Version

0.1.14

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

Can't add items to a newly created custom category.

### Steps to reproduce

1. Create a new custom category
2. Try dragging an item into the area where it says drag items here. Nothing happens.
3. Hold shift and click on the label called item
4. The item gets added but to a new custom category called item.
5. I uploaded a clip of the bug to this youtube video https://youtu.be/PFJ8dsuunEA

**Comment by Cidan** [comment]
1) The "Item" header bug is a known issue and will be resolved soon.

2) To add an item, you need to click, drag, and hold the left mouse button. You can't pick up and click the item in, you have to drag and hold, then let go over the text. This will be resolved in a future update as well.

**Comment by czarl21** [comment]
where do we drop the item? "let go over the text"...which text? 
"Items" or the "drag an item from here..." header box?

I can't get to get his feature to work.

I like having all my "CACHE" rewards go into one place...so maybe you could consider that as an include category?  (so many satchels, treasures. caches to open)..

ty, nice looking addon and I am slowly transitioning from AdiBags

**Comment by Fizgig1973** [comment]
For what it's worth, this doesn't work for me either. 

Dragging over the category and releasing the left button doesn't do anything. The category does highlight, but nothing is able to be added.

Really the only thing I miss from Adibags.

**Comment by Cidan** [comment]
Improved this experience across the board, should behave better now across the board.

**Comment by czarl21** [comment]
> Improved this experience across the board, should behave better now across the board.

yep..working now

Ty
