### ISSUE TITLE
[Feature]: Add ability to search by equipment location

### ISSUE THREAD

**Issue by williamsonm** [Cidan/BetterBags#275]
### Describe the feature

As a user, I would like to be able to search by equipment location (e.g. chest, feet, etc.) in order to find items more quickly.

### Describe the implementation

Add another search prefix named `loc:`, similar to the existing `type:` or `exp:` prefixes, that will allow searching by the equipment location value stored in the item info.

itemInfo.itemEquipLoc contains values like [head, neck, cloak, chest, wrist, hands, waist, legs, feet, finger, trinket]

**Comment by Frici42** [comment]
I know you already have a PR for this #298 but figure replying here as a second user that would be delighted to have this feature  will help keep it along as a worked on option.

**Comment by KestrelWild** [comment]
Would really love to see this added.
