### ISSUE TITLE
7th bank bag missing

### ISSUE THREAD

**Issue by Faelwen** [Cidan/BetterBags#277]
### Addon Version

v0.1.14

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

On characters that have all their bag slots unlocked in the bank, the 7th bag and its content doesn't appear. Only the content of the first 6 bags does. If an item is transfered to the bank and goes to the 7th bag, it "disappears".

### Steps to reproduce

1. Open bank on a character that has all 7 bank bag slots unlocked and equiped.

**Comment by Cidan** [comment]
Fixed and released
