### ISSUE TITLE
forbidden action blocked. 

### ISSUE THREAD

**Issue by Faulkal** [Cidan/BetterBags#28]
was trying to combine a scrap of black dragonscales and a petrified orb when this error happened. A box showed up on the screen saying BetterBags has been blocked from an action only available to the blizzard ui. you can disable this addon and reload the UI. 

1x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterBags' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1424: in function <FrameXML/ContainerFrame.lua:1333>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1476: in function <FrameXML/ContainerFrame.lua:1463>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Cidan** [comment]
Do you have any information on what you were doing at the time? Were you in combat? Also, did you use the bag button to open the bag, i.e. clicking on the blizzard bag button?

Also, do you have the "Hide bag button" option checked that hides the Blizzard bag button?

**Comment by Cidan** [comment]
I just pushed a new file that possibly fixes this. Let me know if you can reproduce this!

**Comment by Faulkal** [comment]
I was able to combine the items and no longer got an error message.
