### ISSUE TITLE
Missing caged battle pets

### ISSUE THREAD

**Issue by S4mmis** [Cidan/BetterBags#286]
### Addon Version

v0.1.14-4-gd66e384

### World of Warcraft Version

Retail

### Describe the bug

When opening bags cant see caged battle pets

### Steps to reproduce

Just open ur bags

**Comment by zeptognome** [comment]
> When opening bags cant see caged battle pets

Did #316 fix this for you?

I'd guess this can be closed

**Comment by S4mmis** [comment]
Its work right now

**Comment by AMaribo** [comment]
Fixed in #316
