### ISSUE TITLE
Can't Open Bag with Keybind

### ISSUE THREAD

**Issue by GrumpyWolf92** [Cidan/BetterBags#288]
### Addon Version

v.0.1.14-4-gd66e384

### World of Warcraft Version

Retail

### Describe the bug

Apologies if this is known -- I searched but couldn't find anyone else with the same issue! I can't seem to open the bag with my bag keybind. Backpack is bound to both B and F12 (by default) and neither will open the bag screen. I've isolated it to BetterBags by disabling all other addons and attempting to open the bags with my keybind, in which case it still won't work. I've also disabled BetterBags to confirm that my bags will still open with a keybind then -- in which case it does work properly. I also tried to rebind it to a different key with the same result, and tried restarting my game client. The bag can still be opened by clicking the bag icon, at least. I have buggrabber and bugsack installed and haven't received any lua errors yet.

### Steps to reproduce

1. Open WoW (retail) with BetterBags enabled.
2. Attempt to open bags using the bag keybind.

**Comment by Cidan** [comment]
You can only open the bag now with `Open All Bags` as the keybind. If it's unbound at the moment, you'll get a warning in game, but it's also likely bound to `shift+B`, which does not trigger the warning.

Rebind it to B -- I'll also add a warning if `shift+B` is detected.

**Comment by GrumpyWolf92** [comment]
Ahh I see! Thank you so much :D It was indeed bound to shift+B.
