### ISSUE TITLE
Can't read stack count if over a certain amount

### ISSUE THREAD

**Issue by Caynn** [Cidan/BetterBags#289]
### Addon Version

v0.1.14-5-ga89d623

### World of Warcraft Version

Retail

### Describe the bug

When item counts are over a certain number (9999 based on the quick test I did) the stack count becomes *

![image](https://github.com/Cidan/BetterBags/assets/74381576/84231d1d-2fbe-456f-a0c2-0f54c59066ba)

### Steps to reproduce

This is repeatable on any stackable item of over 5 digits.

**Comment by Cidan** [comment]
This is working as intended. The Blizzard API will do this with counts over 9999.
