### ISSUE TITLE
All items are unstacked when interacting with AH

### ISSUE THREAD

**Issue by Caynn** [Cidan/BetterBags#290]
### Addon Version

v0.1.14-5-ga89d623

### World of Warcraft Version

Retail

### Describe the bug

When you are at the AH items become unstacked.

Not interacting with AH vendor 
![image](https://github.com/Cidan/BetterBags/assets/74381576/f9afacf1-8f64-4490-bc7f-207abbb2691a)

When interacting
![image](https://github.com/Cidan/BetterBags/assets/74381576/7f0e6e57-2569-499d-b260-10d2e91df9ed)

### Steps to reproduce

Seemed to happen each time I went there.

**Comment by Cidan** [comment]
This is working as intended. You can turn this feature off in the settings menu.
