### ISSUE TITLE
BB pops a msg saying "Start Typing to Search Your Bags" but places the cursor in the msg, not in the bag field

### ISSUE THREAD

**Issue by prathmell** [Cidan/BetterBags#292]
### Addon Version

0.1.14-5-ga89d623

### World of Warcraft Version

Retail

### Describe the bug

I use the "b" key to open my bags.  BB pops an informative message above the bag and puts the curson in the **message**, not in the search field in the bag screen. 

With the message on the screen, if I close the bag by pressing the **x** in the upper right corner, the search message stays open on the screen until I hit escape which then brings up the WoW Esc menu.  

This behavior is confusing and inconsistent.  Pressing a keybind should open the bag and a second press shouuld close it, not start a search.
This image shows the cursor in the message. 
![bbbug](https://github.com/Cidan/BetterBags/assets/33069428/7a4a02c6-6b7b-49f1-8759-638396a43ee9)
This image shows typing in the message _after_ the bag has been closed (nothing was typed in the message box while the bag was opened, but the same result happens if you do type into the message box then close the bag)

### Steps to reproduce

1, use the keybind (set in BetterBags under options>Better Bags in the WoW options screen) to open your bag
2. see the message pop up 
3. use the x in the upper right of the bagto close BB
4. see the message remain on the screen
5. hit Esc to close the message
6. hit Esc again to close the WoW game menu
7. follow steps 1 & 2
8. start typing, (this searches as expected)
9. hit Esc
10. message box disappears but bag remains open
11. hit b - message reappears
 
I think you should take the cursor out of the message box, the message box should stay up for say 5-10 seconds, and re-striking the keybind should close the bag

**Comment by AMaribo** [comment]
The message box above the bags is actually a search box which can be key bound through the Search Bags keybind.
The in-bag search bar has been enabled by default with v0.1.71.
