### ISSUE TITLE
[Feature]: Ability to see, and change, your equipped bags

### ISSUE THREAD

**Issue by NewVenari** [Cidan/BetterBags#293]
### Describe the feature

I'd really love it if BetterBags allowed me to see which bags i had equipped, and allow me to change which bags I had equipped.

### Describe the implementation

Perhaps small icons across the bottom of the window, in the same line (or slightly below) the currencies.

**Comment by Cidan** [comment]
Click the bag icon at the top of the bag screen, and select Show Bags.
