### ISSUE TITLE
[Feature]: Ability to just have currencies always showing

### ISSUE THREAD

**Issue by thattome** [Cidan/BetterBags#301]
### Describe the feature

Would absolotuely love to just have currencies always showing without having to click.

### Describe the implementation

A tick box for always showing would be great

**Comment by Cidan** [comment]
I think the solution here is to just make currency show/hide persist, so that if you open it, and /reload, it stays that way.

**Comment by zeptognome** [comment]
Currency window does persist and up to 7 currencies can be tracked directly on the bag frame.
