### ISSUE TITLE
[Feature]: Remove "shift" from drag and drop when recategorizing in bags.

### ISSUE THREAD

**Issue by prathmell** [Cidan/BetterBags#303]
### Describe the feature

I understand the reasoning behind shift drop, but drag-and-drop is so common everywhere not just in WoW that I find it awkward to have to shift to drop the item, and I don't like having to use both hands (yeah I know I'm lazy) to recategorize.  It's also inconsistent with dragging an item to a category in the category list when custom categories is open with a category on the screen.

### Describe the implementation

When I open bags and see an item that is in the wrong category for me, I'd much prefer not to have to use the shift to drop it.  Yes It means mistakes are easier to make but they can be undone too.

**Comment by Cidan** [comment]
This will not be done. In my testing, I found it common that I would accidentally recategorize bags. Shift will remain, as it is more useful than not.
