### ISSUE TITLE
[Feature]: add an option to immediately remove "new" items to their initial category

### ISSUE THREAD

**Issue by prathmell** [Cidan/BetterBags#304]
### Describe the feature

I don't really understand when an item stops being "new" and gets put in a category.  Sometimes I can't move a "new" item to the category I want it in and I'm not sure what I need to do to make it "old" so to speak.  

### Describe the implementation

I'd like to see a button on the bag itself to move new items to their appropriate category.  I would be perfectly happy with close-then-open to move new items.  But I can see that might be annoying for some people

**Comment by Cidan** [comment]
Right click the bag icon at the top of the bag to make items not-new. You can adjust new-ness settings in the option screen, including how long an item will remain new.
