### ISSUE TITLE
Menu can be moved off screen

### ISSUE THREAD

**Issue by steven-fuller** [Cidan/BetterBags#31]
When experimenting with different category options, I was able to make the bag window wide enough that the menu was off the left of the screen. I had to adjust the UI scale option to be able to change any settings back. I normally run 2560x1440 with a UI scale of 75%
Setting the scale 'off', I was barely able to click the menu again.
I was able to left-click in the window and drag it up and down, but it was clamped from moving left and right.
![image](https://github.com/Cidan/BetterBags/assets/18124992/0d6e632d-3ed8-41d9-8cec-01e6ec89cad2)
(screenshot shows absolute left of unscaled screen)

Imo, the menu should either never be allowed to go off screen, or the user should be able to drag the window freely.
Bonus points for working cooperatively with the UI scaling feature and not letting the user put themselves in this situation :)

**Comment by Cidan** [comment]
Great catch -- this was actually in the back of my mind for a while now, but I have a really, really large monitor and haven't been able to test. I'll add some safe guards here.

Thanks!

**Comment by Cidan** [comment]
A fix for this has been released, please test and re-open this issue if you find anything else related to this!
