### ISSUE TITLE
Script ran to long 

### ISSUE THREAD

**Issue by SebastianJWolf** [Cidan/BetterBags#310]
### Addon Version

0.1.14

### World of Warcraft Version

Retail

### Describe the bug

Bag did not render properly and reloading ui fixed it. This occurred after porting from the Nine in Sanctum of Domination to my Garrison. 

1x BetterBags/frames/item.lua:190: script ran too long
[string "@BetterBags/frames/item.lua"]:190: in function `Unlock'
[string "@BetterBags/frames/item.lua"]:169: in function `SetLock'
[string "@BetterBags/frames/item.lua"]:261: in function `SetItem'
[string "@BetterBags/views/gridview.lua"]:87: in function `Render'
[string "@BetterBags/frames/bag.lua"]:218: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
self = <table> {
 NormalTexture = BetterBagsItemButton500NormalTexture {
 }
 Stock = BetterBagsItemButton500Stock {
 }
 kind = 0
 LockTexture = BetterBagsItemButton500LockButton {
 }
 IconOverlay = Texture {
 }
 isFreeSlot = false
 data = <table> {
 }
 __bb_elvui_skin = true
 ilvlText = FontString {
 }
 Count = BetterBagsItemButton500Count {
 }
 button = BetterBagsItemButton500 {
 }
 IconQuestTexture = BetterBagsItemButton500IconQuestTexture {
 }
 frame = BetterBagsItemButton500parent {
 }
 Cooldown = BetterBagsItemButton500Cooldown {
 }
 IconTexture = BetterBagsItemButton500IconTexture {
 }
}
itemLocation = <table> {
 Clear = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:29
 IsEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:56
 IsEqualToBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:72
 SetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:35
 IsBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:60
 SetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:46
 slotIndex = 24
 HasAnyLocation = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:64
 bagID = 5
 GetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:52
 IsEqualToEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:80
 GetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:42
 IsValid = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:68
 IsEqualTo = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:88
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 Clear = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:29
 IsEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:56
 IsEqualToBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:72
 SetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:35
 IsBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:60
 SetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:46
 slotIndex = 24
 HasAnyLocation = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:64
 bagID = 5
 GetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:52
 IsEqualToEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:80
 GetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:42
 IsValid = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:68
 IsEqualTo = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:88
}
(*temporary) = 24
(*temporary) = <table> {
 Clear = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:29
 IsEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:56
 IsEqualToBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:72
 SetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:35
 IsBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:60
 SetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:46
 slotIndex = 24
 HasAnyLocation = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:64
 bagID = 5
 GetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:52
 IsEqualToEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:80
 GetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:42
 IsValid = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:68
 IsEqualTo = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:88
}
(*temporary) = "script ran too long"
database = <table> {
 SetDefaultModuleLibraries = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.

![Better Bags bug](https://github.com/Cidan/BetterBags/assets/3488467/b25df7e7-1bce-4311-992c-ab04f33693e3)

### Steps to reproduce

As it happened immediately after hearthing to my Garrison unsure if there is a way to reproduce. May be related to closing and opening my bag as I was hearthing.

**Comment by SebastianJWolf** [comment]
Ran into the same issues hearthing back to my garrison from N'zoth this time 

1x BetterBags/frames/item.lua:266: script ran too long
[string "@BetterBags/frames/item.lua"]:266: in function `SetItem'
[string "@BetterBags/views/gridview.lua"]:87: in function `Render'
[string "@BetterBags/frames/bag.lua"]:218: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
self = <table> {
 NormalTexture = BetterBagsItemButton470NormalTexture {
 }
 Stock = BetterBagsItemButton470Stock {
 }
 kind = 0
 LockTexture = BetterBagsItemButton470LockButton {
 }
 IconOverlay = Texture {
 }
 isFreeSlot = false
 data = <table> {
 }
 __bb_elvui_skin = true
 ilvlText = FontString {
 }
 Count = BetterBagsItemButton470Count {
 }
 button = BetterBagsItemButton470 {
 }
 IconQuestTexture = BetterBagsItemButton470IconQuestTexture {
 }
 frame = BetterBagsItemButton470parent {
 }
 Cooldown = BetterBagsItemButton470Cooldown {
 }
 IconTexture = BetterBagsItemButton470IconTexture {
 }
}
data = <table> {
 isItemEmpty = false
 containerInfo = <table> {
 }
 slotid = 18
 basic = false
 questInfo = <table> {
 }
 kind = 0
 itemInfo = <table> {
 }
 bagid = 5
}
tooltipOwner = nil
bagid = 5
slotid = 18
questInfo = <table> {
 isQuestItem = false
 isActive = false
}
info = <table> {
 itemName = "Rousing Decay"
 hasLoot = false
 hyperlink = "|cff0070dd|Hitem:190330::::::::70:263:::::::::|h[Rousing Decay]|h|r"
 iconFileID = 4554446
 hasNoValue = false
 isLocked = false
 itemID = 190330
 isBound = false
 stackCount = 13
 isFiltered = false
 isReadable = false
 quality = 3
}
readable = false
isFiltered = false
noValue = false
isQuestItem = false
questID = nil
isActive = false
bound = false
(*temporary) = BetterBagsItemButton470 {
 BottomLeftCorner = Texture {
 }
 SetItem = <function> defined @FrameXML/ItemButtonTemplate.lua:544
 IconOverlay = Texture {
 }
 SetAlpha = <function> defined @FrameXML/ItemButtonTemplate.lua:631
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 ItemSlotBackground = Texture {
 }
 showMatchHighlight = true
 flashAnim = AnimationGroup {
 }
 RightEdge = Texture {
 }
 isExtended = false
 SetReadable = <function> defined @FrameXML/ContainerFrame.lua:1700
 UpdateNewItem = <function> defined @FrameXML/ContainerFrame.lua:1646
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 count = 13
 PostOnHide = <function> defined @FrameXML/ItemButtonTemplate.lua:423
 NewItemTexture = Texture {
 }
 PostOnEvent = <function> defined @FrameXML/ItemButtonTemplate.lua:427
 UpdateQuestItem = <function> defined @FrameXML/ContainerFrame.lua:1634
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 IsExtended = <function> defined @FrameXML/ContainerFrame.lua:1738
 UpdateItemContextOverlay = <function> defined @FrameXML/ItemButtonTemplate.lua:488
 CheckForTutorials = <function> defined @FrameXML/ContainerFrame.lua:1768
 TopEdge = Texture {
 }
 emptyBackgroundAtlas = "bags-item-slot64"
 Count = BetterBagsItemButton470Count {
 }
 SetItemButtonAnchorPoint = <function> defined @FrameXML/ItemButtonTemplate.lua:618
 SetBackdropColor = <function> defined @BetterBagsElvUISkin/util/misc.lua:3
 LeftEdge = Texture {
 }
 NormalTexture = BetterBagsItemButton470NormalTexture {
 }
 minDisplayCount = 1
 OnItemContextChanged = <function> defined @FrameXML/ItemButtonTemplate.lua:410
 UpdateJunkItem = <function> defined @FrameXML/ContainerFrame.lua:1678
 HasItem = <function> defined @FrameXML/ContainerFrame.lua:1696
 OnClick = <function> defined @FrameXML/ContainerFrame.lua:1467
 pushed = Texture {
 }
 SetItemButtonScale = <function> defined @FrameXML/ItemButtonTemplate.lua:623
 isCraftedItem = false
 isProfessionItem = false
 Cooldown = BetterBagsItemButton470Cooldown {
 }
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 GetSlotAndBagID = <function> defined @FrameXML/ContainerFrame.lua:1611
 GetItemID = <function> defined @FrameXML/ItemButtonTemplate.lua:591
 RegisterBagButtonUpdateItemContextMatching = <function> defined @FrameXML/ItemButtonTemplate.lua:657
 BagIndicator = Texture {
 }
 Stock = BetterBagsItemButton470Stock {
 }
 GetItemLink = <function> defined @FrameXML/ItemButtonTemplate.lua:606
 GetItemInfo = <function> defined

**Comment by SebastianJWolf** [comment]
Happened again hearthing to my Garrison

2x BetterBags/frames/grid.lua:140: script ran too long
[string "@BetterBags/frames/grid.lua"]:140: in function `Sort'
[string "@BetterBags/views/gridview.lua"]:187: in function `Render'
[string "@BetterBags/frames/bag.lua"]:218: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
(*temporary) = <table> {
 view = <table> {
 }
 columns = <table> {
 }
 cellToColumn = <table> {
 }
 spacing = 4
 cells = <table> {
 }
 maxCellWidth = 1
 box = BetterBagsScrollGrid1 {
 }
 headers = <table> {
 }
 __bb_elvui_skin = true
 idToCell = <table> {
 }
 compactStyle = 1
 inner = Frame {
 }
 frame = BetterBagsScrollGrid1 {
 }
 cellToID = <table> {
 }
 bar = Frame {
 }
}
(*temporary) = <function> defined @BetterBags/util/sort.lua:72
(*temporary) = <function> defined =[C]:-1
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
}
(*temporary) = <function> defined @BetterBags/util/sort.lua:72
(*temporary) = "script ran too long"

**Comment by Cidan** [comment]
This is fixed in the latest alpha, with a TBD release date due to some other outstanding bugs. You can install the current Alpha from curse.
