### ISSUE TITLE
[Feature]: Add an icon for Blizzard's bag cleanup tool

### ISSUE THREAD

**Issue by Myrroddin** [Cidan/BetterBags#312]
### Describe the feature

There is a great spot right next to BetterBags' icon to place Blizzard's bag cleanup tool. This should exist on the bags, bank, and reagent bank. Either place the tool next to BetterBags' icon or place the tool on the far right to prevent misclicks.

### Describe the implementation

Classic and Wrath do not have Blizzard's bag cleanup tool. However, there is the addon [SortBags](https://www.curseforge.com/wow/addons/sortbags) which provides the same feature. You could even adapt [AdiBags - Cleanup](https://www.curseforge.com/wow/addons/adibags-cleanup) which uses SortBags to mimic retail WoW.

**Comment by Cidan** [comment]
Right click the bag icon to sort -- this has been in for quite some time.  However, I like the idea of integrating with SortBags -- I'll do this.

**Comment by Cidan** [comment]
Latest alpha implements this feature in Classic. Bank isn't implemented yet across any SKU and will come soon.

**Comment by Myrroddin** [comment]
Oh, I thought the right-click was merely a visual thing that only affected the *display* in BetterBags. I didn't know that was actually sorting the bags, mostly because I couldn't find a way to disable the BetterBags skin without disabling the entire addon.

**Comment by Myrroddin** [comment]
I'm not sure if you covered this when you added SortBags support. I glanced at your commit and might have missed it. SortBags has two commands.

* `SortBags()` which is for the character's bags
* `SortBankBags()` which is for the character's bank bags

I saw SortBags() but if you added SortBankBags() I missed the feature.

**Comment by Cidan** [comment]
> Latest alpha implements this feature in Classic. Bank isn't implemented yet across any SKU and will come soon.

In my original message to you. :)

**Comment by Cidan** [comment]
>  I didn't know that was actually sorting the bags, mostly because I couldn't find a way to disable the BetterBags skin without disabling the entire addon.

Click the menu -> Show Bags. This will show you bags as they are in Blizzard's layout.

**Comment by SpareSimian** [comment]
I'm reminded today when looking at my Altoholics panel that sorting the raw bags would be useful so I can find things in alts' bags when looking in the Altoholics panel. (Altoholics has a search feature but sometimes it fails to find something I know I have. Or I can't remember the name of something I know I have and don't want to switch toons to look it up.)

**Comment by Myrroddin** [comment]
> > I didn't know that was actually sorting the bags, mostly because I couldn't find a way to disable the BetterBags skin without disabling the entire addon.
> 
> Click the menu -> Show Bags. This will show you bags as they are in Blizzard's layout.

This works, but only for the character's bags. When showing the Blizzard bags at the bank or reagent bank, there is no sorting mechanism, whether through BetterBags or access to the Blizzard sorting tool.

Showing the Blizzard layout is one thing, not having Blizzard's sorting tool is another.

**Comment by Cidan** [comment]
Yes, bank sorting is on my todo list -- it's going to come with the planned bank overhaul for TWW.

**Comment by Myrroddin** [comment]
> Yes, bank sorting is on my todo list -- it's going to come with the planned bank overhaul for TWW.

Nice! Hopefully, you can get the bank sorting feature for BagSort working in Classic too. Big things are coming, with BetterBags improving all the time.
