### ISSUE TITLE
Bags Won't Open in WotLK v0.1.15

### ISSUE THREAD

**Issue by cjtylr** [Cidan/BetterBags#315]
### Addon Version

 v0.1.15

### World of Warcraft Version

Wrath

### Describe the bug

Updated to [v0.1.15](https://www.curseforge.com/wow/addons/better-bags/files/5222669) in WotLK this morning and bags would no longer open. Tried disable/reenable/reload to no avail. Options pane still worked, but bag pane wouldn't show. Reverted to v0.1.14 and they resumed opening.

Hopefully not a combination of my addons? I use ElvUI, but the bags functionality is disable. I use four BB plugins: Hearthstones, Tabards, ElvUI Skin, and BoE/BoA.

### Steps to reproduce

- Install WotLK v0.1.15
- Log into game
- Try to open bags
- No inventory

**Comment by Cidan** [comment]
I had to remove all bindings except Open All Bags, which is probably `shift+B` for you by default. Rebind this to your bag key and it will work.

**Comment by cjtylr** [comment]
Thanks!
