### ISSUE TITLE
[Feature]: Allow full section titles

### ISSUE THREAD

**Issue by martheli** [Cidan/BetterBags#317]
### Describe the feature

I would like if there was a way to have the titles fully spelled out. Instead of all being abrevieted like this:

![image](https://github.com/Cidan/BetterBags/assets/20176169/edcf11f4-a2d2-4c29-bda4-c4ebbd80516b)

### Describe the implementation

When I go into the config menu I would like to have a checkbox to show full names or abbreviated them. Or maybe have a scale to show a certain amount of characters for titles.

**Comment by Cidan** [comment]
This will not be implemented -- we did this in a test version, and it's incredibly not user friendly and makes the bag look very bad.
