### ISSUE TITLE
Keys floating around after zoning

### ISSUE THREAD

**Issue by jelmerj** [Cidan/BetterBags#318]
### Addon Version

v0.1.17

### World of Warcraft Version

Wrath

### Describe the bug

After zoning I suddenly have keys floating around in my screen that only go away after reloading. The keys are not clickable.

![image](https://github.com/Cidan/BetterBags/assets/1116119/38986e80-7c36-4872-bcda-30a707a6d3c8)

### Steps to reproduce

1. Heartstone

**Comment by Cidan** [comment]
Fixed.
