### ISSUE TITLE
[Feature]: Moving custom category items to bank / inv with one click

### ISSUE THREAD

**Issue by PeTeFIN** [Cidan/BetterBags#319]
### Describe the feature

So, in adibags you could put certain custom item set items into bank with one click / or take them out. This was super convenient to retrieve specialty items from bank, like frost/fire resistance gear. 

### Describe the implementation

by clicking the custom category name it would move items to or from bank, depending if you clicked the name in bags or bank.

**Comment by claytonkimber** [comment]
Came here to request the same thing.  Would be an amazing addition

**Comment by SargonStarblade** [comment]
Definitely needs this function.

**Comment by AMaribo** [comment]
This has been released with v0.1.90.
