### ISSUE TITLE
Split stacks UI element appears behind bank window

### ISSUE THREAD

**Issue by steven-fuller** [Cidan/BetterBags#32]
When shift left-clicking a stack of items in the bag, bank, or reagent bank, the 'splitter' UI appears behind the ~~bag~~ bank window
(version 0.0.24)

![image](https://github.com/Cidan/BetterBags/assets/18124992/2df8d97c-1fcc-4d5c-9df5-d823ab770054)
![image](https://github.com/Cidan/BetterBags/assets/18124992/27d37aac-ff5d-4a63-a95b-d6609e3afcbb)

**Comment by Cidan** [comment]
Does it appear behind the player bag too, or just the bank?

**Comment by steven-fuller** [comment]
Oops - Infront of bag, behind the bank windows.
![image](https://github.com/Cidan/BetterBags/assets/18124992/7d175714-cca5-4658-b46b-7746d14133df)

**Comment by Cidan** [comment]
Okay, this makes sense. I layer the bank "above" the player frame, but i might instead layer the player frame "under" the bank frame. Let me do some testing.

**Comment by Cidan** [comment]
Fixed in the next release. Thanks!
