### ISSUE TITLE
Unable to Add to Custom Catergory

### ISSUE THREAD

**Issue by justaround31** [Cidan/BetterBags#320]
### Addon Version

v0.1.21

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

I have created a custom category. When dragging items from the bag to the new category nothing happens. The only option showing is "Hold Shift to add "Item Name" to to Items. When I do this it auto create a new custom category named "Items" and does not add it to the category I wanted.

![image](https://github.com/Cidan/BetterBags/assets/166156292/a362c27e-765a-4e51-8d46-c6138ed5b1c7)

All addons are disabled.

### Steps to reproduce

Unsure how to reproduce as I am just creating a custom category and trying to add items to it.

**Comment by Bodric** [comment]
I have the exact same issue. Creating a custom category, for example "Toys" and then trying to add an item in there it still ends up in (or creates if not present) a category called "Items".

**Comment by Cidan** [comment]
The previous code was very tricky about where exactly and how exactly you had to drop the item. I've just released .22, which makes this work much better.

You can also just drag an item to the bag button on the top left of the main bag frame to make a category for it.
