### ISSUE TITLE
Cannot open bags with /script OpenAllBags()

### ISSUE THREAD

**Issue by mahmoudimus** [Cidan/BetterBags#321]
### Addon Version

v0.1.24

### World of Warcraft Version

Retail

### Describe the bug

Unclear when it was working but I updated my betterbag recently and now I cannot open my bags w/ my macro of `/script OpenAllBags()` -- nothing happens. 

### Steps to reproduce

1. Load Better Bags
2. Create a macro with `/script OpenAllBags()` or just type it in the text box
3. Bags do not open :(

**Comment by Cidan** [comment]
Use /script ToggleAllBags()

**Comment by mahmoudimus** [comment]
Thank you!
