### ISSUE TITLE
'Merge Stacks' makes item counter disappear if item count is higher than 10k.

### ISSUE THREAD

**Issue by fgsguedes** [Cidan/BetterBags#324]
### Addon Version

0.1.26

### World of Warcraft Version

Retail

## Description
While having more than 10k of a single item, and with 'Merge Stacks' option enabled, it will make the item counter disappear.

9999 still shows the number just fine, but character count covers entire of item square's width.
Looting the 10k-th item, makes the number with 6 digits no longer fit in the square, and number is gone.

Bug observed in all bags. Regular, reagent, regular bank, reagent bank.

Partial feature request, it would be cool to have numbers shown in shorter format from there.
Not sure if it would make more sense to have the + or not in there, since it could not be exactly 10k in that scenario.
10k+, 10,1k+, 12k, etc.

### 9999 items + Addon version
No bug while item count still lower than 10k
![Screenshot 2024-04-12 184347](https://github.com/Cidan/BetterBags/assets/203216/a628d248-9a21-48c5-8163-b9184b9c757c)

### 10k items
Item count gone if merged stacks account for 10k items or more.
![Screenshot 2024-04-12 183824](https://github.com/Cidan/BetterBags/assets/203216/6cc0b886-b9ac-45b3-80a3-429193d65af5)

### Item counter tooltip
Just showing via tooltip that there is actually 10k items on my bag.
![Screenshot 2024-04-12 184033](https://github.com/Cidan/BetterBags/assets/203216/65073d62-b39a-41c4-9c08-1bb893e10b07)

### Steps to reproduce

1. Have 10k of a single item;
2. Open options screen;
3. Navigate to 'Backpack' on left menu;
4. Under 'Stacking' sub category, enable 'Merge Stacks' option;
5. Observe item counter gone in bag.

**Comment by Cidan** [comment]
This isn't a bug, this is how Blizzard handles the counter at the bottom of items. They explicitly put it in their code to replace the number with *. We will not modify Blizzard behavior here for the time being.
