### ISSUE TITLE
Number of different items will not stick to assigned category

### ISSUE THREAD

**Issue by justaround31** [Cidan/BetterBags#327]
### Addon Version

v0.1.27

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

There are a number of items that will not stick to the category once assigned. E.g I have moved the item "Gray Kodo" from the category Misc. to Hearthstones. Upon either a certain amount of time or relogging the "Gray Kodo" goes back to Misc.

This also happens with item "Winterfall Ritual Totem." Moved from Misc to Quest category and reverts back after X time or relog.

### Steps to reproduce

See description for items tested.
![BB Items ](https://github.com/Cidan/BetterBags/assets/166156292/5b890624-cdaa-4a12-afb8-4cc571360032)

**Comment by Cidan** [comment]
Are you using the BetterBags Hearthstone plugin?

**Comment by justaround31** [comment]
Yes. Using the following:
![Screenshot 2024-04-13 101058](https://github.com/Cidan/BetterBags/assets/166156292/1050d2d9-f0fd-4d8e-ae73-a7d6a1162687)

**Comment by Cidan** [comment]
Hearthstones and Teleports are mutually exclusive according to the author of Hearthstones, which is probably causing a conflict. Disable teleports, and let me know if it's still happening.

**Comment by justaround31** [comment]
That seemed to do the trick. Thank You.
LOVE the addon
