### ISSUE TITLE
Search highlighting dissappears when selling to a vendor.

### ISSUE THREAD

**Issue by eldir** [Cidan/BetterBags#331]
### Addon Version

0.1.127-2

### World of Warcraft Version

Retail

### Describe the bug

Search highlighting gets deactivated when selling something.

### Steps to reproduce

1. Speak to any vendor
2. Use search function to highlight (e.g. 'cloth')
3. Sell anything (highlighted or not highlighted items have the same effect)
4. Remaining highlighting disappears until the search term is changed (e,g. delete the 'h' to get it back)

**Comment by AMaribo** [comment]
Search was completely redone with v.0.1.81 and this bug was resolved with the update.
