### ISSUE TITLE
[Feature]: Replacing the item in your inventory

### ISSUE THREAD

**Issue by Mimsyuwu** [Cidan/BetterBags#336]
### Describe the feature

The addon is very intuitive but theres something that just destroys me that im sure is already a feature but I cannot figure out how to turn it on so if it exists it would be nice to make it more obvious.
I really appreciate the sorting but don't like that when I right click an item in the inventory it replaces the item that I am wearing and the item worn moves to its spot in the inventory alphabetically. If the item I right clicked wasnt an upgrade it can make it difficult to find the item I was wearing if I cannot remember what it was.

### Describe the implementation

I dunno like.. A checkbox for static item replacement or something that replaces the item you just right clicked with the item you were wearing. A way to keep things sorted by armor, weapons, misc, etc but maybe remove the alphabetical and quality sorting or toggle it on and off.

**Comment by Cidan** [comment]
This will come in the way of an improved new item handling -- swapped items will always be at the top of the bag.
