### ISSUE TITLE
[Feature]: Ability to show currencies on the bag panel

### ISSUE THREAD

**Issue by leosilvano** [Cidan/BetterBags#338]
### Describe the feature

Would love if it was possible to have an option to display the currencies on the bag panel like we had on AdiBags, at the bottom left

### Describe the implementation

Similar to the ones we had on AdiBags, a list in which we could select which currencies we want to be displayed

**Comment by Cidan** [comment]
This is already implemented. Click the bag icon in the bag frame, and select Show Currencies. Click a currency to pin it to the bag.
