### ISSUE TITLE
List/vertical currency

### ISSUE THREAD

**Issue by LiamGBR** [Cidan/BetterBags#34]
A list based/vertical currency option alternative to the Adibags horizontal currency, similar to the wow currency view. Not sure if currency names would be worth adding as they may make it look too crowded but just icon + amount is also fine.

Would prefer if they were sortable as well so all the crests are together etc. as in wow currency they sorted are by name

![U66gYu](https://github.com/Cidan/BetterBags/assets/26609549/dd60d223-45b5-4e12-b354-a406c0913d06)

![qVJqKk](https://github.com/Cidan/BetterBags/assets/26609549/bee41628-a969-4624-876d-1673dac702b6)

**Comment by Cidan** [comment]
The current implementation of currency is as far as we'll go with this.
