### ISSUE TITLE
[Feature]: Add unmerge option when trading with another player

### ISSUE THREAD

**Issue by apachehub** [Cidan/BetterBags#348]
### Describe the feature

When activating the "Merge Stacks" and "Unmerge at Shop" option it currently only unmerges the stacks when opening a shop or when sending a mail. I'd like to have the same feature when trading with another player. Currently I can't unstack items and trade a specific amount of flasks, potions etc. when trading with a player.

### Describe the implementation

Basically just another checkbox here: 
![327043280-1d96389d-2fb5-4aca-aac5-2cd868794d10](https://github.com/Cidan/BetterBags/assets/168639741/075a0c1d-2f60-49f0-97b2-517a2ea7f99b)

"Unmerge when trading". Or just add the unmerge when trading functionality to "Unmerge at Shop".

**Comment by Cidan** [comment]
That's odd -- I that should work for trading with humans too. I'll look into it.

**Comment by Cidan** [comment]
Hm, just tested, it works on my end. What version of WoW, and what version of betterbags?

**Comment by apachehub** [comment]
Hi, sorry, I made a mistake. It actually works perfectly for me. It was Adibags where it didn't work and for some reason I assumed it was the same for BetterBags 😅
