### ISSUE TITLE
Stack splitting broken

### ISSUE THREAD

**Issue by kalbert312** [Cidan/BetterBags#350]
### Addon Version

v0.1.30

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

When trying to split a stack and move it to the "free space" slot in the bag, sometimes it will not work and spit out an error in the game's error UI: "Could not split these items." If I try to drag the entire stack to the "free space" slot, it will say "That item does not go in that container". I have no special bags, just 4 Traveler's Backpacks. Happens for any item (herbs, potions, armor, etc) when it's in this bug state. A `/reload` and game restart both did not resolve the issue.

### Steps to reproduce

Try splitting stacks of varying numbers until it happens. I'm not sure what is the exact cause.

**Comment by Cidan** [comment]
This is for things with native stacks, right? Not "unstackable" items like weapons, etc.

**Comment by kalbert312** [comment]
> This is for things with native stacks, right? Not "unstackable" items like weapons, etc.

Correct, first happened to me with a Greater Arcane Elixir stack. Once it's bugged, it happens to any type of item. I tried splitting potions and herb stacks and same result.

**Comment by Cidan** [comment]
Interesting -- okay, do you have any leads on how to reproduce this reliably? I don't play Classic but I can try to debug and fix this.

**Comment by kalbert312** [comment]
Here's a reliable repro. I moved all items to the first available slots per the show bags view. After I split the first potion, it works, but then the second split doesn't.

https://github.com/Cidan/BetterBags/assets/5498623/6e924581-e455-4d01-9ba1-604fed9cb675

**Comment by Cidan** [comment]
That's interesting! Let me see if I can reproduce this locally -- BetterBags doesn't actually touch any of the split mechanics or click interactions. Blizzard doesn't allow for modification to clicks on item buttons.

**Comment by Cidan** [comment]
And just like that, I was able to reproduce it. Looking at it now, will get a fix out soon.

**Comment by Cidan** [comment]
Okay, fixed in .31, which is going out now. Re-open this bug if you see anything else, and thank you!

**Comment by kalbert312** [comment]
Still seems to be an issue after the update. I reverted to 0.1.27 and can't repro.

**Comment by kalbert312** [comment]
Earliest repro version looks like 0.1.28. I swapped to that and reproed immediately. 0.1.27 no issue.

**Comment by Cidan** [comment]
Alright, I'll continue to investigate.

**Comment by Cidan** [comment]
Okay, I was able to narrow it down -- working on a fix now.

**Comment by Cidan** [comment]
Alright, pushed another fix in .32. The bug was in keyrings being marked as bag free slots by accident, causing all kinds of issues. Let me know if you hit anything else.
