### ISSUE TITLE
[Feature]: Add section for equipable gear

### ISSUE THREAD

**Issue by martheli** [Cidan/BetterBags#356]
### Describe the feature

I would like to be able to define a section that puts all equipable gear into that section. Instead of having 1 section for trinkets, 1 for two handed weapons, 1 for gloves, etc.....there should be 1 section to put all gear into.

### Describe the implementation

There should be an option in general tab to combine equitable gear into 1 section....or be able to define a custom category for armor, equipment, etc..

**Comment by AMaribo** [comment]
This can now be done with the new search-based category feature added in v0.1.90.
