### ISSUE TITLE
Drag and Drop Sorting [Feature]: 

### ISSUE THREAD

**Issue by SargonStarblade** [Cidan/BetterBags#362]
### Describe the feature

AdiBags had a feature that allowed you to drag an item to a sort category drop it and have it added to that category. I make tons of categories by expansion and a note, example 01. WoW - Reputation, so this would really help me with sorting.

### Describe the implementation

Same implementation as AdiBags.

**Comment by Cidan** [comment]
This is already implemented. Drag an item to your inventory to the header of a section in the bag. Hold shift and let go/click to put the item in that category permanently.
