### ISSUE TITLE
Bags will refresh after combat ends. spam

### ISSUE THREAD

**Issue by mrbuds** [Cidan/BetterBags#363]
### Addon Version

v0.1.43

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

Sometime i get this spam in the chat

![image](https://github.com/Cidan/BetterBags/assets/189656/34f03cc9-1563-44ca-abcf-87e0e965548b)

I'd like to not get it

### Steps to reproduce

Not sure, last time it occurred i was on a hunter and entered zul farak, but i have seen happening in more occasions

**Comment by zeptognome** [comment]
This print statement was removed quite a while ago
