### ISSUE TITLE
Frame drop by opening bags

### ISSUE THREAD

**Issue by RathianD** [Cidan/BetterBags#364]
### Addon Version

v0.1.43

### World of Warcraft Version

Retail

### Describe the bug

I downloaded the addon today and i noticed a 20fps frame drop every time i opened my bags but the weird thing is it does not happen when ever i open any option window like game menu or options the frame drop is basically gone maybe worth looking into it why this happens.

### Steps to reproduce

I recorded it so you can see what i am talking about i hope it helps.

https://github.com/Cidan/BetterBags/assets/139451298/763cf750-8713-47ee-a785-35e4294092c9

**Comment by Cidan** [comment]
I just spent some time debugging this -- this is tricky, because what I believe is happening is the Blizzard bag is secretly drawing in the background when you show the bag. This causes a small frame drop, and I can't turn off the Blizzard bag draw function.

Does this happen with just the default Blizzard bags?

**Comment by RathianD** [comment]
First of all thank you for responding! I just tested it with the default Blizzard bags and i have the same frame drops about 20 fps and with the default bags i can`t even open it whenever i have the game menu open so maybe that is the reason why the frame drop is gone because the default blizzard bags cant be used when the game menu / option is open.  
The thing is before Betterbags i was using Adibags and there was little to none frame drops maybe 2-4 i dont know if they found a way to reduce it but thats why i asked if this is normal.

**Comment by RathianD** [comment]
I just thought about it is there a way to trick the default bags into thinking the game menu is somehow open ^^

**Comment by Cidan** [comment]
That's so funny, I was just debugging this with another bag addon author and we JUST figured that out as well. There is currently no way to make the Blizzard bags not render in the background -- we put in a request with Blizzard to add a feature for us to do this though. Probably won't happen, but, you never know!

Thanks for the report.

**Comment by RathianD** [comment]
Well that saddles it fingers crossed! Thank you very much for taking the time and looking into it :)

**Comment by Cidan** [comment]
@RathianD With the help of some other folks, we've come up with a solution that I have in testing now. If you download the latest Alpha build of BetterBags (curse, wago, etc), you should get no frame drops at all when opening the bag.

Let me know how it goes!

**Comment by RathianD** [comment]
Well what ever you guys come up with it works Like a Charm!! The Frame Drops are completely gone 🥳 thank you so much ❤️
