### ISSUE TITLE
[Feature]: Custom Categories, Subcategories.

### ISSUE THREAD

**Issue by SargonStarblade** [Cidan/BetterBags#367]
### Describe the feature

I like creating my own categories. I would love to be able to create custom subcategories. Examples: Category: Gear, Subcategory: Plate or Category: 05. MoP, Subcategory: Herbalism. Sub-Subcategories would be nice too, but that may be asking to much.

### Describe the implementation

If implemented could you make a way to drag and drop one category into another to make it a subcategory of what it is dropped into? Also, being able to rename categories would be great.

**Comment by Cidan** [comment]
This is called bisection, and is a planned feature of #189.

**Comment by SargonStarblade** [comment]
cool
