### ISSUE TITLE
Bank window 

### ISSUE THREAD

**Issue by Faulkal** [Cidan/BetterBags#37]
1. Initial opening of bank shows a grey window. 
2. clicking on bag button to go to regent tab refreshes items to see in the original bank tab
3. right clicking again on the bag sometimes combines regent and bank slots.
![3](https://github.com/Cidan/BetterBags/assets/32784397/ba8c4a0e-354e-40c0-ad40-f56f46301ba7)
![1](https://github.com/Cidan/BetterBags/assets/32784397/5e74bbb2-13a9-48e7-bd3e-003ef6d24bb1)
![2](https://github.com/Cidan/BetterBags/assets/32784397/e8f81ce0-b495-480c-8fa9-e61c8f85eca0)

**Comment by Cidan** [comment]
This has been fixed and pushed to .36, which should be live now. Thanks for the report!
