### ISSUE TITLE
Mailbox window disappearing when BetterBags is enabled

### ISSUE THREAD

**Issue by rockernaap** [Cidan/BetterBags#370]
### Addon Version

v0.1.43

### World of Warcraft Version

Retail

### Describe the bug

When having BetterBags enabled and then opening the mailbox it will no longer show the mailbox window if you somehow try to move the mailbox window. I am running ElvUI and MoveAnything addons. However, this issue only occurs when you have BetterBags enabled. 

### Steps to reproduce

1. Have BetterBags Enabled
2. Open Mailbox
3. Try to drag the mailbox window
4. Mailbox window now disappears and will no longer show until you reload

**Comment by Cidan** [comment]
BetterBags does not touch, interact with, or even call any API related to anything with the Mailbox. I can't reproduce this. I'm assuming if you disable ElvUI, this goes away for you too.
