### ISSUE TITLE
[Feature]: Collapsable expansion categories 

### ISSUE THREAD

**Issue by luismigil** [Cidan/BetterBags#371]
### Describe the feature

Hi all! I think that its a good idea to add collapsable sections by expansion

### Describe the implementation

 BetterBags will show a header section with the name of the expansion and inside tha categories for each expansion, let me know if you think that its a good idea :)

**Comment by zeptognome** [comment]
agree that this could be a great feature, but duplicate of #73 I think

**Comment by Cidan** [comment]
Duplicate of #73
