### ISSUE TITLE
In list view, scrolling with mouse wheel doesn't work when mouse cursor is over an item in the list

### ISSUE THREAD

**Issue by mixels** [Cidan/BetterBags#372]
### Addon Version

0.1.44

### World of Warcraft Version

Cataclysm

### Describe the bug

In Classic Progression, Cataclysm version. When viewing the backpack in list view with BetterBags, the list will not scroll when spinning the middle mouse wheel if the cursor is over an item.

The list does scroll if the cursor is over the left margin, a category name, or the scroll bar as expected. It would be nice if this control worked when the cursor is over an item as the majority of the panel is covered by items in the list.

### Steps to reproduce

1. Open the bag.
2. Left click the backpack icon in top left and choose View -> List.
3. While in list view, put your mouse cursor over an item and scroll your middle mouse wheel.
4. Note that the results view does not scroll up or down.

Now you can move your mouse wheel over the left margin or a category name and scroll the mouse wheel to see that it does scroll as expected in this case. Ideally the list should scroll no matter where the mouse cursor is in the window when the mouse wheel is scrolled.

**Comment by zeptognome** [comment]
List view has been removed, at least for now, so this issue no longer applies
