### ISSUE TITLE
[Feature]: Expand all free spaces in non-Show Bags view

### ISSUE THREAD

**Issue by MummaBearHelp** [Cidan/BetterBags#373]
### Addon Version

10.2.7 (most recent)

### World of Warcraft Version

Retail

### Describe the bug

2 issues which seem to be related. In my bank I cannot have spaces where I want them, for eg spaces between items, all spaces are stacked and grouped at the bottom of my bank meaning the items cannot have a space for separation. The only way to allow spaces is to have my bags separately showing as opposed to one big display of slots.

Additionally, when opening bags, whether in the bank or not,  the bag divisions cannot be removed, unless I have the spaces all gathered together at the bottom so I am forced to have bag 1, bag 2 etc with gaps between bags. I checked the options where it says "view one bag" assuming it would combine all my slots into one big bag like before but selecting one bag, forces all the empty bag slots into one stacked section at the bottom.

Thank you for all the years of bagnon also :)

### Steps to reproduce

As above, open the bag and select the option

**Comment by Cidan** [comment]
Wrong addon, this isn't Bagnon :)

**Comment by MummaBearHelp** [comment]
> Wrong addon, this isn't Bagnon :)

Oh sorry, I know that, I was thanking you for bagnon, thinking that you were the same people because Betterbags replaced it, I thought. I am using Betterbags, this is the issue I'm having.

Sorry if I've misunderstood.

**Comment by Cidan** [comment]
BetterBags replaced AdiBags, not Bagnon -- however, I'm not quite understanding your issue. Can you screenshot exactly what you mean?

**Comment by MummaBearHelp** [comment]
Hi, sorry for the delay, I've attached screenies, I hope it works..

To try to explain it better, I like my bags to just be one mass space (ie not separated by each bag) but if I click for that, it takes all the empty spaces and condenses them into one at the bottom. Please see first file, bag spaces, I've circled what I mean. I used to have all the bags in one huge bag and I could have spaces wherever in the bank I wanted them, so for eg, I might leave a space to separate fish and meat if you see what I mean.
![bag spaces](https://github.com/Cidan/BetterBags/assets/86306590/253cac69-1426-4b0b-91ad-298e16bfd47e)

The 2nd pic shows the bag separation, I can't get the bags away without having the spaces compacted as you see in the 1st pic (circled).
![backpack separated](https://github.com/Cidan/BetterBags/assets/86306590/c4e6eb81-37c5-4bc6-b634-3e9ce3206f45)

The 3rd pic shows my bank (and I didn't mention this before) but theres no reagent bank, I have to click it separately to see it, I cant see reagent bank and regualr bank at the same time.
![bank reagentbag](https://github.com/Cidan/BetterBags/assets/86306590/004ab90b-9044-45c9-a8bf-3e8dab797969)

I'm sorry to be so much trouble lol, thank you for helping with this.

**Comment by AMaribo** [comment]
Renamed issue to be more relevant.

**Comment by AMaribo** [comment]
Free spaces can now be expanded and shown as of v.0.1.88.
