### ISSUE TITLE
Deposite Reagents still broken for Evoker

### ISSUE THREAD

**Issue by karaktaka** [Cidan/BetterBags#378]
### Addon Version

v0.1.45

### World of Warcraft Version

Retail

### Describe the bug

As stated in this bug report https://github.com/Cidan/BetterBags/issues/217 I can still not deposite reagents to the bank on my evoker.

### Steps to reproduce

* Open Bank
* Click on deposite reagents
* Nothing happens, but the bag sorting sound is playing

**Comment by zeptognome** [comment]
@karaktaka Can you report if this is still an issue?
Reagent bank UI was recently updated to support Warband bank, so fresh information, and/or screenshots would help

**Comment by karaktaka** [comment]
It is actually not. The issue was that my reagent bag was set to be ignored by cleanup. But BetterBags does not seem to show this kind of setting. So it looks like some other Addon might have set (or even I did set it and forgot about it) this.

I just found the setting in the normal Blizzard UI (as I thought it could also be a Blizzard Bug) and I didn't even know this setting existed.

**Comment by zeptognome** [comment]
Great news. Thanks for reporting back and glad you got it solved.
I had also forgotten this setting exists, but I'll see if it can be included with a feature request for a similar setting on the Warbank
