### ISSUE TITLE
[Feature]: Include Scrap/Unravel in "Unmerge at Shop" (or new option) [MOP Remix]

### ISSUE THREAD

**Issue by thetakerfan** [Cidan/BetterBags#379]
### Describe the feature

Currently can only unravel one piece of equipment or gem at a time when stacked in the BetterBags UI in MOP Remix (and likely future expansions that use the feature).

### Describe the implementation

Include Unravel UI in "Unmerge at Shop" or add additional option

**Comment by Cidan** [comment]
This is a good one -- I'll see if I can get this out today.

**Comment by Cidan** [comment]
Released in Alpha.

**Comment by thetakerfan** [comment]
So far so good
