### ISSUE TITLE
RegisterCategoryFunction

### ISSUE THREAD

**Issue by Phophia** [Cidan/BetterBags#384]
### Addon Version

10.2.7

### World of Warcraft Version

Retail

### Describe the bug

27x BetterBags/data/categories.lua:274: category function already registered: reg
[string "=[C]"]: in function `assert'
[string "@BetterBags/data/categories.lua"]:274: in function `RegisterCategoryFunction'
[string "@BetterBags-Openable/main.lua"]:186: in main chunk

Locals:
(*temporary) = false
(*temporary) = "category function already registered: reg"

### Steps to reproduce

I logged into the game and bugsack informed me of the error.

**Comment by DJSchaffner** [comment]
Do you have any plugins for BetterBags installed? If yes, which ones?

**Comment by Phophia** [comment]
All of them

**Comment by Cidan** [comment]
You have plugins that are doing duplicate functions. Plugins are not written by the BetterBags team directly. The error message indicates "BetterBags Openable" might be the cause, but only because it's trying to do the same thing as another plugin.
