### ISSUE TITLE
Category not working

### ISSUE THREAD

**Issue by PirateKain** [Cidan/BetterBags#387]
### Addon Version

v0.1.48

### World of Warcraft Version

Retail

### Describe the bug

Retail / Remix

I made gem categories for each type of gem, all work except one.

Gem Cogwheel - Works
Gem Meta - Works
Gem Prismatic 1 Chipped - Works
Gem Prismatic 2 Flawed - Works
Gem Prismatic 3 Epic Purple - Works
Gem Prismatic 4 Perfect - DOES NOT WORK
Gem Tinker - Works

Now in the Custom Categories they show up as if they worked but in my bags they do not. They just stay in the default gem Other slot.
![Screenshot 2024-05-28 002205](https://github.com/Cidan/BetterBags/assets/68149179/9b36ba9a-9b14-4bc3-957f-633aba09bda1)

### Steps to reproduce

I deleted the category that didn't work two times and remade it each time but all three I made didn't work.

**Comment by zeptognome** [comment]
What you show above would happen if you had deselected your custom category from the backpack list of categories. Make sure Gems 4 is checked in this list:
![image](https://github.com/Cidan/BetterBags/assets/158738380/7b65a639-192f-4f4b-9755-d9daca0279ee)

**Comment by PirateKain** [comment]
I have not deselected any category from backpack or Bank, so still not sure why it did this.

But my son also has the addon and does almost everything I do with custom categories. He added a few I had that he didn't and it all worked fine for him. So I deleted the addon and just copied his to see if that would work and it did.

So it is working fine for me now.
