### ISSUE TITLE
[Feature]: Include gem socketing window in "Unmerge at Shop" (or new option) [MOP Remix][Feature]: 

### ISSUE THREAD

**Issue by thetakerfan** [Cidan/BetterBags#394]
### Describe the feature

Similar to https://github.com/Cidan/BetterBags/issues/379

Currently can only socket one gem at a time when stacked in the BetterBags UI in MOP Remix

### Describe the implementation

Include socketing window in "Unmerge at Shop" or add additional option

**Comment by Cidan** [comment]
Gems are not virtual BetterBags stacks, they are Blizzard stacks -- I don't control the stacking of gems. I also don't see a way to split stacks programmatically to fix this behavior. Your best bet is to ask Blizzard to fix this.

**Comment by Cidan** [comment]
Small addition: You can unsplit programmatically, but you would need as many free slots as you have total gems for this to work, which doesn't seem practical at all.

**Comment by thetakerfan** [comment]
Nah, agreed not worth the hassle. My bad on not verifying it wasn't a virtual stack just seemed to behave similarly and assumed so.
