### ISSUE TITLE
Blank Bag (not BetterSort plugin)

### ISSUE THREAD

**Issue by perks** [Cidan/BetterBags#399]
### Addon Version

v 0.1.56

### World of Warcraft Version

Retail

### Describe the bug

When opening the bag, the window size is reduced and nothing is displayed (grid boxes or items)

![image](https://github.com/Cidan/BetterBags/assets/1820298/485ab0de-c21f-45a6-ab18-8fa1e804343b)

Stack trace of error is here:

https://pastebin.com/FGj749Pk

### Steps to reproduce

Load into retail WoW with latest version of BetterBags

Open BetterBags

**Comment by paceyuk** [comment]
Same problem here on Cataclysm Classic

**Comment by zeptognome** [comment]
" GetSectionSortFunction = <function> defined @BetterBags_GearFirst/main.lua:54"

you are using BetterBags - Gear First which includes a broken version of BetterSort.

Uninstall Gear first until its fixed.

**Comment by JourneyOver** [comment]
it looks like gearfirst released an update about ~30 minutes ago, but tbh I don't think the gearfirst plugin is really needed now since you can pin categories so you could just pin all the categories that gearfirst does, I could still see the normal bettersort plugin being useful though for now.
