### ISSUE TITLE
[Possible Bug] Can't buy reagent bank

### ISSUE THREAD

**Issue by gobacktogo** [Cidan/BetterBags#402]
### Addon Version

v0.1.57

### World of Warcraft Version

Retail

### Describe the bug

hey, 
thanks for your work. 
i was just on a char that unbeknownst to me did not own a reagent bank. better bags displayed free space (98) for my reagent bank. i have merge stacks enabled. after disabling better bags i saw that i did not have a reagent bank with that char and when opening it i got offered the option to buy it. 

### Steps to reproduce

1. have char without reagent bank
2. open reagent bank. 
3. BetterBags then seems to show an empty reagent bank and does not offer the option to buy it. 
4. disabling BetterBags, then buying the reagent bank and enabling BetterBags works fine.

**Comment by Cidan** [comment]
This is on my list to improve with some TWW changes I'm making (that will also work in retail) in the next few weeks.

Thanks for the report!

**Comment by AMaribo** [comment]
The reagent bank can now be purchased by clicking on the reagent bank tab on a character that does not own the tab yet.
