### ISSUE TITLE
stopped working with newest release

### ISSUE THREAD

**Issue by loksinss** [Cidan/BetterBags#404]
### Addon Version

v0.1.58

### World of Warcraft Version

Cataclysm

### Describe the bug

after updating to the newest version, i get lua errors upon logging in or /reload and the addon doesn't function at all.

> Message: Interface/AddOns/BetterBags/frames/sectionconfig.lua:40: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionItemList'.
Time: Thu Jun  6 05:27:21 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/sectionconfig.lua:40: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionItemList'.
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:208: in function `GetModule'
[string "@Interface/AddOns/BetterBags/frames/sectionconfig.lua"]:40: in main chunk
Locals: (*temporary) = "Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionItemList'."

>Message: Interface/AddOns/BetterBags/frames/bag.lua:71: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'.
Time: Thu Jun  6 05:27:21 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/bag.lua:71: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'.
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:208: in function `GetModule'
[string "@Interface/AddOns/BetterBags/frames/bag.lua"]:71: in main chunk
Locals: (*temporary) = "Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'."

>Message: Interface/AddOns/BetterBags/frames/classic/bag.lua:62: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'.
Time: Thu Jun  6 05:27:21 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/classic/bag.lua:62: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'.
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:208: in function `GetModule'
[string "@Interface/AddOns/BetterBags/frames/classic/bag.lua"]:62: in main chunk
Locals: (*temporary) = "Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'."

>Message: Interface/AddOns/BetterBags/core/init.lua:67: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'.
Time: Thu Jun  6 05:27:21 2024
Count: 1
Stack: Interface/AddOns/BetterBags/core/init.lua:67: Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'.
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:208: in function `GetModule'
[string "@Interface/AddOns/BetterBags/core/init.lua"]:67: in main chunk
Locals: (*temporary) = "Usage: GetModule(name, silent): 'name' - Cannot find module 'SectionConfig'."

### Steps to reproduce

only started happening after updating to the newest version

**Comment by Cidan** [comment]
Will push a fix for this in a few.

**Comment by Cidan** [comment]
Fixed in .59, going out now.
