### ISSUE TITLE
release.json file missing since v0.1.56

### ISSUE THREAD

**Issue by torkus** [Cidan/BetterBags#405]
### Addon Version

v0.1.56

### World of Warcraft Version

Retail

### Describe the bug

Since release v0.1.56 the `release.json` file as part of each release has disappeared.

### Steps to reproduce

![Screenshot at 2024-06-07 18-18-15](https://github.com/Cidan/BetterBags/assets/48790775/fdc12332-bf98-4030-8310-995319f37285)

**Comment by zeptognome** [comment]
uses: BigWigsMods/packager@v2.2.0

^ needs to be v2 or v2.3.1 for TWW support

**Comment by zeptognome** [comment]
This was implemented

**Comment by torkus** [comment]
cheers, @zeptognome , it's appreciated.
