### ISSUE TITLE
[Feature]: Meta-Categories

### ISSUE THREAD

**Issue by Autipho** [Cidan/BetterBags#407]
### Describe the feature

Thanks for a beautiful addon.

The only thing I'm truly missing is the ability to sort the categories into meta-categories that'd retain sorting functionality within themselves. That way I could put my Gear categories together, and keep them together. 

It kind of works a bit like that with the subtypes and sorting alphabetically, but since the names are so long, they're often cut short.

As an added bonus, if one could optionally put some kind of visual divider between the meta-categories, that'd just be swell! Like a line or a bar between my "Gear" meta-category and my "Season 4" meta-category.

### Describe the implementation

Being able to drag and drop categories into meta-categories. Optionally, being able to turn off and on the feature, and off and on any visual dividers.

**Comment by Cidan** [comment]
Meta categories will eventually present itself as break out windows and/or tabs. You can now manually sort sections however, and keep your gear together, in the new Configure Categories menu.
