### ISSUE TITLE
Impossible to temporarily split stacks

### ISSUE THREAD

**Issue by ouija-gg** [Cidan/BetterBags#409]
### Addon Version

v0.1.61

### World of Warcraft Version

Retail

### Describe the bug

I don't see a way to split items into smaller quantities, for example, when you want to trade your buddy a couple potions instead of an entire stack.

### Steps to reproduce

1. Open bag and shift-click an item to split.
2. Select quantity, e.g. 1
3. Place quantity(1) item onto free space.
4. Item is recompacted into a stack

**Comment by AMaribo** [comment]
There are a few settings you can use to allow you to see partial stacks to trade to someone.
If you turn on Don't Merge Partial, the partial stack you just created will never merge.
If you turn on Unmerge at Shop, the partial stacks will be unmerged when you're at any vendor window, including the trade window.
![image](https://github.com/Cidan/BetterBags/assets/7267373/76f5f5a2-8c4a-4432-9bb3-44b5bebb227f)
