### ISSUE TITLE
[Feature]: Gear set merged category

### ISSUE THREAD

**Issue by supmiller** [Cidan/BetterBags#410]
### Describe the feature

Currently each item in a gear set goes into a category title the name of the gear set. The issue is that if you have multiple gear sets that use the same item you often see missing items in each category and it gets confusing which item is where. 

I personally just got rid of the gear set categories and will hover over each item and view the tooltip to see if its part of a gear set. Its easier just to use the single weapon/ armor categories then sort into individual gear set categories.

### Describe the implementation

Cidan suggested an easier way would be to make a single category that all of the gear set items go into. It would be easy to implement, and alleviate the confusion with multiple gear set categories and similar items in multiple ones. If you were curious about an item if it is in a gear set you would just have to go to this single category versus looking for multiple gear set categories.

As discussed with Cidan on discord.

**Comment by AMaribo** [comment]
This can now be done with search-based categories added with v0.1.90.
