### ISSUE TITLE
text overlap in the search

### ISSUE THREAD

**Issue by Akiraownz** [Cidan/BetterBags#415]
### Addon Version

v01.61-2-g4315336

### World of Warcraft Version

Retail

### Describe the bug

when displaying the search bar on top of the bags there is 2 texts overlapping "Search Backpack" and "Backpack"
![image](https://github.com/Cidan/BetterBags/assets/112855057/33cf7f40-5e43-4886-a265-92745ca146f1)

### Steps to reproduce

make it so aways shows the search bar

**Comment by Cidan** [comment]
I noticed this too -- I'll be making changes to the bar before the final release.

**Comment by zeptognome** [comment]
This was fixed
