### ISSUE TITLE
[Feature]: Armor Categories Filtering

### ISSUE THREAD

**Issue by husskhash** [Cidan/BetterBags#420]
### Describe the feature

Hey! Awesome work on BetterBags.
I feel for me, seperating armor by every slot or gear set makes it too split.
Would be amazing to have these categories for gear:
-Armor
-Jewelry (Except trinkets)
-Trinkets
-Weapon/Offhand

### Describe the implementation

Would be amazing to have these categories for gear:
-Armor
-Jewelry (Except trinkets)
-Trinkets
-Weapon/Offhand

**Comment by AMaribo** [comment]
You can now make these categories yourself with the new search-based categories feature released in v0.1.90.
