### ISSUE TITLE
[Feature]: ElvUI Skin Tweak

### ISSUE THREAD

**Issue by Triksterism** [Cidan/BetterBags#427]
### Describe the feature

As the unofficial ElvUI skin for BetterBags has ceased due to one being included in the base addon, one thing that is missing is having black icon outlines for all the items. Square 1 pixel outlines for every item icon in the bag would be nice. Maybe put it on a toggle for people who don't prefer it I guess but it'd match up super nice with various clean icon packs players use.

### Describe the implementation

Include it in the base ElvUI skin for BetterBags

**Comment by Raenore** [comment]
Hey hey,

Cidan confirmed today in the Discord that he is looking into icon buttons (and their outlines) skinning in the near future:
![image](https://github.com/Cidan/BetterBags/assets/172234435/2ae2fe64-9ec2-48b8-8da2-1b45ef6d91ad)

If my understanding of what he meant is correct, this should bring back the theming functionality that you're asking for.

**Comment by Triksterism** [comment]
That's great to hear, thank you for the informative response!

**Comment by AMaribo** [comment]
This was fixed in v0.1.71.
