### ISSUE TITLE
Item icons are being cut off when in compact mode.

### ISSUE THREAD

**Issue by ozoxchris** [Cidan/BetterBags#43]
![betterbags bug](https://github.com/Cidan/BetterBags/assets/27544118/06071543-ea88-4f07-ae07-314aa20fdd33)

**Comment by Cidan** [comment]
This is due to some recent changes in how we handle the grid. I think I know exactly where the issue is. Fun fact, if you use the mouse wheel to scroll, you should be able to see it (though that's not intended!).

**Comment by Cidan** [comment]
This has been fixed.
