### ISSUE TITLE
Bag opening half off-screen

### ISSUE THREAD

**Issue by Lugnaut** [Cidan/BetterBags#431]
### Addon Version

v0.1.64-1-gf107bab and newer

### World of Warcraft Version

Cataclysm

### Describe the bug

The bag doesn't open where it is left, when addon is used alone it opens farther up the screen the first time opening after reload/relog. When used with Elvui it moves up and to the right where it starts off half way off the screen.

### Steps to reproduce

Download just the addon, base settings.
Open bag and move to where u want it.
Reload.
Open bag and watch it not be in same place.

**Comment by Cidan** [comment]
I can confirm this is happening to me too -- I'll have a patch out today.

**Comment by AMaribo** [comment]
Fixed in v0.1.68.
