### ISSUE TITLE
Window ignores scale when "Show Bags" is enabled

### ISSUE THREAD

**Issue by silverhawke249** [Cidan/BetterBags#435]
### Addon Version

v0.1.61

### World of Warcraft Version

Cataclysm

### Describe the bug

backpack and bank windows ignore the scale setting when the "Show Bags" option is ticked. this causes the windows to change size, perhaps significantly, depending on what the scaling is set to.

### Steps to reproduce

1. open backpack/bank, make sure "show bags" is disabled
2. open settings, set scale to any value not 100 (the bigger the difference, the better)
3. click the bag icon on the top left of the window, and enable "show bags"
4. backpack/bank window shrinks/enlarges to 100 scale.

![image](https://github.com/Cidan/BetterBags/assets/50395934/da8a1d05-a031-43c6-82ec-92abe7f985d8)
![image](https://github.com/Cidan/BetterBags/assets/50395934/ecaf8004-ed2d-425b-873f-75ebc5339b3d)

**Comment by Cidan** [comment]
It's not ignored, it's that each view has independent settings. When in Show Bags view, set your scale to what you'd like and it save for that specific view. I plan on making this more clear in the future.

**Comment by zeptognome** [comment]
> version of the addon in game
Top the the bag menu
