### ISSUE TITLE
Compatibility with Caerdon Wardrobe

### ISSUE THREAD

**Issue by ozoxchris** [Cidan/BetterBags#44]
Would love to see this addon become Compatible with Better Bags, or feature what it does within Better Bags.
It shows indicators for quest items, learnable transmog, BoE, BoA, etc.

### Caerdon Wardrobe
https://www.curseforge.com/wow/addons/caerdon-wardrobe

Images
![BankBags](https://github.com/Cidan/BetterBags/assets/27544118/c2038b31-b07d-4275-a668-286e1d09818f)

![Options](https://github.com/Cidan/BetterBags/assets/27544118/c7cfdf1d-0c92-4604-85b7-41d61d1cef0a)

An example of how it looks with Adibags
![image](https://github.com/Cidan/BetterBags/assets/27544118/1cfc07bb-a7ca-4f0e-92dd-85a7a4113cc0)

**Comment by zeptognome** [comment]
This was implemented with https://github.com/Caerdon/CaerdonWardrobe/releases version 3.6
