### ISSUE TITLE
The bag content appear darkened/shadowed and harder to see today

### ISSUE THREAD

**Issue by octapusxft** [Cidan/BetterBags#442]
### Addon Version

v0.1.67

### World of Warcraft Version

Retail

### Describe the bug

I simply run the game as usual after updating my addons.
I will include an image of how it looks now
![2024-06-27 19_44_39-World of Warcraft](https://github.com/Cidan/BetterBags/assets/62168059/c9bc0377-4763-4db8-99d1-b214276c6980)

### Steps to reproduce

I am not sure how to reproduce it

**Comment by Cidan** [comment]
Does this happen on all themes, or just default?

**Comment by Cidan** [comment]
Also, if you set the opacity of the bag to 100%, does it "block" the icons, or do they stay faded?

**Comment by Cidan** [comment]
Talking to some other users, it seems like this might be related to search -- can you /reload, and does it go away?

**Comment by Jonnnyki** [comment]
Having the same issue on v0.1.67 Cata classic, reloading does not change it, happens in all Themes 'Default', 'Simple Dark' and 'ElvuI' from external addon.

**Comment by Cidan** [comment]
Figured it out: delete the elvui external addon/skin -- it's deprecated and is not required anymore, and will break bags. ElvUI is now built in.
