### ISSUE TITLE
Items in the bag are darkened

### ISSUE THREAD

**Issue by Inzaniity** [Cidan/BetterBags#444]
### Addon Version

v0.1.67

### World of Warcraft Version

Retail

### Describe the bug

Updating to the latest version made all items in the bag be darker as if the search was active but nothing is matched. 
![image](https://github.com/Cidan/BetterBags/assets/17164019/7aa200da-bec2-47ec-baf1-d87bab8cf0af)

Same inventory with v0.1.66
![image](https://github.com/Cidan/BetterBags/assets/17164019/e7c7832a-b599-4ba9-b2f9-9a0920953b78)

### Steps to reproduce

Updated to latest version and opened the bag.

**Comment by AMaribo** [comment]
Delete the BetterBags ElvUI plugin/addon. ElvUI themeing is now built in and the plugin is deprecated and will break bags.

**Comment by Inzaniity** [comment]
Hm that fixed it but I raterh still use v0.1.66 since the bag categories seem to be better placed as opposed to the new version

**Comment by AMaribo** [comment]
What do you mean by better placed?
If you want to remove the 2nd column, there is an option in the settings (`/bb`) for column count.

**Comment by Inzaniity** [comment]
That worked, thanks.

**Comment by umop3plsdn** [comment]
Well glad i stumbled on this the dark thing was really driving me bonkers

**Comment by Cidan** [comment]
I've asked the ElvUI plugin author to push a release that disables the addon entirely.
