### ISSUE TITLE
Eye-glass: view items and clothing (GONE)

### ISSUE THREAD

**Issue by mrlinuxdude** [Cidan/BetterBags#447]
### Addon Version

v0.1.67, v0.1.68

### World of Warcraft Version

Retail

### Describe the bug

**Not sure if somebody posting this issue already i checked and didn't see any. so sorry if it has been posted.**

Seems the last two versions of Betterbags v0.1.67, v0.1.68 has this issue where you can't view your items. If you hover over Boots,chest or hat any gear etc. press "ctrl" eye-glass come up view it on your portrait. It does't let you or comes up.

I had to go back to version v0.1.66

No other issues here just this minor one that really big to me. Thanks for awesome add-on i love it. 

### Steps to reproduce

i just updated it today on v0.1.68 and tried v0.1.67
its gone in the last two versions v0.1.67, v0.1.68 i tried.  i was on v0.1.66 untill today 28 of Jun

**Comment by Cidan** [comment]
I'm able to click view an item -- do you think you can show me a screenshot?

**Comment by Cidan** [comment]
Oh I see, it's the actual hourglass icon. I'll take a look at this.

**Comment by Cidan** [comment]
Found the bug! Fixed in the next release.

**Comment by Cidan** [comment]
Fixed in .69.

**Comment by mrlinuxdude** [comment]
wow your amazing. that was really fast reply thanks a lot
