### ISSUE TITLE
Bag search is not functioning [Cata]

### ISSUE THREAD

**Issue by BGannon2** [Cidan/BetterBags#448]
### Addon Version

v0.1.69

### World of Warcraft Version

Cataclysm

### Describe the bug

Bag search functionality doesn't darken items that don't match the search term like it usually does. Seems non-functional.
![image](https://github.com/Cidan/BetterBags/assets/9086150/c8c08ce6-0843-4acf-b4dc-355000bdc7f4)

### Steps to reproduce

1. Open bag
2. Type in search box for an item you have in your bag

**Comment by BGannon2** [comment]
Of note, this is happening with all of the themes without any additional plugins installed.

**Comment by AMaribo** [comment]
This has been fixed with the upgrades to the search engine.
