### ISSUE TITLE
Everything is greyed out

### ISSUE THREAD

**Issue by hlokk101** [Cidan/BetterBags#449]
### Addon Version

v0.1.69

### World of Warcraft Version

Retail

### Describe the bug

![image_2024-06-29_103619140](https://github.com/Cidan/BetterBags/assets/75588676/d3903c42-4867-4ddc-a3fd-725701075436)

Everything is greyed out. Items are still usable, they're just... dull.

### Steps to reproduce

1. Open bags.
2. See them being greyed out.

**Comment by AlexHaible** [comment]
You likely have the old ELVUI theme addon installed. Remove that. There's a built in theme now.

**Comment by icym1lk** [comment]
I've been having the same issue since the latest update. Removed the ELVui skin I had installed as suggested and reloaded but the issue persists. However, restarting the game completely after removing the ELVui skin seems to have corrected it.

**Comment by Cidan** [comment]
Please delete the old ElvUI skin as others have suggested -- it is causing errors and is no longer updated.
