### ISSUE TITLE
[Feature]: Button to bypass "New Item" timer.

### ISSUE THREAD

**Issue by joshgsx** [Cidan/BetterBags#450]
### Describe the feature

Please add a button, that when clicked it can bypass the items staying in "Recent Items". 

### Describe the implementation

Please add a button, that when clicked it can bypass the items staying in "Recent Items".

**Comment by AlexHaible** [comment]
That already exists. Right click the bag button in the top left. That forces a resort, which also takes all items out of "Recent Items"

**Comment by AMaribo** [comment]
If you are in Cataclysm Classic or SOD, you'll need the SortBags addon as Blizzard has disabled the sort API in Classic versions.
