### ISSUE TITLE
ElvUI and BetterBags broken

### ISSUE THREAD

**Issue by Tyology** [Cidan/BetterBags#451]
### Addon Version

v0.1.70

### World of Warcraft Version

Retail

### Describe the bug

For the last several versions, BetterBags have been completely unusable with ElvUI. All the skins darken everything so you can't see things. Sometimes you can get the icons to intermittently show by switching between Themes but I just have to disable this thing until it's fixed.
![image](https://github.com/Cidan/BetterBags/assets/9412390/e501c01c-e7f2-4ef4-9c84-86c56d9f0153)

### Steps to reproduce

Install latest BetterBags and ElvUI, WindTools, and BetterBags ElvUI.

**Comment by AMaribo** [comment]
If you have the old ElvUI BetterBags skin addon, remove it. It is causing errors and it now deprecated. BetterBags now has an ElvUI theme is built into the base addon.

**Comment by AlexHaible** [comment]
For the last several versions BetterBags has had its own built in ElvUI theme. You've still got the addon installed. You should uninstall the skin addon.

**Comment by nickdnk** [comment]
How can I make the item border color go away or be less vivid? I removed the ElvUI skin addon after reading this thread cause it bugged out, but now all the items have white border (or blue/green/purple depending on quality) and it hurts readability a lot. And depending on the scale you set, one of each side of the border square is always invisible below 100%.

**Comment by Gnathach** [comment]
Removing the old ElvUI BetterBags Skin addon fixed this for me.

**Comment by Cidan** [comment]
@nickdnk More work will be completed soon on ElvUI theme as it's a work in progress still.
