### ISSUE TITLE
Inconsistencies with gap between window border and item frame based on view type.

### ISSUE THREAD

**Issue by ozoxchris** [Cidan/BetterBags#46]
Inconsistencies with gap between window border and item frame based on view type.

### Example
![image](https://github.com/Cidan/BetterBags/assets/27544118/52ebd3a4-cdbe-4ace-8994-d4402ff4b46c)

### One bag (I really prefer how tight this looks!!)
![image](https://github.com/Cidan/BetterBags/assets/27544118/01e35f35-215e-47e8-9d6b-cbda05bdb024)

### Section Grid
![image](https://github.com/Cidan/BetterBags/assets/27544118/116ddefb-c043-4366-b5ee-6d2d9df079c2)

### List View
![image](https://github.com/Cidan/BetterBags/assets/27544118/8a3b8b45-11f7-45f0-af68-3556bca8810a)

### Stock UI One Bag for reference (Also tight and clean looking ;) )
![image](https://github.com/Cidan/BetterBags/assets/27544118/07c45d0e-8e49-458c-adb8-5d61a17374fe)

**Comment by Cidan** [comment]
Yes, I've noticed this as well and it also bugs me. I am going to redo some parts of the rendering code that works with offsets and sizing to fix this and make it consistent, as there's a few border bugs still around.

**Comment by Cidan** [comment]
Pushed some significant improvements to alignment all around. The one bag alignment is slightly different than the section alignment, and this is on purpose. I may (really stressing may here) make insets configurable at some point in the future.

Closing this out for now, but if you find any alignment issues, please let me know.
