### ISSUE TITLE
[Feature]: Buy bank bag slots

### ISSUE THREAD

**Issue by xenoterracide** [Cidan/BetterBags#467]
### Describe the feature

When you don't have all the slots unlocked presumably with bags in them... you can't unlock a new slot. There's no purchase slot button

### Describe the implementation

I'd be happy with a purchase slot button with the right amount of gold for the next slot. Although I think you also need to be able to view which bags are currently slotted for adding and removal.

for now my workaround is simply disable the addon when I need to do this. Playing in Classic

**Comment by AMaribo** [comment]
I don't have any characters on Classic to test with, but on Retail, if you left-click the bag icon on the top-left corner of the bank, and turn on Show Bags, you can see all bag slots and purchase any slots you don't yet have purchased. This also allows you to view, add, and replace bags.

![image](https://github.com/user-attachments/assets/55d2c0eb-10b6-49a4-a162-ed75eb211b78)

**Comment by xenoterracide** [comment]
yeah, that works, sorry I didn't notice it.
