### ISSUE TITLE
Purchasing Reagent bag

### ISSUE THREAD

**Issue by NovaStarr724** [Cidan/BetterBags#468]
### Addon Version

0.1.75

### World of Warcraft Version

Retail

### Describe the bug

When I visit the bank it doesn't give me the option of purchase the reagent bag and it won't allow me to deposit anything until I do.  So I have to turn off betterbags and use ElvUI's bags to purchase the reagent bag.  Can you please fix this?

### Steps to reproduce

Just go to the bank on a fresh character using betterbags.

**Comment by nexus-guardian** [comment]
My fix has been to uncheck the addon, reload, buy the reagent tab, and reload the better bags to gain access. If the reagent tab was added to the top by the bank tabs when you show bags that would be seen that it's purchased and allow you to buy there. It's mainly when starting a new toon that it's not available.

**Comment by AMaribo** [comment]
The reagent bank can now be purchased by clicking on the reagent bank tab on a character that does not own the tab yet.
