### ISSUE TITLE
Cataclysm Classic version broke in 0.1.77

### ISSUE THREAD

**Issue by Pewtro** [Cidan/BetterBags#476]
### Addon Version

v0.1.77

### World of Warcraft Version

Cataclysm

### Describe the bug

When updating to 0.1.77, cataclysm classic has a large amount of lua errors causing bags to no longer work. 

Reverting to 0.1.75 works again.

### Steps to reproduce

1. Install 0.1.77 on cataclysm and notice lua errors

**Comment by shaakz** [comment]
Same for SOD.

`Message: Interface/AddOns/BetterBags/core/constants.lua:289: table index is nil
Time: Wed Jul 24 12:09:33 2024
Count: 1
Stack: Interface/AddOns/BetterBags/core/constants.lua:289: table index is nil
[string "@Interface/AddOns/BetterBags/core/constants.lua"]:289: in main chunk

Locals: addonName = "BetterBags"
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 isBCC = false
 EnableModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHookScript = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:409
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:394
 GetName = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "BetterBags"
 IsEnabled = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 isRetail = false
 HookScript = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:365
 IsHooked = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:492
 IsModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:464
 SetDefaultModuleState = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 SetEnabledState = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:273
 enabledState = true
 SecureHook = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:335
 isClassic = true
 hooks = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 IterateModules = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 isCata = false
 RawHook = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:312
 UnhookAll = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:476
 Unhook = <function> defined @Interface/AddOns/BetterBags/libs/AceHook-3.0/AceHook-3.0.lua:417
 defaultModuleState = false
 Disable = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
}
L = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 data = <table> {
 }
 EnableModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/BetterBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 enabledState = true
 S = <function> defined @Interf`

**Comment by mrbuds** [comment]
on sod

![image](https://github.com/user-attachments/assets/d8b7890f-ddf0-43c9-81e6-6810f656558f)

**Comment by AMaribo** [comment]
This issue is resolved in v0.1.78
