### ISSUE TITLE
Showing wrong ilevels

### ISSUE THREAD

**Issue by FlyingDiver** [Cidan/BetterBags#48]
Drogbar Stones, and a couple of Sunless leather pieces (all season 2) are showing ilvl 250, when they're actually 411 and 424.

Wildercloth fishing cap showing 317 when it's 320.

Lariat showing 350 when it's 424 (shadowflame crafted).

**Comment by Cidan** [comment]
Can you supply me with ItemID's for the wrong items? I think I know what this is, but I need to test.

**Comment by FlyingDiver** [comment]
Stones is 204811
Moonless items are 204934, 204935
Lariat is 193001

**Comment by FlyingDiver** [comment]
One minute

**Comment by FlyingDiver** [comment]
No it did not.  Same results.

**Comment by Cidan** [comment]
So interestingly, I can't get the item level info for those items when I manually call `/run print(GetDetailedItemLevelInfo(itemID))` where itemID is an ID you passed. Let me see if I can figure out what's going on.

**Comment by FlyingDiver** [comment]
When I try that for the lariat, I get `250 false 350`

**Comment by Cidan** [comment]
Hm, so that's right -- that's what the Blizzard API returns. How about `/run print(GetItemInfo(itemID))` and the output of that?

**Comment by FlyingDiver** [comment]
[16:44] Elemental Lariat [Elemental Lariat] 4 350 1 Armor Miscellaneous 1 INVTYPE_NECK 4548906 356629 4 0 1 9 nil false

**Comment by Cidan** [comment]
The other API is also returning 350 -- those are the only two API's for getting item level that I'm aware of. How are you getting your item level information?

**Comment by Cidan** [comment]
Screenshot?

**Comment by FlyingDiver** [comment]
This keyboard doesn't have a print screen key, and I only use Windows for gaming.  Is there a key combo that will work?

**Comment by Cidan** [comment]
Windows key + Shift + S on any modern windows, then click/drag a box to capture.

**Comment by Cidan** [comment]
Let's try this other API -- do this.

In items.lua, under GetDetailedItemLevel, add:

`effectiveIlvl = C_Item.GetCurrentItemLevel(itemLocation)`

Reload, and see if that does it.

**Comment by FlyingDiver** [comment]
![Screenshot 2023-12-03 165056](https://github.com/Cidan/BetterBags/assets/72976/2fc50b24-436c-4ca7-9503-e935c575fbc4)

**Comment by FlyingDiver** [comment]
Leave the parameter as itemLink, or revert it?

**Comment by Cidan** [comment]
doesn't matter, we're overriding the variable we care about

**Comment by FlyingDiver** [comment]
That fixed it.

**Comment by Cidan** [comment]
Okay, excellent, fix incoming.
