### ISSUE TITLE
No longer able to interact with actual bags to change them? 

### ISSUE THREAD

**Issue by DCCXVIII** [Cidan/BetterBags#480]
### Addon Version

0.1.78

### World of Warcraft Version

Retail

### Describe the bug

The option to show the actual bags shows them as all greyed out and thus are not intractable or replaceable with new bags.

### Steps to reproduce

Use the addon.

**Comment by AMaribo** [comment]
Do you have any Lua errors? I am not able to reproduce it on v0.1.78.

**Comment by Cidan** [comment]
Same, I can't reproduce this.

**Comment by DCCXVIII** [comment]
Looks like your latest release 0.1.79 fixed the issue. Thanks.
