### ISSUE TITLE
Bag Button error / nothing showing in bags

### ISSUE THREAD

**Issue by sylenced** [Cidan/BetterBags#481]
### Addon Version

v.0.1.78

### World of Warcraft Version

Retail

### Describe the bug

![image](https://github.com/user-attachments/assets/78cd571f-cfff-4071-801c-fa7d27c416bc)

**_Showing full error below, maybe it's related to something else ? Unsure_**

Message: .../Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua:294: attempt to index local 'color' (a number value)
Time: Wed Jul 24 21:24:28 2024
Count: 1
Stack: .../Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua:294: attempt to index local 'color' (a number value)
[string "@Interface/AddOns/Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua"]:294: in function `SetItemButtonOverlay'
[string "@Interface/AddOns/Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua"]:249: in function <.../Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua:236>
[string "@Interface/AddOns/Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua"]:672: in function `SetItemButtonQuality'
[string "@Interface/AddOns/Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua"]:265: in function `SetItemButtonQuality'
[string "@Interface/AddOns/BetterBags/frames/item.lua"]:333: in function `SetItemFromData'
[string "@Interface/AddOns/BetterBags/frames/item.lua"]:286: in function `SetItem'
[string "@Interface/AddOns/BetterBags/views/gridview.lua"]:88: in function <Interface/AddOns/BetterBags/views/gridview.lua:80>
[string "@Interface/AddOns/BetterBags/views/gridview.lua"]:164: in function `Render'
[string "@Interface/AddOns/BetterBags/frames/bag.lua"]:251: in function `Draw'
[string "@Interface/AddOns/BetterBags/core/init.lua"]:257: in function `cb'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:50: in function <Interface/AddOns/BetterBags/core/events.lua:45>
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>b
[string "@Interface/AddOns/BetterBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:186: in function <Interface/AddOns/BetterBags/core/events.lua:185>

Locals: button = BetterBagsItemButton695Decorationdefault {
 IconOverlay = Texture {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 icon = BetterBagsItemButton695DecorationdefaultIconTexture {
 }
 count = 0
 HighlightTexture = Texture {
 }
 IconQuestTexture = BetterBagsItemButton695DecorationdefaultIconQuestTexture {
 }
 hasItem = 1
 PushedTexture = Texture {
 }
 emptyBackgroundAtlas = "bags-item-slot64"
 timeSinceUpgradeCheck = 0
 Count = BetterBagsItemButton695DecorationdefaultCount {
 }
 flash = Texture {
 }
 searchOverlay = BetterBagsItemButton695DecorationdefaultSearchOverlay {
 }
 isProfessionItem = false
 itemContextMatchResult = 3
 IconTexture = BetterBagsItemButton695DecorationdefaultIconTexture {
 }
 IconOverlay2 = Texture {
 }
 ItemSlotBackground = Texture {
 }
 minDisplayCount = 1
 flashAnim = AnimationGroup {
 }
 newitemglowAnim = AnimationGroup {
 }
 JunkIcon = Texture {
 }
 ExtendedSlot = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 NewItemTexture = Texture {
 }
 isCraftedItem = false
 AugmentBorderAnimTexture = Texture {
 }
 UpgradeIcon = Texture {
 }
 NormalTexture = BetterBagsItemButton695DecorationdefaultNormalTexture {
 }
 IconBorder = Texture {
 }
 Cooldown = BetterBagsItemButton695DecorationdefaultCooldown {
 }
 ItemContextOverlay = Texture {
 }
 BagIndicator = Texture {
 }
 Stock = BetterBagsItemButton695DecorationdefaultStock {
 }
}
itemIDOrLink = "[Fel Commando]"
quality = 4
isBound = true
color = 0.639216
(*temporary) = Texture {
}
(*temporary) = 0.207843
(*temporary) = 0.933333
(*temporary) = "ffa335ee"
(*temporary) = "attempt to index local 'color' (a number value)"

### Steps to reproduce

This only occurs when logging in and opening bags, sometimes doesn't always error when opening the bags, it just opens it completely empty.

**Comment by zeptognome** [comment]
> itemIDOrLink = "[Fel Commando]"

Delete this conduit - conduits currently break the Item Quality API
https://github.com/Stanzilla/WoWUIBugs/issues/602

**Comment by sylenced** [comment]
Absolutely insane, but that fixed it.
It was breaking even the blizzard bags !

Thank you for your timely support, have a wonderful rest of the evening !
