### ISSUE TITLE
can not switch to reagent bank

### ISSUE THREAD

**Issue by soso-15** [Cidan/BetterBags#483]
### Addon Version

v0.1.79

### World of Warcraft Version

Retail

### Describe the bug

before TWW I can switch to reagent bank by right clicking of the bag icon of bank.
now I right click the bag icon but nothing happens.

### Steps to reproduce

1.open bank
2.right click the bag icon of bank

**Comment by zeptognome** [comment]
under TWW, with tab support for the bank, Reagent bank access was moved from the bag menu to a tab

![image](https://github.com/user-attachments/assets/b10c8b99-bf94-4ed3-beac-601761c40082)

**Comment by soso-15** [comment]
thank you!
