### ISSUE TITLE
only one of my toons gets this bug

### ISSUE THREAD

**Issue by I-AM-T3X** [Cidan/BetterBags#485]
### Addon Version

v0.1.79

### World of Warcraft Version

Retail

### Describe the bug

only breaks on my auction toon that sales grey mogs

### Steps to reproduce

Message: Interface/AddOns/BetterBags/core/hooks.lua:86: attempt to index field 'Backpack' (a nil value)
Time: Thu Jul 25 23:25:16 2024
Count: 2
Stack: Interface/AddOns/BetterBags/core/hooks.lua:86: attempt to index field 'Backpack' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/core/hooks.lua"]:86: in function `ToggleAllBags'
[string "@Interface/AddOns/BetterBags/core/init.lua"]:87: in function `BetterBags_ToggleBags'
[string "BETTERBAGS_TOGGLEBAGS"]:1: in function <[string "BETTERBAGS_TOGGLEBAGS"]:1>

Locals:

**Comment by Cidan** [comment]
There's another error that happens before this one, can you scroll back and see what it is?

**Comment by I-AM-T3X** [comment]
these are the only other errors i found in my bug sack related to better bags


Error1

Message: Interface/AddOns/BetterBags/frames/search.lua:91: attempt to index field 'Backpack' (a nil value)
Time: Fri Jul 26 13:26:41 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/search.lua:91: attempt to index field 'Backpack' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/frames/search.lua"]:91: in function `UpdateSearch'
[string "@Interface/AddOns/BetterBags/frames/search.lua"]:128: in function <Interface/AddOns/BetterBags/frames/search.lua:127>

Locals: 

error 2:

Message: Interface/AddOns/BetterBags/frames/currency.lua:139: attempt to index local 'info' (a nil value)
Time: Fri Jul 26 13:26:38 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/currency.lua:139: attempt to index local 'info' (a nil value)
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals: parent = Frame {
 DragonflightLandingOverlay = Frame {
 }
}
overlayFrame = nil

**Comment by AMaribo** [comment]
Are you tracking Trader's Tender as a currency at the bottom of the bag?

**Comment by I-AM-T3X** [comment]
only on my main

**Comment by AMaribo** [comment]
This was fixed in v0.1.80.
