### ISSUE TITLE
Toggle Bags LUA Error

### ISSUE THREAD

**Issue by Faulkal** [Cidan/BetterBags#487]
### Addon Version

v0.1.79-3-ga37fa3e 

### World of Warcraft Version

Retail

### Describe the bug

pressing B to open bags would fail until a /reload was done. 

31x BetterBags/core/hooks.lua:86: attempt to index field 'Backpack' (a nil value)
[string "@BetterBags/core/hooks.lua"]:86: in function `ToggleAllBags'
[string "@BetterBags/core/init.lua"]:87: in function `BetterBags_ToggleBags'
[string "BETTERBAGS_TOGGLEBAGS"]:1: in function <[string "BETTERBAGS_TOGGLEBAGS"]:1>

Locals:
self = <table> {
 isBCC = false
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 _bindingFrame = Frame {
 }
 defaultModuleState = false
 name = "BetterBags"
 baseName = "BetterBags"
 orderedModules = <table> {
 }
 backpackShouldClose = false
 isRetail = true
 Bags = <table> {
 }
 atBank = false
 enabledState = true
 backpackShouldOpen = false
 isClassic = false
 hooks = <table> {
 }
 isCata = false
 _buttons = <table> {
 }
}
interactingFrame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "ToggleAllBags"
(*temporary) = "attempt to index field 'Backpack' (a nil value)"
debug = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabled = false
 window = <table> {
 }
 tooltip = BetterBagsTooltip {
 }
 name = "BetterBags_Debug"
 orderedModules = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 profiles = <table> {
 }
 colors = <table> {
 }
 defaultModuleState = true
 moduleName = "Debug"
}
addon = <table> {
 isBCC = false
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 _bindingFrame = Frame {
 }
 defaultModuleState = false
 name = "BetterBags"
 baseName = "BetterBags"
 orderedModules = <table> {
 }
 backpackShouldClose = false
 isRetail = true
 Bags = <table> {
 }
 atBank = false
 enabledState = true
 backpackShouldOpen = false
 isClassic = false
 hooks = <table> {
 }
 isCata = false
 _buttons = <table> {
 }
}
events = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "BetterBags_Events"
 orderedModules = <table> {
 }
 _eventArguments = <table> {
 }
 _eventQueue = <table> {
 }
 _bucketCallbacks = <table> {
 }
 _bucketTimers = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 _messageMap = <table> {
 }
 _eventHandler = <table> {
 }
 _eventMap = <table> {
 }
 moduleName = "Events"
 defaultModuleState = true
}

### Steps to reproduce

not sure what triggers this. ill keep testing and get back to it.

**Comment by AMaribo** [comment]
Are you tracking Trader's Tender?

**Comment by Faulkal** [comment]
no, flightstones and gold

**Comment by AMaribo** [comment]
This was fixed in v0.1.80.
