### ISSUE TITLE
Lua Error on /rl / login

### ISSUE THREAD

**Issue by Harsesis89** [Cidan/BetterBags#488]
### Addon Version

v0.1.80

### World of Warcraft Version

Retail

### Describe the bug

When logging on or /rl the following error comes up:

Message: Interface/AddOns/BetterBags/frames/grid.lua:161: invalid order function for sorting
Time: Sat Jul 27 17:09:54 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/grid.lua:161: invalid order function for sorting
[string "@Interface/AddOns/BetterBags/frames/grid.lua"]:161: in function `Sort'
[string "@Interface/AddOns/BetterBags/views/gridview.lua"]:247: in function `Render'
[string "@Interface/AddOns/BetterBags/frames/bag.lua"]:258: in function `Draw'
[string "@Interface/AddOns/BetterBags/core/init.lua"]:257: in function `cb'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:50: in function <Interface/AddOns/BetterBags/core/events.lua:45>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:186: in function <Interface/AddOns/BetterBags/core/events.lua:185>

Locals: self = <table> {
 view = <table> {
 }
 columns = <table> {
 }
 sortVertical = true
 spacing = 4
 cells = <table> {
 }
 maxCellWidth = 2
 box = BetterBagsScrollGrid1 {
 }
 headers = <table> {
 }
 cellToColumn = <table> {
 }
 idToCell = <table> {
 }
 compactStyle = 0
 inner = Frame {
 }
 frame = BetterBagsScrollGrid1 {
 }
 cellToID = <table> {
 }
 bar = Frame {
 }
}

After the error, the bag is able open but only an empty frame is shown:

![image](https://github.com/user-attachments/assets/0c8b0f5e-c2ed-4c07-b727-9342415f3fe2)

If you close the bag and wait a few seconds before opening it again, the bag contents are then shown.

This error occurs since updating to the latest version earlier today.
The following modules are installed.

![image](https://github.com/user-attachments/assets/920fe695-8605-44bc-9083-dc0ca8092a0e)

### Steps to reproduce

1. Login or /rl

**Comment by Harsesis89** [comment]
The root cause seems to be in https://www.curseforge.com/wow/addons/betterbags-gear-first
Disabling the plugin makes the error go away.
I raised an issue there too.

**Comment by zeptognome** [comment]
As there is no current plugin API that supports replacing BetterBags internal sorting functions, its up to that author to fix and/or keep up with internal changes. You'll need to wait for a fix from them and/or disable using it at least for now.
