### ISSUE TITLE
All icons shaded in

### ISSUE THREAD

**Issue by grumpypbear** [Cidan/BetterBags#496]
### Addon Version

v0.1.80-12-ga2ba437

### World of Warcraft Version

Retail

### Describe the bug

Both v0.1.80-11-gb1b0659 & v0.1.80-12-ga2ba437 (30/07/2024 updates) add a darkened shade over the bag icons. 

It happens the moment you do anything with items in the bag. So, on first load or reload the bag icons look normal, but if you equip an item, swap gems, sort bags, do literally anything that uses an item in the bag every item becomes shaded.

I'm playing remix. I disabled every addon and had no bag issues using default ui. Turned on betterbags (no plugins) and immediately after right clicking to sort bags the icons went dark. 

The issue goes away after reverting to v0.1.80.10-g30243f1.
![WoWScrnShot_073024_181127](https://github.com/user-attachments/assets/86f5bf8b-5207-462e-8c3d-0f973294b2d3)

### Steps to reproduce

1. open bag
2. right click to sort bags or
3. remove gem or
4. add gem or
5. sneeze in the bags direction...

**Comment by grumpypbear** [comment]
sorry, i should have used the **_newest version_** in the version section. It is the newest version and the one before it. I had to revert 3 versions back.

**Comment by Cidan** [comment]
Thanks for the report, I'll fix this today.

**Comment by Cidan** [comment]
This should be fixed in the latest alpha -- I can't test because everything is down, but on cata it did fix it.

**Comment by AMaribo** [comment]
This was fixed and released with v0.1.81.
