### ISSUE TITLE
More intuitive search function?

### ISSUE THREAD

**Issue by Lyrandos** [Cidan/BetterBags#497]
### Describe the feature

Hey! I've only recently discovered your addon so still taking a bit to get used to it but I really love the potential of this!

Apologies in advanced if this has already been brought up or I'm simply not using the search feature correctly however I've noticed searching for in particular "uncommon(green), rare(blue), epic(purple), legendary(orange)" doesn't seem to register when using betterbags search feature. Before I downloaded it, WoW's base UI seems to be able to run this search and it works! Currently I've been using this a lot in MoP remix, it makes scrapping uncommon and rare items very quick!
Image below is screenshot of betterbags
![image](https://github.com/user-attachments/assets/c2c8ab89-d710-4ceb-baaf-0bbb769a2178)

### Describe the implementation

If this is already an upcoming feature than sweet! If not brought up yet it would be a very handy thing to have :)
Image below is screenshot of Base WoW Bag UI
![image](https://github.com/user-attachments/assets/19815c8c-ee78-44fe-a816-bbd31d10e153)

**Comment by Cidan** [comment]
Good timing! This has been implemented in the latest alpha release, which will come with a readme update that showcases the new search engine and search language features. It's extremely comprehensive and will fill this gap. A full release should happen later today.

Thanks!

**Comment by AMaribo** [comment]
The improved search was released today with v0.1.81.

**Comment by Lyrandos** [comment]
Amazing! Legend! thank you heaps!

**Comment by Lyrandos** [comment]
Hey I dunno if i'm doing something wrong but the search features don't seem like it's working. I use WoWup,io CF version and BetterBags that i updated to is v0.1.87 even trying to search for gear that has a particular stat (vers, crit, mast, hast, avoidance) etc not illuminating any gear in bags when searching.

**Comment by AMaribo** [comment]
Tooltip scanning is not yet implemented, so searching for things like particular stats will not yet work.
The [Readme](https://github.com/Cidan/BetterBags?tab=readme-ov-file#search) has more information about the specifics on the search functionality. The same information is also in the CurseForge description.
