### ISSUE TITLE
Right-clicking an item to deposit into warbank always deposits into Tab 1

### ISSUE THREAD

**Issue by duraz0rz** [Cidan/BetterBags#500]
### Addon Version

v0.1.80

### World of Warcraft Version

Retail

### Describe the bug

When you right-click to deposit an item, the deposited item does not appear in the tab you have open. It gets deposited into Tab 1 instead. Unsure if it spills over into Tab 2 once Tab 1 is filled.

Dragging and dropping the item into the opened tab does still work, though.

### Steps to reproduce

1) Open a warbank tab other than Tab 1.
2) Deposit an item by right-clicking on it.

Expected: Item is deposited into the tab you have open.  
Actual: Item is deposited into Tab 1.

**Comment by Cidan** [comment]
This is a Blizzard thing, not a BetterBags thing. This also happens in the default UI. I have no idea why Blizzard does this.

**Comment by duraz0rz** [comment]
Oh, that's stupid ... thank you!
