### ISSUE TITLE
Addon does not show Warband gold or allow deposit or withdrawal

### ISSUE THREAD

**Issue by joeyherne** [Cidan/BetterBags#502]
### Addon Version

v0.1.80

### World of Warcraft Version

Retail

### Describe the bug

Addon removes Withdraw and Desposit for warbank and does not show gold.

### Steps to reproduce

Open warbank.

**Comment by Cidan** [comment]
This is being worked on today.

**Comment by zeptognome** [comment]
and released with v0.1.83
Enjoy!
