### ISSUE TITLE
[Feature]: Warband - Bank - Currency

### ISSUE THREAD

**Issue by fkany** [Cidan/BetterBags#504]
### Describe the feature

Firstly, congratulations on the addon... it's fantastic.
Please, don't forget to click the button to deposit and withdraw gold from Warband bank

### Describe the implementation

Firstly, congratulations on the addon... it's fantastic.
Please, don't forget to click the button to deposit and withdraw gold from Warband bank

**Comment by Cidan** [comment]
Already in the works -- I have it working locally, just packaging it up. Should be out in the next few minutes.

**Comment by Cidan** [comment]
Done and released.
