### ISSUE TITLE
Unpin category

### ISSUE THREAD

**Issue by bennyty** [Cidan/BetterBags#505]
### Addon Version

v0.1.84

### World of Warcraft Version

Retail

### Describe the bug

It's either unclear or impossible to unpin a category.

P.S. Is there also any way to undelete a category (such as cooking) if I've made a mistake? Low priority, I just won't delete the ones I actually want 👍 

### Steps to reproduce

Shift + Left to pin category.
Presumably Shift + left on a pinned category should unpin it? Or something else in the tooltip.

**Comment by zeptognome** [comment]
You can drag the category you want to un-pin down to the Automatic section
![image](https://github.com/user-attachments/assets/9452fca3-5881-4659-b116-af7b008f8ba4)

There is no current undelete - but you could make a backup of important categories with the <https://github.com/zeptognome/BetterBags_ImportExport> plugin I wrote
