### ISSUE TITLE
Warband Bank UI Errors

### ISSUE THREAD

**Issue by joeyherne** [Cidan/BetterBags#509]
### Addon Version

v0.1.83

### World of Warcraft Version

Retail

### Describe the bug

Warbank only shows the empty slots and creates extra warbank tabs. 
![image](https://github.com/user-attachments/assets/c0ddc9c4-87e9-41a9-87f5-31282c3baca9)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/937274cf-24c0-4833-90d8-1d5d7448e279)
1. Click Warband tab at bank.

**Comment by joeyherne** [comment]
![image](https://github.com/user-attachments/assets/ecd564c4-28dd-4389-98d8-cc817e462767)
After opening and closing sometimes it works, but every time the bank is opened new tabs appear.

**Comment by zeptognome** [comment]
So, there is a bug when you have multiple tabs with the same name.
To fix, load the game without BetterBags, and rename the tabs to have different names.

**Comment by kcoderhere** [comment]
![image](https://github.com/user-attachments/assets/00d2df49-7166-4629-8810-3eb02e6eb081)
Renamed "Tab 1" as "Gear" and it renamed the "Purchase New Tab" tab as "Gear" and now I can't purchase new tabs.

**Comment by zeptognome** [comment]
The fix for tab names is in version v0.1.87.
