### ISSUE TITLE
The Scary Vault of Ur

### ISSUE THREAD

**Issue by Faulkal** [Cidan/BetterBags#51]
Trying to use a https://www.wowhead.com/item=203720/restorative-water but had already used it so it might not be able to actually be used where im using it but this error poped up when trying to use it again. 

2x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterBags' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1424: in function <FrameXML/ContainerFrame.lua:1333>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1476: in function <FrameXML/ContainerFrame.lua:1463>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Cidan** [comment]
Are you able to reproduce this 100% of the time?

**Comment by Cidan** [comment]
I've confirmed how this happens, and can reproduce it 100% of the time, which is great. I need to investigate a fix for it, which is extremely high priority -- I expect a fix today.

**Comment by Cidan** [comment]
This is fixed in .64 -- thanks for the heads up!
