### ISSUE TITLE
Icon border gone after changing spec - ELVUI Theme

### ISSUE THREAD

**Issue by Grupson** [Cidan/BetterBags#512]
### Addon Version

v0.1.86

### World of Warcraft Version

Retail

### Describe the bug

When changing spec and got assignet Equipment menager to that spec icon borders dissaper for most bag items
Screenshot Before:

![Wow_1NPEyLrHXp](https://github.com/user-attachments/assets/1675f925-58a5-419b-8d6f-b615780ee52d)

Screenshot after:

![Wow_Fgl76A8Gjt](https://github.com/user-attachments/assets/b9b5f402-3db3-4a4c-8068-5a706a6766f6)

### Steps to reproduce

Just assign elvui theme and gear to eq manager

**Comment by Cidan** [comment]
Fixed.
