### ISSUE TITLE
Bank ignoring config settings

### ISSUE THREAD

**Issue by Mazzaradi** [Cidan/BetterBags#514]
### Addon Version

v0.1.87

### World of Warcraft Version

Retail

### Describe the bug

All of the bank tabs (bank, reagents, and warbank) ignore any settings change I make.
The 'View' and 'Display' settings do nothing when changed

### Steps to reproduce

1. Open Bank
2. Change setting
3. Nothing Happens
4. Reload ui
5. still nothing happens

**Comment by zeptognome** [comment]
do you have 'show bags' turned on by chance? most of the category features and settings don't apply to that 'raw' view

**Comment by Mazzaradi** [comment]
That would be the case. That is my mistake.
Should this option be reset when closing the bag/bank to stop this mistake from happening in the future?
