### ISSUE TITLE
Gear sets don't show until after logout/login

### ISSUE THREAD

**Issue by FlyingDiver** [Cidan/BetterBags#52]
Originally reported in #24 

 I just did LFR on that toon and got some new pieces. I set them up in my gear sets, but the groups would not show in the bag frame. /reload did not help. I had to log out and back in to get the groups to show up.

This is reproducible, as follows:

1. Delete all equipment sets (this is standard UI)
2. Create several equipment sets - nothing in BB
3. Do /reload - still nothing in BB
4. Log out then log in - gear sets now in BB

If BB code is the same for login and reload, I have to conclude this is a Blizzard bug where the equipment set API doesn't return the newly created sets until after a logout/login.

**Comment by Cidan** [comment]
Yes, your conclusion does feel like that might be the case. Give me a few to reproduce this -- it very well could be a bug on my end.

**Comment by FlyingDiver** [comment]
This also happens for existing gear sets when you add items to them.

**Comment by Cidan** [comment]
Okay, I was able to reproduce this and found the bug -- it was on my end, but I'm unsure why logging out and logging in fixes it. The item location indexes can be negative numbers, and when iterating an array with negative indexes, `ipairs` will break and `pairs` needs to be used.

Pushing a fix in .63 -- can you confirm a fix on your end?

**Comment by FlyingDiver** [comment]
Yes, it's fixed for me.

**Comment by Cidan** [comment]
Amazing, thanks!
