### ISSUE TITLE
[Feature]: Click to remove all items from "new" category in bag

### ISSUE THREAD

**Issue by RaphanW** [Cidan/BetterBags#520]
### Describe the feature

I'd love it if betterbags had a button (perhaps labeled "N") to click that took everything classified as a new item and sorted it to its normal category. Or if right clicking on new item category did that. Or something.

One of the features I miss most from AdiBags, (second only to having an anchor point other than the top of the bag, as mentioned in other feature requests).

I see you have a ton of feature requests, thank you for your hard work. I went through the 5 pages and thumbs-up some I agreed with.

### Describe the implementation

As described above.

**Comment by zeptognome** [comment]
Yup! This already exists as right-click on the bag menu

![image](https://github.com/user-attachments/assets/089ecf75-da63-4f62-9f8b-ade7c06c2838)

**Comment by RaphanW** [comment]
thanks for the crazy quick reply! 

sorry to take your time but happy to know this exists; eager to try it out next time I am in game :)
