### ISSUE TITLE
"Always Active Search Bar"[Feature]: 

### ISSUE THREAD

**Issue by Sirkgust** [Cidan/BetterBags#523]
### Describe the feature

"Due to my visual impairments, I would like to know if it is possible for the search bar's input box to be ready for typing as soon as I open the bags, without having to move the cursor and click on the search bar."

### Describe the implementation

"First and foremost, this feature should be optional. It could be enabled by checking a box, or through a key combination. For example, if I press 'CONTROL + ENTER' while Betterbags is open, then the search bar should be ready for input."

**Comment by zeptognome** [comment]
Yes, this feature already exists!

If you use the Search Bags keybind, the search bar and the backpack window opens and the search bar has immediate focus for typing
 
![image](https://github.com/user-attachments/assets/86a1c979-c357-4099-b242-83eb44a26fe0)

![image](https://github.com/user-attachments/assets/6be30927-e280-4ac1-b947-ea1529c57928)

**Comment by Sirkgust** [comment]
Thx
