### ISSUE TITLE
Double bag on vendor/ Elvui skin addon doesn't work

### ISSUE THREAD

**Issue by stiflers-mom** [Cidan/BetterBags#524]
### Addon Version

v0.1.89.zip

### World of Warcraft Version

Retail

### Describe the bug

When I open the vendor (Yak vedor for instance) the regular WoW bag appears + the BetterBags addon. Another bug is that the Elvui skin is not 'compatible' with the addon. If I enable the addon an Blizzard error message pops up and it automatically disables the Elvui skin addon.

### Steps to reproduce

Go to an Vendor and open it. Get the better bags Elvui skin addon and reload the UI:
![Bug 1 - Double Bags](https://github.com/user-attachments/assets/54cd78a7-6f1c-4319-8003-53be0e389645)
![Bug 2 - Elvui Skin not compatible](https://github.com/user-attachments/assets/1391f70f-4070-486f-aff0-475dd5b6ffd4)

**Comment by AMaribo** [comment]
To use BetterBags with ElvUI, you'll need to disable the default bags in ElvUI's settings.

The separate ElvUI skin plugin is deprecated. BetterBags has a built in ElvUI skin if you left-click the bag icon in the top left corner of the bags and choose Themes. You should see ElvUI as an option in the list.
