### ISSUE TITLE
Can't open bags after disabling BetterBags addon

### ISSUE THREAD

**Issue by TMRaven85** [Cidan/BetterBags#525]
### Addon Version

v0.1.89

### World of Warcraft Version

Retail

### Describe the bug

I was testing features of BetterBags and Sorted to find my best setup for my bags. BetterBags are great for Pandaria Remix, but when I want to equip newer gear, it just label all my items as lowlvl gear and not in each slot, so I'm still working on that to make it useful. In the meantime I want to be able to easily switch to Sorted, as that addon have that function. But I can't switch directly, so I was disabling BetterBags to get into Sorted, but when I disable BetterBags I can't open any bags at all. 
If I enable BetterBags again, it works to see my bags. But the category of gear for gear slots is not easily found for me, so not as useful. 

Please fix this and make equipment slots easier to manage without making convoluted settings. I can see in the screenshots it's possible, but it's not easily done as in Sorted. 

### Steps to reproduce

I only tried to disable the addon while Sorted also were installed. Then the error happened, but also for none of the two addons enabled, I couldn't even open my bags without addons enabled after this bug. The first time I could disable the addon and restart the game. But the second time it didn't work. So I was "forced" to use BetterBags, unless I deleted it.

**Comment by AMaribo** [comment]
Are you using ElvUI and have the default bag disabled through ElvUI settings? I am not able to replicate the error on Retail with BetterBags and Sorted. installed. Did you receive a Lua error?

As for separating out gear slots, turn on Equipment Location in the BetterBags config window to separate gear by slot.
![image](https://github.com/user-attachments/assets/1865628a-8d09-4f32-b8e6-f6a2bd56bafe)

**Comment by TMRaven85** [comment]
I am not using ElvUI, so don't have the default disabled through that. 
And no, I haven't seen any lua errors popup about it, which is weird. 

I did have the equipment location active, but found under Plugins the itemlvl cap for lowlvl, that one changed my interface.

**Comment by Cidan** [comment]
> but when I disable BetterBags I can't open any bags at all.

If you disable BetterBags and your bags don't work, there is literally nothing I can do about that.

> but found under Plugins the itemlvl cap for lowlvl,

Plugins are not written by this team, they are written by third parties that aren't us. You'll have to talk to any plugin authors for help on those.
