### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by deathmessinger** [Cidan/BetterBags#53]
ok just had a weird issue
I'm on V0.0.61
I have set up for expansion sort
I search for armor and click a piece from Shadowlands to sell it and it sold
The issue was all my armor disappeared from my bags 
It didn't sell it(checked the buyback tab)
Had to reload game to see it again
I tried to reproduce it by selling another piece after reload but I couldn't so this is just a heads up that it happened

**Comment by Cidan** [comment]
I just pushed a bug fix that I think might resolve this. I'm going to close this, but if you can reproduce it, please re-open this.

Thanks!
