### ISSUE TITLE
Black squares showing instead of items

### ISSUE THREAD

**Issue by Gja1988** [Cidan/BetterBags#530]
### Addon Version

Latest

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

When i open my bag, sometimes items are black spots. No idea is showing, its just a black square. When i hover over it the item shows again. 

### Steps to reproduce

Hard to replicate buy i notice it alot when I add new items in my inventory. Not sure whats going on but any suggestions would be great.

**Comment by Cidan** [comment]
Fixed
