### ISSUE TITLE
Partial searches not working

### ISSUE THREAD

**Issue by kcoderhere** [Cidan/BetterBags#532]
### Addon Version

0.1.89

### World of Warcraft Version

Retail

### Describe the bug

Searching for items is doing a Search* instead of *Search*

### Steps to reproduce

Search for an "egg", "Necroray Egg" doesn't show up as a match.

![image](https://github.com/user-attachments/assets/45620827-dd22-432a-960f-6bc6faffc868)

**Comment by Cidan** [comment]
The readme outlines all of this, but, you need to do `name %= blah` to do partial searches. This is changing in the next release though, such that partial searches are default.
