### ISSUE TITLE
Error with BetterBags sorting

### ISSUE THREAD

**Issue by ingham-tyler** [Cidan/BetterBags#533]
### Addon Version

v0.1.89

### World of Warcraft Version

Retail

### Describe the bug

Getting following error when returning from a Radiant Echo event to Dalaran via in-game portals. Refreshing, relogging do not seem to fix the issue. Only disabling the addon (BetterBags).

Date: 2024-08-03 16:55:56
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/BetterBags/frames/grid.lua line 163:
   invalid order function for sorting
Debug:
   [string "=[C]"]: sort()
   [string "@Interface/AddOns/BetterBags/frames/grid.lua"]:163: Sort()
   [string "@Interface/AddOns/BetterBags/views/gridview.lua"]:264: Render()
   [string "@Interface/AddOns/BetterBags/frames/bag.lua"]:302: Draw()
   [string "@Interface/AddOns/BetterBags/core/init.lua"]:258: cb()
   [string "@Interface/AddOns/BetterBags/core/events.lua"]:50:
      Interface/AddOns/BetterBags/core/events.lua:45
   [string "=[C]"]: ?
   [string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: SendMessage()
   [string "@Interface/AddOns/BetterBags/core/events.lua"]:186:
      Interface/AddOns/BetterBags/core/events.lua:185
Locals:
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 maxItemsPerRow = 7
 content = <table> {
 }
 frame = Frame {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 maxItemsPerRow = 7
 content = <table> {
 }
 frame = Frame {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 maxItemsPerRow = 7
 content = <table> {
 }
 frame = Frame {
 }
}

AddOns:
  Swatter, v<%version%> (<%codename%>)
  AddonFactory, v11.0.001
  AdvancedInterfaceOptions, v2.0.0
  AllTheThings, vTWW-4.0.2
  Altoholic, v11.0.001
  Auctionator, v11.0.0
  Auctioneer, v9.1.BETA.5.17 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.17 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.17 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.17 (OneMawTime)
  BattleGroundEnemies, v11.0.0.0
  BetterBags, vv0.1.89
  BetterBagsBound, vv1.2.0
  BetterBagsDragonflightReputationInsignia, vv1.2.0
  BetterBagsGearFirst, vv1.0.8
  BetterBagsHearthstones, v1.18
  BetterBagsWorldEvents, v1.3.3
  BetterFishing, v1.1.24
  BigDebuffs, vv29
  Capping, vv10.2.12
  DataStore, v2024.07.28
  DataStoreAchievements, v2024.07.28
  DataStoreAgenda, v2024.07.28
  DataStoreAuctions, v2024.07.28
  DataStoreCharacters, v2024.07.28
  DataStoreContainers, v2024.07.28
  DataStoreCrafts, v2024.07.28
  DataStoreCurrencies, v2024.07.28
  DataStoreGarrisons, v2024.07.28
  DataStoreInventory, v2024.07.28
  DataStoreMails, v2024.07.28
  DataStorePets, v2024.07.28
  DataStoreQuests, v2024.07.28
  DataStoreReputations, v2024.07.28
  DataStoreSpells, v2024.07.28
  DataStoreStats, v2024.07.28
  DataStoreTalents, v2024.07.28
  DejaCharacterStats, vR110000r1
  Details, v#Details.12827.159
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DialogueUI, v0.3.6
  HandyNotes, vv1.6.20.3
  HandyNotesBattleForAzerothTreasures, vv32
  HandyNotesBurningCrusade, vv6
  HandyNotesDragonflightTreasures, vv60
  HandyNotesDragonGlyphs, v0.1.5
  HandyNotesHigherDimensionalLearning, vv6
  HandyNotesKosumoth, vv9
  HandyNotesLegionTreasures, vv35.1
  HandyNotesLongForgottenHippogryph, vv12
  HandyNotesMistsOfPandariaTreasures, vv33
  HandyNotesSecretFish, vv6
  HandyNotesShadowlandsTreasures, vv78
  HandyNotesStygia, vv110000.0
  HandyNotesSuramarLeylines, vv8
  HandyNotesSuramarTelemancy, vv13
  HandyNotesTreasureHunter, vv35
  HandyNotesWitheredArmyTraining, v1
  HandyNotesWrathOfTheLichKing, vv14
  Informant, v9.1.BETA.5.17 (OneMawTime)
  KrowiAchievementFilter, v75.2
  LeatrixMaps, v11.0.02
  LeatrixPlus, v11.0.02
  MasterPlanA, vA
  MinimalArchaeology, v11.0.0
  Narcissus, v1.6.7
  OmniCC, v11.0.0
  OPie, vZeta 8a
  Plumber, v1.3.3
  Postal, vv4.1.8
  PremadeGroupsFilter, v5.8.2
  RareScanner, v11.0.0.1
  Rarity, v1.0 (r733-release)
  RarityOptions, v
  SavedInstances, v11.0.2
  SpeedyAutoLoot, v2.2.21
  Stubby, v9.1.BETA.5.17 (OneMawTime)
  TomTom, vv4.0.1-release
  VenturePlan, v4.42
  WarPlan, v3.26
  WeakAuras, v5.15.4
  WeakAurasArchive, v5.15.4
  ZerethMortisPuzzleHelper, v1.6.13
  BlizRuntimeLib v11.0.0.55939(US) <enUS>
  (ck=a4f)

### Steps to reproduce

1. Take portal from Dalaran to Radiant Echo event (Searing Gorge was first I went to)
2. Do the event
3. Return via the in-game portal to Dalaran
4. Once loaded in, error gets thrown

---

Other variables that are present:

- level 60 Nelf DH freshly Gear Update'd
- accepted the first event quest from Dadgar
- accepted the daily quest in Searing Gorge
- killed Rag
- turned in daily (not quest from Dadgar)

**Comment by AMaribo** [comment]
Try disabling the BetterBags - GearFirst plugin and see if you still receive the error.

**Comment by ingham-tyler** [comment]
> Try disabling the BetterBags - GearFirst plugin and see if you still receive the error.

This has removed the error, or more accurately, not replicated the above error.

**Comment by AMaribo** [comment]
You'll need to reach out to the developer of that plugin with the error so they can take a look at it.

**Comment by ingham-tyler** [comment]
I will share this with them then, thank you for your help!
