### ISSUE TITLE
Vieuw gone in options

### ISSUE THREAD

**Issue by Chickiah** [Cidan/BetterBags#534]
### Addon Version

v0.1.89

### World of Warcraft Version

Retail

### Describe the bug

before i had adibags. but the addon stopped. i use betterbags now but before i had option to click vieuw -One bag - categorie but its gone. i dont know if its a bug or has it been put somewhere els?

i attached a picture from before and afther.

![Betterbags](https://github.com/user-attachments/assets/b85e85f8-f9b0-466d-92cd-6114a688988f)

### Steps to reproduce

i dont know, if it is a bug please fix it? 
i dont find i have the right to make demand anything

**Comment by AMaribo** [comment]
One Bag and List view were removed from BetterBags in v0.1.88 with the following note:
> Removed the One Bag and List views from BetterBags, as they were not well maintained and were more pet projects than anything. One Bag will return at a later date!
