### ISSUE TITLE
Search in russian language doesn't work

### ISSUE THREAD

**Issue by ivanguy** [Cidan/BetterBags#535]
### Addon Version

v0.1.89

### World of Warcraft Version

Retail

### Describe the bug

Search functionality doesn't work at all in russian language at least - doesn't highlight anything. 
![Screenshot 2024-08-04 121553](https://github.com/user-attachments/assets/03c3848f-3bb1-4757-912a-3c448156923f)

### Steps to reproduce

Change client language in the launcher - create character on a russian server and you can see it yourself

**Comment by T3tzu** [comment]
Search in Chinese does not work either.

**Comment by Cidan** [comment]
This is fixed in the latest alpha and will go out in the next release.
