### ISSUE TITLE
Bag draws too big for screen

### ISSUE THREAD

**Issue by Michael-Cooney** [Cidan/BetterBags#538]
### Addon Version

v0.1.89

### World of Warcraft Version

Retail

### Describe the bug

When there are many items and many categories in the bags, sometimes the needed real estate is larger than the screen.  When this happens, there is no way to access items off the bottom of the screen, even after pulling the bag windows to the very top of the screen.  Should have a scroll bar if it starts to near the screen size.

### Steps to reproduce

Fill every bag slot.
Turn on many categories and subcategories.
Set to only 2 columns.
Open bags.
Pull bags window up to top of screen.
Items at the bottom of the window should still be off the bottom of the screen.

**Comment by Cidan** [comment]
There will be no scroll bar, but I am working on a dynamic sizing system.

**Comment by Michael-Cooney** [comment]
Thanks!  By dynamic sizing, do you mean than icons will get smaller until the whole bag fits on the screen again?

**Comment by Cidan** [comment]
No, the bag column count will change such that more things fit across the screen.
