### ISSUE TITLE
Section labels truncated

### ISSUE THREAD

**Issue by FlyingDiver** [Cidan/BetterBags#54]
When there's only one item, the label is truncated.

![Screenshot 2023-12-04 155752](https://github.com/Cidan/BetterBags/assets/72976/e464fc85-ef1c-4f26-8c8d-4b290b89e9a0)

**Comment by Cidan** [comment]
Hm, noted. This will be complicated to solve correctly, so I may skip this for a bit, but let's keep this bug open to track it.

**Comment by FlyingDiver** [comment]
Edge case, I know.  Rare to only have one item in a gear set.

**Comment by Cidan** [comment]
Well really, any section with one item would cause this, so it should be fixed at some point.

**Comment by zeptognome** [comment]
Implemented as a config option to truncate or not
