### ISSUE TITLE
Bag Settings are not kept between logins

### ISSUE THREAD

**Issue by Pakka77** [Cidan/BetterBags#541]
### Addon Version

v0.1.89

### World of Warcraft Version

Retail

### Describe the bug

Bags do not keep settings between logouts. Multiple characters and servers.  Currencys are retained for settings.
![image](https://github.com/user-attachments/assets/892d823e-9cde-4219-bf1f-67436e4e9a63)
When I login, and check Show bags but goes back to this after I logout the character.
![image](https://github.com/user-attachments/assets/194d5e63-644b-4c4b-a614-46a8094957a4)
Pandaren Remix

### Steps to reproduce

Just Log out

**Comment by Cidan** [comment]
This is fixed in the latest alpha and will go out on next release.
