### ISSUE TITLE
Bag Themes

### ISSUE THREAD

**Issue by TheChadV1** [Cidan/BetterBags#547]
### Addon Version

11.0.0

### World of Warcraft Version

Retail

### Describe the bug

The bag themes are the same on all characters. If i change 1 theme it changes them all to that theme.
I noticed this when i change the theme to the characters Race, but it doesnt seem to stick its always the same theme for all of them.
A small bug but yea, still wanted to bring it up.

### Steps to reproduce

Change the theme then go to another character and change the them then go back. The themes change to the same one

**Comment by zeptognome** [comment]
All of BetterBags' settings, including theme, are part of a global profile at the moment.

Profile support is coming - you can watch #377 for updates
