### ISSUE TITLE
Search Based Categories: Last condition ignored

### ISSUE THREAD

**Issue by FvonY** [Cidan/BetterBags#548]
### Addon Version

0.1.89-6

### World of Warcraft Version

Retail

### Describe the bug

When creating a search based category with multiple conditions linked by OR, the last condition is not used, when those conditions are in brackets "()".

### Steps to reproduce

`equipmentLocation = back or equipmentLocation = feet` matches back and feet items. 
`(equipmentLocation = back or equipmentLocation = feet)` matches only back items. 
`(equipmentLocation = back or equipmentLocation = feet or equipmentLocation = feet)` matches back and feet items again.

**Comment by Cidan** [comment]
Fixed in the next alpha, thanks for the report!
