### ISSUE TITLE
I broke it

### ISSUE THREAD

**Issue by deathmessinger** [Cidan/BetterBags#55]
Just got 3 lua errors from BB 
I was creating the korthian gear from the tokens you can buy when the rest of the tokens disappeared 

1st: 1x BetterBags/util/sort.lua:75: attempt to compare two nil values
[string "@BetterBags/util/sort.lua"]:75: in function <BetterBags/util/sort.lua:72>
[string "=[C]"]: in function `sort'
[string "@BetterBags/frames/grid.lua"]:126: in function `Sort'
[string "@BetterBags/frames/section.lua"]:116: in function <BetterBags/frames/section.lua:115>
[string "=(tail call)"]: ?
[string "@BetterBags/views/gridview.lua"]:142: in function `GridView'
[string "@BetterBags/frames/bag.lua"]:184: in function `Draw'
[string "@BetterBags/core/init.lua"]:111: in function `cb'
[string "@BetterBags/core/events.lua"]:41: in function <BetterBags/core/events.lua:36>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:94: in function `SendMessage'
[string "@BetterBags/data/items.lua"]:132: in function <BetterBags/data/items.lua:126>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:83: in function `CheckIfSatisfied'
[string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:33: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:31>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:35: in function <FrameXML/ObjectAPI/AsyncCallbackSystem.lua:31>

Locals:
a = <table> {
 NormalTexture = BetterBagsItemButton21NormalTexture {
 }
 Stock = BetterBagsItemButton21Stock {
 }
 data = <table> {
 }
 masqueGroup = "Backpack"
 kind = 0
 ilvlText = FontString {
 }
 Count = BetterBagsItemButton21Count {
 }
 button = BetterBagsItemButton21 {
 }
 IconQuestTexture = BetterBagsItemButton21IconQuestTexture {
 }
 frame = Frame {
 }
 Cooldown = BetterBagsItemButton21Cooldown {
 }
 IconTexture = BetterBagsItemButton21IconTexture {
 }
}
b = <table> {
 NormalTexture = BetterBagsItemButton23NormalTexture {
 }
 Stock = BetterBagsItemButton23Stock {
 }
 data = <table> {
 }
 masqueGroup = "Backpack"
 kind = 0
 ilvlText = FontString {
 }
 Count = BetterBagsItemButton23Count {
 }
 button = BetterBagsItemButton23 {
 }
 IconQuestTexture = BetterBagsItemButton23IconQuestTexture {
 }
 frame = Frame {
 }
 Cooldown = BetterBagsItemButton23Cooldown {
 }
 IconTexture = BetterBagsItemButton23IconTexture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare two nil values"

2nd:1x BetterBags/views/gridview.lua:77: attempt to index local 'oldSection' (a nil value)
[string "@BetterBags/views/gridview.lua"]:77: in function `GridView'
[string "@BetterBags/frames/bag.lua"]:184: in function `Draw'
[string "@BetterBags/core/init.lua"]:111: in function `cb'
[string "@BetterBags/core/events.lua"]:41: in function <BetterBags/core/events.lua:36>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:94: in function `SendMessage'
[string "@BetterBags/data/items.lua"]:132: in function <BetterBags/data/items.lua:126>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:83: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:75>
[string "=(tail call)"]: ?
[string "@BetterBags/data/items.lua"]:126: in function `ProcessContainer'
[string "@BetterBags/data/items.lua"]:120: in function `RefreshBackpack'
[string "@BetterBags/data/items.lua"]:64: in function `RefreshAll'
[string "@BetterBags/data/items.lua"]:48: in function `cb'
[string "@BetterBags/core/events.lua"]:81: in function <BetterBags/core/events.lua:76>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 ListView = <function> defined @BetterBags/views/listview.lua:43
 SetEnabledState = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 UpdateListSize = <function> defined @BetterBags/views/listview.lua:27
 enabledState = false
 OneBagView = <function> defined @BetterBags/views/oneview.lua:23
 SetDefaultModuleState = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 moduleName = "Views"
 GetName = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "BetterBags_Views"
 SetDefaultModulePrototype = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 IsEnabled = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 GridView = <function> defined @BetterBags/views/gridview.lua:23
 DisableModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
bag = <table> {
 itemsByBagAndSlot = <table> {
 }
 sections = <table> {
 }
 isReagentBank = false
 kind = 0
 recentItems = <table> {
 }
 slots = <table> {
 }
 freeSlots = <table> {
 }
 freeReagentBagSlotsButton = <table> {
 }
 moneyFrame = <table> {
 }
 bottomBar = Frame {
 }
 freeBagSlotsButton = <table> {
 }
 frame = BetterBagsBagBackpack {
 }
 content = <table> {
 }
 resizeHandle = Button {
 }
}
dirtyItems = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table

3rd:1x BetterBags/views/gridview.lua:95: attempt to index local 'oldSection' (a nil value)
[string "@BetterBags/views/gridview.lua"]:95: in function `GridView'
[string "@BetterBags/frames/bag.lua"]:184: in function `Draw'
[string "@BetterBags/core/init.lua"]:111: in function `cb'
[string "@BetterBags/core/events.lua"]:41: in function <BetterBags/core/events.lua:36>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:94: in function `SendMessage'
[string "@BetterBags/data/items.lua"]:132: in function <BetterBags/data/items.lua:126>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:83: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:75>
[string "=(tail call)"]: ?
[string "@BetterBags/data/items.lua"]:126: in function `ProcessContainer'
[string "@BetterBags/data/items.lua"]:120: in function `RefreshBackpack'
[string "@BetterBags/data/items.lua"]:64: in function `RefreshAll'
[string "@BetterBags/data/items.lua"]:48: in function `cb'
[string "@BetterBags/core/events.lua"]:81: in function <BetterBags/core/events.lua:76>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 ListView = <function> defined @BetterBags/views/listview.lua:43
 SetEnabledState = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 UpdateListSize = <function> defined @BetterBags/views/listview.lua:27
 enabledState = false
 OneBagView = <function> defined @BetterBags/views/oneview.lua:23
 SetDefaultModuleState = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:383
 moduleName = "Views"
 GetName = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "BetterBags_Views"
 SetDefaultModulePrototype = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 IsEnabled = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 GridView = <function> defined @BetterBags/views/gridview.lua:23
 DisableModule = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
}
bag = <table> {
 itemsByBagAndSlot = <table> {
 }
 sections = <table> {
 }
 isReagentBank = false
 kind = 0
 recentItems = <table> {
 }
 slots = <table> {
 }
 freeSlots = <table> {
 }
 freeReagentBagSlotsButton = <table> {
 }
 moneyFrame = <table> {
 }
 bottomBar = Frame {
 }
 freeBagSlotsButton = <table> {
 }
 frame = BetterBagsBagBackpack {
 }
 content = <table> {
 }
 resizeHandle = Button {
 }
}
dirtyItems = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
 61 = <table> {
 }
 62 = <table> {
 }
 63 = <table> {
 }
 64 = <table> {
 }
 65 = <table> {
 }
 66 = <table> {
 }
 67 = <table> {
 }
 68 = <table> {
 }
 69 = <table> {
 }
 70 = <table> {
 }
 71 = <table> {
 }
 72 = <table> {
 }
 73 = <table> {
 }
 74 = <table> {
 }
 75 = <table> {
 }
 76 = <table> {
 }
 77 = <table> {
 }
 78 = <table

**Comment by Cidan** [comment]
Technically, I broke everything, not you :p

Pushing a fix for the sorting now -- but did this all happen back to back?

**Comment by deathmessinger** [comment]
yeah all three errors popped at the same time so I guess the second two could have been caused by the first one but figured you might want to see all three

**Comment by Cidan** [comment]
Alright they were probably related then. I'm closing this, as I did push a fix. If you see it again, please feel free to re-open this bug.

Thanks!
