### ISSUE TITLE
bag resets on reload or eeloig

### ISSUE THREAD

**Issue by fistdlanthus** [Cidan/BetterBags#553]
### Addon Version

v0.1.89

### World of Warcraft Version

Retail

### Describe the bug

when you reload or relog it resets how you changed your bag.  I prefer that i show my bags seperatly and hit the show bags button.  But after re-load or logging it changes it back to one bag and resets the position

### Steps to reproduce

reload or relog

**Comment by Cidan** [comment]
Fixed, but you really shouldn't play in this mode today as it may cause issues. I will be revisiting show bags later on, but fundamentally, you may have lag if you keep that view open.
