### ISSUE TITLE
[Feature]:  keep gear catgories together

### ISSUE THREAD

**Issue by N6REJ** [Cidan/BetterBags#554]
### Describe the feature

a member mentioned how she found it very frustrating that the gear was scattered alphabetically instead of each category being grouped next to another gear category.  I can understand what she means.

### Describe the implementation

So, we'd have a parent category "Gear" and then sub-categories of "feet", "wrist", "Chest" etc... all grouped within the "Gear" category.  I don't think the parent category name needs to display.  Just an internal grouping.

**Comment by juntereiner** [comment]
You can already do this with pinned category or with https://www.curseforge.com/wow/addons/betterbags-gear-first
