### ISSUE TITLE
v0.1.90 BetterBags/data/categories.lua:239: attempt to index local 'category' (a string value)

### ISSUE THREAD

**Issue by Louivatar** [Cidan/BetterBags#558]
### Addon Version

v0.1.90

### World of Warcraft Version

Retail

### Describe the bug

8x BetterBags/data/categories.lua:239: attempt to index local 'category' (a string value)
[string "@BetterBags/data/categories.lua"]:239: in function `CreateCategory'
[string "@BetterBags_Legendary/BetterBags_Legendary.lua"]:26: in main chunk

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "BetterBags_Categories"
 categoryCount = 0
 orderedModules = <table> {
 }
 categoryFunctions = <table> {
 }
 ephemeralCategories = <table> {
 }
 defaultModuleState = true
 baseName = "BetterBags"
 ephemeralCategoryByItemID = <table> {
 }
 enabledState = false
 moduleName = "Categories"
 itemsWithNoCategory = <table> {
 }
}
category = "Легендарки+"
(*temporary) = <table> {
 0 = true
 1 = true
}
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'category' (a string value)"
const = <table> {
 BANK_ONLY_BAGS = <table> {
 }
 BAG_KIND = <table> {
 }
 modules = <table> {
 }
 BANK_TAB = <table> {
 }
 BANK_BAGS = <table> {
 }
 WINDOW_KIND = <table> {
 }
 BANK_ONLY_BAGS_LIST = <table> {
 }
 BAG_SUBTYPES = <table> {
 }
 DATABASE_DEFAULTS = <table> {
 }
 SECTION_SORT_TYPE = <table> {
 }
 baseName = "BetterBags"
 name = "BetterBags_Constants"
 EQUIPMENT_SLOTS = <table> {
 }
 orderedModules = <table> {
 }
 TRADESKILL_MAP = <table> {
 }
 BRIEF_EXPANSION_MAP = <table> {
 }
 OFFSETS = <table> {
 }
 ITEM_QUALITY_COLOR = <table> {
 }
 EXPANSION_MAP = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 REAGENTBANK_BAGS = <table> {
 }
 ITEM_QUALITY_TO_ENUM = <table> {
 }
 ITEM_QUALITY_HIGHLIGHT = <table> {
 }
 BAG_SUBTYPE_TO_QUALITY = <table> {
 }
 EXPANSION_TYPE = <table> {
 }
 ITEM_SORT_TYPE = <table> {
 }
 defaultModuleState = true
 BAG_VIEW = <table> {
 }
 ITEM_QUALITY_COLOR_LOW = <table> {
 }
 BACKPACK_ONLY_BAGS_LIST = <table> {
 }
 enabledState = false
 BACKPACK_ONLY_REAGENT_BAGS = <table> {
 }
 ACCOUNT_BANK_BAGS = <table> {
 }
 GRID_COMPACT_STYLE = <table> {
 }
 BACKPACK_BAGS = <table> {
 }
 MOVEMENT_FLOW = <table> {
 }
 ITEM_BAG_FAMILY = <table> {
 }
 ITEM_QUALITY_COLOR_HIGH = <table> {
 }
 moduleName = "Constants"
 BACKPACK_ONLY_BAGS = <table> {
 }
}
database = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 data = <table> {
 }
 enabledState = true
 baseName = "BetterBags"
 defaultModuleLibraries = <table> {
 }
 name = "BetterBags_Database"
 orderedModules = <table> {
 }
 moduleName = "Database"
}
events = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "BetterBags_Events"
 orderedModules = <table> {
 }
 _eventArguments = <table> {
 }
 _eventQueue = <table> {
 }
 _bucketCallbacks = <table> {
 }
 _bucketTimers = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 _messageMap = <table> {
 }
 _eventHandler = <table> {
 }
 _eventMap = <table> {
 }
 moduleName = "Events"
 defaultModuleState = true
}

### Steps to reproduce

1. Just log in to the game

**Comment by Cidan** [comment]
This is written by a third party, BetterBags Legendary. Please reach out to that author.
