### ISSUE TITLE
[Feature]: Option to create category for each expansion

### ISSUE THREAD

**Issue by SiJiL82** [Cidan/BetterBags#560]
### Describe the feature

When creating custom categories, have the ability to automatically create multiple instances of the category, one for each expansion

### Describe the implementation

A "Create for each expansion" checkbox on the Create Category panel.
If checked, creates the category name you enter with a suffix of each expansion
For example, entering "Leather" would create:
Leather - Classic
Leather - The Burning Crusade
Leather - Wrath of the Lich King
Leather - Mists of Pandaria
etc.

Maybe 2 checkboxes - one for full expansion name, one for abbreviated expansion names (so it would create "Leather - TBC" etc.)

**Comment by Cidan** [comment]
This sort of group-by aggregation was considered, but will not come for a while. Until then, use the new search categories to achieve this.

**Comment by SiJiL82** [comment]
> This sort of group-by aggregation was considered, but will not come for a while. Until then, use the new search categories to achieve this.

I'm not sure how this relates to the request? Unless I'm missing something, it's not to do with grouping / aggregation, or something that can be achieved by searching?

I want to be able to speed up creating multiple categories.
For example, I have manually created these custom categories:
![image](https://github.com/user-attachments/assets/da90aacb-ab4d-418b-8bf2-873349b67c22)
To do this, I had to go to "Create Category" and enter "Cloth - Battle for Azeroth" and then click Okay, then enter "Cloth - Dragonflight" and click OK and so on.
The request was to just be able to enter "Cloth" in the "New Category Name" and have it automatically create "Cloth - Battle for Azeroth" and "Cloth - Dragonflight" (and a category for all the other expansions), rather than me manually doing t.

**Comment by Cidan** [comment]
> it's not to do with grouping / aggregation, or something that can be achieved by searching?

Sorry, group by aggregations is a common computer science term, mainly used in query systems. It means "take these results, and then group them by X field."

I understand what your request is, but right now, it's not on the roadmap. If it does come, it's going to be via search categories and not manual categories. You can still use search categories today to help some of this, i.e. `cloth and expansion = df` to make this a bit easier, but you still have to make a category named per each one manually.

Thanks!
