### ISSUE TITLE
Drag and drop to categories now broken

### ISSUE THREAD

**Issue by fraenhawk** [Cidan/BetterBags#561]
### Addon Version

v0.1.90

### World of Warcraft Version

Retail

### Describe the bug

Since upgrade to .90 if you drag an item to a custom category you get the tool tip to then press shift to drop, the tooltip then tells you to drop but clicking no longer puts the item in that category. Nothing happens. This had been working fine previously.

Workaround for now is to turn on the Configure Categories sidebar and drag to those instead.

### Steps to reproduce

1. Setup a custom category.
2. Add something to it from the Options screen so that it shows up in BetterBags
3. Drag another item to the category header - tooltip shows "Hold shift to add"
4. Hold down shift - tooltip shows "Drop"
5. click on header - nothing happens

![image](https://github.com/user-attachments/assets/3333fc3e-7498-48af-9569-e8640dc6639c)
![image](https://github.com/user-attachments/assets/11ef3c8a-4717-4f45-9855-01328637a452)

**Comment by Cidan** [comment]
Fixed in the next release, out later today.
