### ISSUE TITLE
items not staying in predefined catagories

### ISSUE THREAD

**Issue by Faulkal** [Cidan/BetterBags#565]
### Addon Version

v0.1.91-2-g894528b

### World of Warcraft Version

Retail

### Describe the bug

When i put https://www.wowhead.com/item=202096/armaments-of-the-scale in the storms fury category, upon reload it removes it from that category and puts it back under consumables. 

when i put https://www.wowhead.com/item=217243/awakening-ruby-wing in the Crests category, upon reload the item is removed and put back under miscellaneous category again. 

### Steps to reproduce

just a reload.

**Comment by Cidan** [comment]
if you have ephemeral categories supplied by another plugin, it'll get wiped on reload.

**Comment by Faulkal** [comment]
I’ll disable other plugins and retry. I’ll report my findings again soon

**Comment by Faulkal** [comment]
seemed to be a plugin like you said. ty!
