### ISSUE TITLE
Items not categorized correctly when adding via AddItemToCategory

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#570]
### Addon Version

v0.1.91

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

In my plugin for BetterBags I am using AddItemToCategory to add certain items to custom categores (for ItemRack) which was previously working but seems like it broke with the most recent update. Now I am seeing items in categories which are not in there (Interestingly they were previously, in case that is useful information)

However, this behavior is also inconsistent, since not every time the same items are being added to the same category. Noticed this when reloading occasionally

![grafik](https://github.com/user-attachments/assets/2375de82-0d0b-4706-afeb-c02eb4c00afc)
Example image shows bugged item list for category on the left (all custom categories added by my plugin look like this)
The highlighted items in the bag do not belong to this category as you can see the ItemRack UI on the right for comparison

In case you want to see the source code to clear things up: https://github.com/DJSchaffner/BetterBags_ItemRack/blob/main/main.lua

### Steps to reproduce

- Add items to custom category via plugin
- Check item list for category

**Comment by Cidan** [comment]
Fixed in alpha
