### ISSUE TITLE
Some items marked as key but are not keys

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#573]
### Addon Version

v0.1.91

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

Not sure if this is actually fixable on BetterBags end since I'm not sure where this categories gets read from, but "Atal'alarion's Enchanted Boulder" for example gets placed in the "Key" category but is not actually a key.

![grafik](https://github.com/user-attachments/assets/d993707c-2663-4e5c-aa6c-e56c02e81ec0)
Image of keyring for reference

Feel free to close this if it's a blizzard issue. It's also more of a minor inconvenience

### Steps to reproduce

- Acquire item
- Check items category

**Comment by Rafii2198** [comment]
They made is so cosmetic trinkets are not trinkets but usable keys, and as such are going to keyring, so they don't take up bag space, so probably only way is to create a custom category with these toy like keys

**Comment by DJSchaffner** [comment]
I think what you mean is this issue #572 
The item I mentioned here is not in the keyring but placed in the "Key" category.

See this picture for reference (Keyring is the same as original post):
![grafik](https://github.com/user-attachments/assets/17a6a6bd-201b-4265-9d5e-d3ff2c5dfe1a)

**Comment by AMaribo** [comment]
> See this picture for reference (Keyring is the same as original post): ![grafik](https://private-user-images.githubusercontent.com/16212271/357367129-17a6a6bd-201b-4265-9d5e-d3ff2c5dfe1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5Mzc1OTksIm5iZiI6MTcyMzkzNzI5OSwicGF0aCI6Ii8xNjIxMjI3MS8zNTczNjcxMjktMTdhNmE2YmQtMjAxYi00MjY1LTlkNWUtZDNmZjJjNWRmZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDIzMjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5Y2M4NTE5YTc3MzM2MjI0MzVhZGNkZWJiNjg5NWUwMzg0MDk0NTkwOWNjZDcyN2I2NjJjMWJkMGYwYWVhYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wrbTbCrKmqzmqQLgtncr8F920mS793eHiayZ5V7PeHQ)

Looking on [WoWHead](https://www.wowhead.com/classic/item=220635/atalalarions-enchanted-boulder), this item is classified under Items > Keys in the database. So it's a Blizzard classification issue.
