### ISSUE TITLE
[Feature]: Bag tabs for bank on classic???

### ISSUE THREAD

**Issue by Darnell8681** [Cidan/BetterBags#575]
### Describe the feature

Kind of like retail was hoping maybe we could get some bag tabs when banking like retail but in classic.  That way i can purchase new bag spots and add larger bags without having to always disabling the addon

### Describe the implementation

Ill eb honest same exact as retail would be great and i love how it is setup there.  I do play classic just as much as i do on retail.

**Comment by Cidan** [comment]
> that way i can purchase new bag spots and add larger bags without having to always disabling the addon

Click the menu for the bag -> show bags. this will show you your bag slots and you can buy and replace bags. this has been around for a very long time :)

**Comment by Darnell8681** [comment]
Oh goodness i am so sorry i have never seen that option there until now :( i feel so dumb thank you!!!!
