### ISSUE TITLE
Bank "category sell" defaults to main tab instead of active one

### ISSUE THREAD

**Issue by JH0Ni-github** [Cidan/BetterBags#578]
### Addon Version

v0.1.91

### World of Warcraft Version

Retail

### Describe the bug

Trying to deposit a category containing only crafting materials to reagent bank (tab open) by right clicking the category name. Instead of depositing to reagent bank they get sent to main bank.

### Steps to reproduce

1. Open reagent bank.
2. Right click mass deposit a reagent category from bags by clicking the category title.

**Comment by juntereiner** [comment]
It has been fixed in alpha.
