### ISSUE TITLE
[Feature]: Give Gearset categories priority over search categories

### ISSUE THREAD

**Issue by FvonY** [Cidan/BetterBags#586]
### Describe the feature

Currently search categories have priority over gearset categories. This can place items that are part of a gear set in a category, where you wouldn't expect them to be. 

To be blunt: I almost sold my best weapons, because I didn't expect them to be in my "weapons + shields" search category, when they are part of a gear set.

### Describe the implementation

Swap priority for this case, or maybe add a (negatable) search term that matches "is part of any gearset". I only managed to match gearsets with a known name.

**Comment by AMaribo** [comment]
Gearsets are currently all named `Gear: nameOfGearset`, so you can exclude them from searches by doing `not category = "gear:"`.

**Comment by Cidan** [comment]
As @AMaribo said, just exclude the gear categories from your own search category. Check the README for more information, as this is documented.

**Comment by FvonY** [comment]
I really should have RTFM...thanks!
