### ISSUE TITLE
Bag anchor in Screen Center and can't hide it

### ISSUE THREAD

**Issue by Dyrebear** [Cidan/BetterBags#588]
### Addon Version

v0.1.98

### World of Warcraft Version

Retail

### Describe the bug

I used /bbanchor to see the anchor. Now I can't get rid of it.
It's in the center of my screen.

### Steps to reproduce

use /bbanchor

**Comment by Cidan** [comment]
Does right clicking the anchor work?

**Comment by Cidan** [comment]
Just pushed a fix in .99, which is going out now. You'll have to type the slash command again (just once) and you'll be all set.
