### ISSUE TITLE
caps lock makes search fail!

### ISSUE THREAD

**Issue by brett1337** [Cidan/BetterBags#602]
### Addon Version

v.0.1.99

### World of Warcraft Version

Retail

### Describe the bug

Just type one single capital letter into the search bar and you'll see every single item is immediately blacked out from search! It's been like this for a week or two.

### Steps to reproduce

Type a letter S! shift-S or caps lock S doesn't matter as long as it is caps!

**Comment by AMaribo** [comment]
I can confirm. I am getting this bug, but only on bare word searches. Any capital letter in a bare word search returns no results.
Capital letters in `name = Feral` or `name %= Hide` both return the correct items.

**Comment by Cidan** [comment]
Fixed in next release.

**Comment by brett1337** [comment]
Ty dawg
