### ISSUE TITLE
[Feature]: Create Category from the bag "Configue Categories"

### ISSUE THREAD

**Issue by Nutrinoff** [Cidan/BetterBags#605]
### Describe the feature

Title is pretty self-explanatory.
It'd be nice to have a quick way of making categories from the "Configure Categories" that is attached to the bag, rather than go into the settings. The rest of the necessary stuff is already there for Categories (like item adding etc)
It's just a slog to create new categories on the fly by having to go into the settings every time.

### Describe the implementation

A button in configure categories, add a name, and hit enter. Just make a new custom with no items. 
OR
A button that opens a box to drag an item in in to make a new category

**Comment by zeptognome** [comment]
This exists. Drop an icon onto the corner bag icon to create a new category.

**Comment by Nutrinoff** [comment]
It'd probably be a good idea to explain that somewhere.... Because it's not explained when hovering the bag in the corner, nor in the "Create Category" in the options!

**Comment by zeptognome** [comment]
as a picture is worth more... you should see the message 'drop thing to create category'

![Screenshot 2024-03-18 023644](https://github.com/user-attachments/assets/e642b969-6419-45b1-8a5f-5c1b2e8e6c63)

**Comment by Nutrinoff** [comment]
Yeah, but it requires you to hold an item apparently! You might want to have a variant of that text for when you do NOT hold an item..... But glad it exists!

**Comment by zeptognome** [comment]
perhaps.. there is a section in the readme as well

https://github.com/Cidan/BetterBags/blob/main/README.md#manual-custom-categories

**Comment by Nutrinoff** [comment]
Sure... but you know aswell as i do that 9/10 addon users wouldn't read the readme.... :)
