### ISSUE TITLE
LUA error with latest version 

### ISSUE THREAD

**Issue by Andf** [Cidan/BetterBags#608]
### Addon Version

v0.2.1

### World of Warcraft Version

Retail

### Describe the bug

Getting random LUA error, not sure what is  triggering it:

4x [ADDON_ACTION_BLOCKED] AddOn 'BetterBags' tried to call the protected function 'BetterBagsBagBankTabContainerTab1default:Enable()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Enable'
[string "@BetterBags/frames/tabs.lua"]:251: in function `DeselectTab'
[string "@BetterBags/frames/tabs.lua"]:211: in function `SetTabByIndex'
[string "@BetterBags/frames/bag.lua"]:414: in function `SwitchToBankAndWipe'
[string "@BetterBags/core/hooks.lua"]:107: in function <BetterBags/core/hooks.lua:102>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:1849: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1848>
[string "=[C]"]: in function `securecall'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:1115: in function `CloseWindows'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:1129: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:1127>
[string "=[C]"]: in function `securecall'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:2853: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:2792>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

### Steps to reproduce

Unable to link it to a specific behaviour

**Comment by AMaribo** [comment]
This is fixed in v0.2.2

**Comment by Andf** [comment]
Thanks!
