### ISSUE TITLE
Redo the way recent items work

### ISSUE THREAD

**Issue by Cidan** [Cidan/BetterBags#61]
Right now, recent items is a special section that has a different code path for detecting when an item should go in that section, or if an item is in that section. This code should be moved into the GetCategory() code for items, such that it functions the same as any other category.

**Comment by Vhye76** [comment]
I would like to suggest adding the ability to disable the "recent items" grouping entirely; not as anything urgent, but it's a feature I find distracting.

**Comment by fubbleskag** [comment]
I'd second that. An option to choose between either a category just highlighting in the item's normal category, ideally.

**Comment by Cidan** [comment]
All features around Recent Items as noted have been implemented.
