### ISSUE TITLE
Attempted to add item 164254 to category Openable, but the item does not exist

### ISSUE THREAD

**Issue by Tovrin** [Cidan/BetterBags#622]
### Addon Version

v0.2.2-10-g619a012

### World of Warcraft Version

Retail

### Describe the bug

Bug captured in Bugsack:

3x BetterBags/data/categories.lua:140: Attempted to add item 164254 to category Openable, but the item does not exist.
[string "=[C]"]: in function `assert'
[string "@BetterBags/data/categories.lua"]:140: in function `AddItemToCategory'
[string "@betterbags-openable/Core.lua"]:23: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "Attempted to add item 164254 to category Openable, but the item does not exist."

### Steps to reproduce

It happens whenever I open the client.

**Comment by Cidan** [comment]
This is a bug with the Openable plugin, which is not written by us. Please reach out to that author.
