### ISSUE TITLE
[Feature]: Lock Items so they cannot be sold

### ISSUE THREAD

**Issue by Hirosashii** [Cidan/BetterBags#624]
### Describe the feature

Is there a possibility you could add functionality so that we could lock items so that they cannot be accidentally sold? There used to be an addon called ItemLock that did this that I believe is no longer supported. I'm not sure how difficult it would be to add said functionality, but I figured I'd ask.

### Describe the implementation

[Alt+Left Click] (or some configurable combination if need be) would add a little lock icon over the item's icon, and slightly grey out the item's icon.

**Comment by Cidan** [comment]
Anything that does this is a UI hack and does not prevent actual item selling. We implemented a feature like this a few months ago and deleted it, as it was really easy to work around. This is not on the roadmap today.
