### ISSUE TITLE
game freezes when hovering over items with TipTac Reborn enabled

### ISSUE THREAD

**Issue by yssaril** [Cidan/BetterBags#638]
### Addon Version

0.2.2

### World of Warcraft Version

Cataclysm

### Describe the bug

with TipTac Reborn (https://www.curseforge.com/wow/addons/tiptac-reborn) installed when hovering over items the game first starts to lag then freeze up. I have not had this issue with other bag addons or the default bags. It seams like BetterBags is updating the tooltip over and over again causing other addons that add info to lock up the game.

### Steps to reproduce

1. have tiptac reborn installed
2. hover mouse over several item
3. game starts to freeze

**Comment by Cidan** [comment]
BetterBags does not hook the tooltips for items in any way whatsoever. What you are seeing is the native game tooltip. Let me try this addon and see what's going on.

**Comment by Cidan** [comment]
I can confirm no events are firing on hover with tiptac enabled. You can confirm this yourself, type /bbdb, and look at the debug window which logs all events the bag fires and catches. I suggest reaching out to the tiptac authors.
