### ISSUE TITLE
Items drawing outside of frame when switching between Bank and Reagent bank

### ISSUE THREAD

**Issue by malkalen** [Cidan/BetterBags#64]
When I switch between the bank and reagent bank the items in the bank are becoming detached from the bank frame itself and have lost any groupings that they previously had. I can switch back to the reagent bank and it works fine but the bank tab remains broken.

The issue sometimes persists when closing and reopening the bank.

Initial open of bank:
![image](https://github.com/Cidan/BetterBags/assets/10790929/e57c4562-7bb3-4a8e-a405-e9d7e8e87a25)

Switch to reagent bank:
![image](https://github.com/Cidan/BetterBags/assets/10790929/bc545d63-58bc-49d7-85a1-1219531587f4)

Switch bank to bank:
![image](https://github.com/Cidan/BetterBags/assets/10790929/fe1752fe-2a48-48b8-8bdd-7b2d4431885f)

After moving bank frame:
![image](https://github.com/Cidan/BetterBags/assets/10790929/6705b5d1-d877-49b5-96df-e2b0d64c10e5)

Switch back to reagent bank:
![image](https://github.com/Cidan/BetterBags/assets/10790929/074c1fc8-1069-45ca-869c-394c18641a26)

**Comment by Cidan** [comment]
Thank you for the report! I just pushed version .75 which fixes this. It should be on curse in a few minutes, and on Github/Wago right now :)
