### ISSUE TITLE
Catagories.lua

### ISSUE THREAD

**Issue by Topcat357** [Cidan/BetterBags#640]
### Addon Version

v0.2.2

### World of Warcraft Version

Retail

### Describe the bug

When loading into the game.
14x BetterBags/data/categories.lua:140: Attempted to add item 176004 to category SL.Consumables, but the item does not exist.
[string "=[C]"]: in function `assert'
[string "@BetterBags/data/categories.lua"]:140: in function `AddItemToCategory'
[string "@Betterbags_Shadowlands/main.lua"]:12: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "Attempted to add item 176004 to category SL.Consumables, but the item does not exist."

### Steps to reproduce

Log In

**Comment by AMaribo** [comment]
This is a bug in the `Betterbags_Shadowlands` plugin. They are attempting to add an invalid item `176004` into the list of items. You'll need to reach out to the developer of that plugin to report the issue.
