### ISSUE TITLE
[Feature]: "Question about categories"

### ISSUE THREAD

**Issue by Sirkgust** [Cidan/BetterBags#643]
### Describe the feature

How to have categories for weapons/armor, rather than specific categories for each piece of gear.

### Describe the implementation

Something I liked about AdiBags was that it divided gear into categories like weapons, armor, and then items like neck pieces, rings, or trinkets. Since I've been using BetterBags, it's divided into very detailed categories like ranged weapons, two-handed weapons, neck, rings, shoulders, etc. Honestly, I don't like that level of detail for my case. How can I switch to something less detailed? Sorry if I didn’t know how to classify this, as it only allows me to report an error or suggest a new option. The solution might be simple, but due to my visual issues, making adjustments requires taking photos and zooming in to figure out where to adjust, so I’m asking to know specifically where to make changes. Besides that, thanks for the addon—I liked it with AdiBags and I still like it now.

**Comment by AMaribo** [comment]
You can create some new search based categories, such as `(type = weapon or slot %= 'off hand' or slot %= 'held in') and not category = 'gear:'` to find all weapons, shields, and held in off hand items, but not any pieces of gear in gearsets. The Readme has some more information about the things that can be searched.
