### ISSUE TITLE
too many errors

### ISSUE THREAD

**Issue by S1lverone** [Cidan/BetterBags#646]
### Addon Version

11.0.2

### World of Warcraft Version

Retail

### Describe the bug

82x BetterBags_Renamer/locale/enUs.lua:42: attempt to call method 'S' (a nil value)
[string "@BetterBags_Renamer/locale/enUs.lua"]:42: in main chunk

Locals:
BetterBags = <table> {
 isBCC = false
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 defaultModuleState = false
 _bindingFrame = Frame {
 }
 baseName = "BetterBags"
 name = "BetterBags"
 orderedModules = <table> {
 }
 backpackShouldClose = false
 isRetail = true
 backpackShouldOpen = false
 Bags = <table> {
 }
 atBank = false
 enabledState = true
 atWarbank = false
 isClassic = false
 hooks = <table> {
 }
 isCata = false
 _buttons = <table> {
 }
}
L = <table> {
 data = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 locale = "enUS"
 moduleName = "Localization"
 defaultModuleState = true
 name = "BetterBags_Localization"
 orderedModules = <table> {
 }
}
generalStrings = <table> {
 Select Category = "Select Category"
 Developer = "Developer"
 AdiBags Importer = "AdiBags Importer"
 New Name = "New Name"
 Check Out My Other BetterBags Plugins = "Check Out My Other BetterBags Plugins"
 Category Renamer = "Category Renamer"
 Version = "Version"
 Date = "Date"
 GitHub = "GitHub"
 Support = "Support"
 Rename = "Rename"
 About = "About"
}
descriptions = <table> {
 Select the category to rename = "Select the category to rename"
 If you find any issues with the plugin, please submit an issue on the projects GitHub page. = "If you find any issues with the plugin, please submit an issue on the projects GitHub page."
 Custom categories that are manually created are only allowed to be renamed.

If a category is missing from the list below, it means that its either created by BetterBags itself or an installed plugin. = "Custom categories that are manually created are only allowed to be renamed.

If a category is missing from the list below, it means that its either created by BetterBags itself or an installed plugin."
 BetterBags - Renamer: Successfully Renamed '%s' to '%s' = "BetterBags - Renamer: Successfully Renamed '%s' to '%s'"
 Enter the new name you want for the selected category = "Enter the new name you want for the selected category"
}
errors = <table> {
 Attempted to call RenameCategory on a category that doesn't exist = "Attempted to call RenameCategory on a category that doesn't exist"
 Error: A category with this name already exists. = "Error: A category with this name already exists."
}
(for state) = <table> {
 Select Category = "Select Category"
 Developer = "Developer"
 AdiBags Importer = "AdiBags Importer"
 New Name = "New Name"
 Check Out My Other BetterBags Plugins = "Check Out My Other BetterBags Plugins"
 Category Renamer = "Category Renamer"
 Version = "Version"
 Date = "Date"
 GitHub = "GitHub"
 Support = "Support"
 Rename = "Rename"
 About = "About"
}
(for control) = "Select Category"
key = "Select Category"
value = "Select Category"
(*temporary) = nil
(*temporary) = <table> {
 data = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 locale = "enUS"
 moduleName = "Localization"
 defaultModuleState = true
 name = "BetterBags_Localization"
 orderedModules = <table> {
 }
}
(*temporary) = "Select Category"
(*temporary) = "Select Category"
(*temporary) = "attempt to call method 'S' (a nil value)"

### Steps to reproduce

logging into the game

**Comment by S1lverone** [comment]
125x ...ceBetterBags_AdiBagsImporter/locale/enUs.lua:46: attempt to call method 'S' (a nil value)
[string "@BetterBags_AdiBagsImporter/locale/enUs.lua"]:46: in main chunk

Locals:
BetterBags = <table> {
 isBCC = false
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 defaultModuleState = false
 _bindingFrame = Frame {
 }
 baseName = "BetterBags"
 name = "BetterBags"
 orderedModules = <table> {
 }
 backpackShouldClose = false
 isRetail = true
 backpackShouldOpen = false
 Bags = <table> {
 }
 atBank = false
 enabledState = true
 atWarbank = false
 isClassic = false
 hooks = <table> {
 }
 isCata = false
 _buttons = <table> {
 }
}
L = <table> {
 data = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 locale = "enUS"
 moduleName = "Localization"
 defaultModuleState = true
 name = "BetterBags_Localization"
 orderedModules = <table> {
 }
}
generalStrings = <table> {
 Developer = "Developer"
 Warning! = "Warning!"
 AdiBags Importer = "AdiBags Importer"
 Enable AdiBags = "Enable AdiBags"
 Import = "Import"
 Check Out My Other BetterBags Plugins = "Check Out My Other BetterBags Plugins"
 Version = "Version"
 GitHub = "GitHub"
 Undo = "Undo"
 Support = "Support"
 Date = "Date"
 About = "About"
}
descriptions = <table> {
 Enter the separator to use between Category and Sub-Category = "Enter the separator to use between Category and Sub-Category"
 Import your AdiBags custom filters into BetterBags = "Import your AdiBags custom filters into BetterBags"
 If enabled, only the Sub-Category will be used for the category name = "If enabled, only the Sub-Category will be used for the category name"
 AdiBags is installed but disabled. Please enable it and reload the UI. = "AdiBags is installed but disabled. Please enable it and reload the UI."
 If you find any issues with the plugin, please submit an issue on the projects GitHub page. = "If you find any issues with the plugin, please submit an issue on the projects GitHub page."
 No import to undo. = "No import to undo."
 Successfully imported %d AdiBags categories into BetterBags. = "Successfully imported %d AdiBags categories into BetterBags."
 AdiBags not detected! The functionality of this module will be disabled. = "AdiBags not detected! The functionality of this module will be disabled."
 Undo successful. Reverted imported items and categories. = "Undo successful. Reverted imported items and categories."
 AdiBags configuration not found! = "AdiBags configuration not found!"
}
errors = <table> {
 AdiBags Importer Warning: Attempted to import item '%d' but the item does not exist. Item import was skipped. = "AdiBags Importer Warning: Attempted to import item '%d' but the item does not exist. Item import was skipped."
 Error: Selected profile does not have any overrides! = "Error: Selected profile does not have any overrides!"
}
(for state) = <table> {
 Developer = "Developer"
 Warning! = "Warning!"
 AdiBags Importer = "AdiBags Importer"
 Enable AdiBags = "Enable AdiBags"
 Import = "Import"
 Check Out My Other BetterBags Plugins = "Check Out My Other BetterBags Plugins"
 Version = "Version"
 GitHub = "GitHub"
 Undo = "Undo"
 Support = "Support"
 Date = "Date"
 About = "About"
}
(for control) = "Developer"
key = "Developer"
value = "Developer"
(*temporary) = nil
(*temporary) = <table> {
 data = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 locale = "enUS"
 moduleName = "Localization"
 defaultModuleState = true
 name = "BetterBags_Localization"
 orderedModules = <table> {
 }
}
(*temporary) = "Developer"
(*temporary) = "Developer"
(*temporary) = "attempt to call method 'S' (a nil value)"

**Comment by AMaribo** [comment]
The first error is coming from `BetterBags - AdiBags Importer` and the other error is coming from `BetterBags - Renamer`. You'll need to reach out to the author of these 2 plugins to let them know about the error.
