### ISSUE TITLE
Don't close Section Categories on every click

### ISSUE THREAD

**Issue by FlyingDiver** [Cidan/BetterBags#65]
It would be nice if the menu didn't close on every click.  Enabling or disabling multiple custom categories is a pain.

**Comment by Cidan** [comment]
This has been a mental to-do for a while now -- thanks for adding this, I'll make the change tonight.

Generally speaking, I want to change a lot about the config process, but not yet.

**Comment by jomoroon** [comment]
Tmog status
![image](https://github.com/Cidan/BetterBags/assets/43888664/dbd2d1a4-857b-4192-a288-2946fe013c2e)

![image](https://github.com/Cidan/BetterBags/assets/43888664/20d1da0c-2bf4-4e67-b71a-6139b4add633)

**Comment by FlyingDiver** [comment]
@jomoroon What do those images have to do with this issue?

**Comment by Cidan** [comment]
I think they posted the image to the wrong issue. I deleted it.

Additionally, this issue has been fixed for categories specifically. I may evaluate it for other things over time.
