### ISSUE TITLE
Sorting error

### ISSUE THREAD

**Issue by Sathorn** [Cidan/BetterBags#651]
### Addon Version

v0.2.2

### World of Warcraft Version

Retail

### Describe the bug

`Message: Interface/AddOns/BetterBags/frames/grid.lua:165: invalid order function for sorting
Time: Sat Aug 31 13:12:01 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/grid.lua:165: invalid order function for sorting
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/BetterBags/frames/grid.lua"]:165: in function `Sort'
[string "@Interface/AddOns/BetterBags/views/gridview.lua"]:278: in function `Render'
[string "@Interface/AddOns/BetterBags/frames/bag.lua"]:304: in function `Draw'
[string "@Interface/AddOns/BetterBags/core/init.lua"]:266: in function `cb'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:50: in function <Interface/AddOns/BetterBags/core/events.lua:45>
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:186: in function <Interface/AddOns/BetterBags/core/events.lua:185>

Locals: (*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 maxItemsPerRow = 11
 content = <table> {
 }
 frame = Frame {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 maxItemsPerRow = 11
 content = <table> {
 }
 frame = Frame {
 }
}
`

### Steps to reproduce

Everytime I am clicking sorting option it result in error

**Comment by AMaribo** [comment]
Do you have either `BetterBags - BetterSort` or `BetterBags - Gear First` installed alongside BetterBags?

**Comment by Sathorn** [comment]
Nope, there you have my list
![image](https://github.com/user-attachments/assets/b6827f51-feb4-4948-9818-f09321e59f57)

**Comment by Sathorn** [comment]
Oh I didn't notice, gear first

**Comment by AMaribo** [comment]
Try disabling `Gear First` and seeing if you still receive the error. If you do not, you'll need to reach out to the author of the `Gear First` plugin to let them know about the error.

**Comment by Sathorn** [comment]
seems ok, after I did block Gear First - If this will happen again I will let you know. To be closed I suppose.

**Comment by AMaribo** [comment]
You can reach out to the author of Gear First with the error to report it.
