### ISSUE TITLE
Portioned Steak is not in Cooking category

### ISSUE THREAD

**Issue by sean-kang** [Cidan/BetterBags#657]
### Addon Version

v0.2.2

### World of Warcraft Version

Retail

### Describe the bug

Portioned Steak is in the Consumable category although it is not a consumable item. It should be in the Cooking category since it is a crafting reagent.

### Steps to reproduce

1. Portioned Steak can be crafted through Cooking skill. You can craft it with the level 1 cooking skill.
2. Open the bag when you have a Portioned Steak.
3. You will see the item in the Consumable category instead of the Cooking category.

**Comment by AMaribo** [comment]
This is a categorization error on Blizzard's side. WoWHead shows that it is indeed in the `Consumables - Food & Drink` category instead of the `Trade Goods - Cooking` like it probably should be.

You will need to manually put it into the category that you want it to be in.

**Comment by N6REJ** [comment]
Since its a vendor item shouldn't it go under "Vendor" ?

**Comment by N6REJ** [comment]
@sean-kang I added it, didn't realize it was a reagent.  Wowhead-db is messed up.
