### ISSUE TITLE
With the new categories placement, you can't create new categories

### ISSUE THREAD

**Issue by lukzmu** [Cidan/BetterBags#663]
### Addon Version

v0.3.6

### World of Warcraft Version

Retail

### Describe the bug

When the categories were moved from the options screen to the bags "configure categories" you can only edit the existing categories. There is no "new" button to create new custom categories.

### Steps to reproduce

1. Open bags,
2. Click "Configure Categories",
3. ...
4. Profit.

**Comment by AMaribo** [comment]
Drag and item to the bag icon in the top left corner of the bag to create a new category.

**Comment by AMaribo** [comment]
There are some reference images here.
https://github.com/Cidan/BetterBags?tab=readme-ov-file#manual-custom-categories
