### ISSUE TITLE
Can't load - BetterBags/core/async.lua:49 Error

### ISSUE THREAD

**Issue by Reckless-WoW-Player** [Cidan/BetterBags#665]
### Addon Version

v0.3.9

### World of Warcraft Version

Retail

### Describe the bug

Lua error pops up when I log in. Here's the Error.

8x BetterBags/core/async.lua:49: Blizzard_ObjectAPI/Mainline/Item.lua:121: bad argument #1 to 'GetItemGUID' (Usage: local itemGUID = C_Item.GetItemGUID(itemLocation))
[string "=[C]"]: in function `error'
[string "@BetterBags/core/async.lua"]:49: in function <BetterBags/core/async.lua:46>

Locals:
(*temporary) = "Blizzard_ObjectAPI/Mainline/Item.lua:121: bad argument #1 to 'GetItemGUID' (Usage: local itemGUID = C_Item.GetItemGUID(itemLocation))"

### Steps to reproduce

Log into a character

**Comment by AMaribo** [comment]
Revert to v0.3.7 for now.

**Comment by Reckless-WoW-Player** [comment]
Ok, thank you

**Comment by AMaribo** [comment]
I'm reopening this issue to track the error until it is resolved.

**Comment by AMaribo** [comment]
This is fixed in v0.3.10.
