### ISSUE TITLE
Bag broken

### ISSUE THREAD

**Issue by Aealm** [Cidan/BetterBags#666]
### Addon Version

v0.3.9

### World of Warcraft Version

Retail

### Describe the bug

Bag shows no items, and it is compressed. All I can see is the currency but they're on top of each other.

6x BetterBags/core/async.lua:49: Blizzard_ObjectAPI/Mainline/Item.lua:121: bad argument #1 to 'GetItemGUID' (Usage: local itemGUID = C_Item.GetItemGUID(itemLocation))
[string "=[C]"]: in function `error'
[string "@BetterBags/core/async.lua"]:49: in function `worker'
[string "@BetterBags/core/async.lua"]:65: in function `DoWithDelay'
[string "@BetterBags/core/async.lua"]:74: in function `Do'
[string "@BetterBags/core/async.lua"]:102: in function `Batch'
[string "@BetterBags/data/loader.lua"]:111: in function `Load'
[string "@BetterBags/data/items.lua"]:799: in function `ProcessContainer'
[string "@BetterBags/data/items.lua"]:515: in function `RefreshBackpack'
[string "@BetterBags/data/refresh.lua"]:144: in function `StartUpdate'
[string "@BetterBags/data/refresh.lua"]:227: in function `cb'
[string "@BetterBags/core/events.lua"]:49: in function <BetterBags/core/events.lua:47>
[string "=[C]"]: ?

### Steps to reproduce

Just opening the bag

**Comment by AMaribo** [comment]
This is a known issue currently. Revert to v0.3.7 for now.
