### ISSUE TITLE
LUA Error after Update Today

### ISSUE THREAD

**Issue by Xarl** [Cidan/BetterBags#669]
### Addon Version

v0.3.9

### World of Warcraft Version

Retail

### Describe the bug

After logging in, I get this Lua Error and my Bag Shows Empty:

`Message: Interface/AddOns/BetterBags/core/async.lua:49: ...nterface/AddOns/Blizzard_ObjectAPI/Mainline/Item.lua:121: bad argument #1 to 'GetItemGUID' (Usage: local itemGUID = C_Item.GetItemGUID(itemLocation))
Time: Tue Sep  3 18:00:33 2024
Count: 1
Stack: Interface/AddOns/BetterBags/core/async.lua:49: ...nterface/AddOns/Blizzard_ObjectAPI/Mainline/Item.lua:121: bad argument #1 to 'GetItemGUID' (Usage: local itemGUID = C_Item.GetItemGUID(itemLocation))
[string "@Interface/AddOns/BetterBags/core/async.lua"]:49: in function `worker'
[string "@Interface/AddOns/BetterBags/core/async.lua"]:65: in function `DoWithDelay'
[string "@Interface/AddOns/BetterBags/core/async.lua"]:74: in function `Do'
[string "@Interface/AddOns/BetterBags/core/async.lua"]:102: in function `Batch'
[string "@Interface/AddOns/BetterBags/data/loader.lua"]:111: in function `Load'
[string "@Interface/AddOns/BetterBags/data/items.lua"]:799: in function `ProcessContainer'
[string "@Interface/AddOns/BetterBags/data/items.lua"]:515: in function `RefreshBackpack'
[string "@Interface/AddOns/BetterBags/data/refresh.lua"]:144: in function `StartUpdate'
[string "@Interface/AddOns/BetterBags/data/refresh.lua"]:227: in function `cb'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:49: in function <Interface/AddOns/BetterBags/core/events.lua:47>
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
...
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:96: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:89: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:84: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:76: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:72>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals: success = false
err = "...nterface/AddOns/Blizzard_ObjectAPI/Mainline/Item.lua:121: bad argument #1 to 'GetItemGUID' (Usage: local itemGUID = C_Item.GetItemGUID(itemLocation))"
task = <table> {
 ctx = <table> {
 }
 thread = <no value>
}
events = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "BetterBags_Events"
 orderedModules = <table> {
 }
 _eventArguments = <table> {
 }
 _bucketCallbacks = <table> {
 }
 _bucketTimers = <table> {
 }
 _eventQueue = <table> {
 }
 _messageMap = <table> {
 }
 _eventHandler = <table> {
 }
 enabledState = true
 baseName = "BetterBags"
 _eventMap = <table> {
 }
 moduleName = "Events"
 defaultModuleState = true
}
delay = 0
`

### Steps to reproduce

Just Log In...

**Comment by Zazou89** [comment]
Please update to the latest verison : https://github.com/Cidan/BetterBags/releases/tag/v0.3.10

**Comment by Xarl** [comment]
> Please update to the latest verison : https://github.com/Cidan/BetterBags/releases/tag/v0.3.10

Thats what I did and got that Lua Error

**Comment by woodrikj** [comment]
My bags are completely gone after the update

**Comment by AMaribo** [comment]
You are on v0.3.9. v0.3.10 has been released (still waiting for Curse to update, I guess) and resolves this issue.

**Comment by Xarl** [comment]
> You are on v0.3.9. v0.3.10 has been released (still waiting for Curse to update, I guess) and resolves this issue.

Ok your Right it must be Curse for some reason.
Used the Link for the Update above and all working again.

**Comment by Zazou89** [comment]
v0.3.10 is now available on Curse.
