### ISSUE TITLE
Bag won't open at Item Upgrade vendor

### ISSUE THREAD

**Issue by FlyingDiver** [Cidan/BetterBags#67]
If bag frame is open before interacting with the NPC (Ezra in Valdrakken), all works fine.

But if you interact with the NPC first (getting the Item Upgrade window), then the Open All Bags keybind doesn't work.  The window frame flashes on the screen, but doesn't stay open.  Clicking on one of the bags in the bag bar does work.

It's a weird one.

**Comment by Cidan** [comment]
Weird indeed, I'll check this shortly.

**Comment by Cidan** [comment]
Fixed in latest release!
