### ISSUE TITLE
Invalid order function for sorting

### ISSUE THREAD

**Issue by Daeadin** [Cidan/BetterBags#673]
### Addon Version

v0.3.10

### World of Warcraft Version

Retail

### Describe the bug

Message: Interface/AddOns/BetterBags/frames/grid.lua:242: invalid order function for sorting
Time: Tue Sep  3 14:13:43 2024
Count: 1
Stack: Interface/AddOns/BetterBags/frames/grid.lua:242: invalid order function for sorting
[string "@Interface/AddOns/BetterBags/frames/grid.lua"]:242: in function `Sort'
[string "@Interface/AddOns/BetterBags/views/gridview.lua"]:354: in function `Render'
[string "@Interface/AddOns/BetterBags/frames/bag.lua"]:316: in function `Draw'
[string "@Interface/AddOns/BetterBags/core/init.lua"]:274: in function `cb'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:49: in function <Interface/AddOns/BetterBags/core/events.lua:47>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:206: in function `SendMessage'
[string "@Interface/AddOns/BetterBags/core/events.lua"]:224: in function <Interface/AddOns/BetterBags/core/events.lua:223>

Locals: self = <table> {
 view = <table> {
 }
 sortVertical = true
 columns = <table> {
 }
 spacing = 4
 cells = <table> {
 }
 footers = <table> {
 }
 maxCellWidth = 2
 box = BetterBagsScrollGrid0 {
 }
 headers = <table> {
 }
 cellToColumn = <table> {
 }
 idToCell = <table> {
 }
 compactStyle = 0
 inner = Frame {
 }
 frame = BetterBagsScrollGrid0 {
 }
 cellToID = <table> {
 }
 bar = Frame {
 }
}

### Steps to reproduce

Occurs on load

**Comment by AMaribo** [comment]
Do you have `BetterBags - GearFirst` or `BetterBags - BetterSort` installed?

**Comment by Daeadin** [comment]
Yes, I have BetterBags - GearFirst installed.  I have disabled it for now, and error went away as described.
