### ISSUE TITLE
LUA Error looking at cateogires

### ISSUE THREAD

**Issue by kcoderhere** [Cidan/BetterBags#681]
### Addon Version

v0.3.12

### World of Warcraft Version

Retail

### Describe the bug

Date: 2024-09-04 11:01:43
ID: 1
Error occured in: Global
Count: 115
Message: Interface/AddOns/BetterBags/frames/item.lua line 301:
   bad argument #1 to 'DoesItemExist' (Usage: local itemExists = C_Item.DoesItemExist(emptiableItemLocation))
Debug:
   [string "=[C]"]: DoesItemExist()
   [string "@Interface/AddOns/BetterBags/frames/item.lua"]:301: GetItemContextMatchResult()
   [string "@Interface/AddOns/Blizzard_ItemButton/Mainline/ItemButtonTemplate.lua"]:462: UpdateItemContextMatching()
   [string "@Interface/AddOns/BetterBags/frames/item.lua"]:383: SetItemFromData()
   [string "@Interface/AddOns/BetterBags/frames/item.lua"]:285: SetStaticItemFromData()
   [string "@Interface/AddOns/BetterBags/frames/itemrow.lua"]:76: SetItemFromData()
   [string "@Interface/AddOns/BetterBags/frames/itemrow.lua"]:59: SetStaticItemFromData()
   [string "@Interface/AddOns/BetterBags/frames/sectionitemlist.lua"]:147:
      ...terface/AddOns/BetterBags/frames/sectionitemlist.lua:146
   [string "@Interface/AddOns/BetterBags/data/items.lua"]:847:
      Interface/AddOns/BetterBags/data/items.lua:839
   [string "=[C]"]: xpcall()
   [string "@Interface/AddOns/Blizzard_ObjectAPI/Mainline/ContinuableContainer.lua"]:83:
      ...Blizzard_ObjectAPI/Mainline/ContinuableContainer.lua:75
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/BetterBags/data/items.lua"]:839: GetItemData()
   [string "@Interface/AddOns/BetterBags/frames/sectionitemlist.lua"]:146: initSectionItem()
   [string "@Interface/AddOns/BetterBags/frames/sectionitemlist.lua"]:234: initializer()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:372: InvokeInitializer()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:390:
      ...izzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua:389
   [string "=[C]"]: secureexecuterange()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:393: InvokeInitializers()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:712: Update()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:168: FullUpdateInternal()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:682: FullUpdateInternal()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:122: FullUpdate()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:653:
      ...ddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua:652
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144:
      ...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: TriggerEvent()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:317: SignalDataChangeEvent()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:312: DataProviderContentsChanged()
   [string "@Interface/AddOns/Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:303:
      ...izzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua:300
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144:
      ...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: TriggerEvent()
   [string "@Interface/AddOns/Blizzard_SharedXML/DataProvider.lua"]:68: InsertAtIndex()
   [string "@Interface/AddOns/BetterBags/frames/list.lua"]:49: AddToStart()
   [string "@Interface/AddOns/BetterBags/frames/sectionitemlist.lua"]:202: ShowCategory()
   [string "@Interface/AddOns/BetterBags/frames/sectionconfig.lua"]:149:
      Interface/AddOns/BetterBags/frames/sectionconfig.lua:133

### Steps to reproduce

Click the bag in the upper-left, Configure Categories, select a category

**Comment by zeptognome** [comment]
PR #684 should fix this

**Comment by zeptognome** [comment]
merged in BetterBags v0.3.14
