### ISSUE TITLE
Everything in bag disappears

### ISSUE THREAD

**Issue by Adnoxx1** [Cidan/BetterBags#683]
### Addon Version

v0.3.12

### World of Warcraft Version

Retail

### Describe the bug

Items in Bag Disappear. takes a few reloads or reinstalls to bring items back. Been happening for past couple days. I couldn't find any solutions to this. 
![image](https://github.com/user-attachments/assets/66b5dcc2-cc64-4ff6-911c-e79486c1d549)
![image](https://github.com/user-attachments/assets/481fca49-a1b0-4fa9-8e84-8a6a6697357f)

### Steps to reproduce

 Been random such as selling items or hit the sort bag button

**Comment by zeptognome** [comment]
The most common cause of this recently is a plugin that has not been updated to support BetterBags v0.3.x
A bugsack/bug grabber report would help, but you might try turning off all BetterBags plugins to find the trigger.

**Comment by Adnoxx1** [comment]
3x BetterBags/frames/grid.lua:242: invalid order function for sorting
[string "=[C]"]: in function `sort'
[string "@BetterBags/frames/grid.lua"]:242: in function `Sort'
[string "@BetterBags/views/gridview.lua"]:359: in function `Render'
[string "@BetterBags/frames/bag.lua"]:316: in function `Draw'
[string "@BetterBags/core/init.lua"]:274: in function `cb'
[string "@BetterBags/core/events.lua"]:49: in function <BetterBags/core/events.lua:47>
[string "=[C]"]: ?
[string "@Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...er4/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:206: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:224: in function <BetterBags/core/events.lua:223>

Locals:
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 maxItemsPerRow = 7
 content = <table> {
 }
 frame = Frame {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 maxItemsPerRow = 7
 content = <table> {
 }
 frame = Frame {
 }
}

Heres the bug grabber report also found out its the war within plugin

**Comment by zeptognome** [comment]
> its the war within plugin

You'll need to reach out to that plugin author for a fix
