### ISSUE TITLE
Right click to sort not working

### ISSUE THREAD

**Issue by CommPic** [Cidan/BetterBags#698]
### Addon Version

v0.3.16

### World of Warcraft Version

Retail

### Describe the bug

When I right click on the icon in the upper right to sort bags nothing happens

### Steps to reproduce

1. open bag
2. right click the bag icon in upper right

**Comment by Cidan** [comment]
Sorting will only put reagent items into the reagent bag, and re-stack items that are split. It will not sort the bags under the hood at the moment, as this is generally not useful and wastes frames/makes the game lag when you do this.

In the near future, I will be adding a "also sort bag slots" feature as well.
