### ISSUE TITLE
Items not showing in the bag

### ISSUE THREAD

**Issue by r0xp0x** [Cidan/BetterBags#708]
### Addon Version

v0.3.16

### World of Warcraft Version

Retail

### Describe the bug

Randomly when I'm opening the bag, it's just all blank. Doing a single /reload works sometimes, but quite often I have to to several /reload for the items to show again.
After a /reload the window looks like this when I try to open the bag the first time: 
![21-09-2024 14_50_55-Medal Overlay](https://github.com/user-attachments/assets/9837f8a5-9b55-47d1-8536-617ef55a67d6)

Closing the bag and waiting a couple of seconds shows the bag like this instead (which is the size it is when I can actually see the items in my bag): 
![21-09-2024 14_51_49-](https://github.com/user-attachments/assets/9f3ab80f-d0c9-4620-93ee-7b6ffa22278c)

I can't remember when it started, but it was this week (It's Sept. 21st as of writing) that it became this severe where it can happen a LOT of times in a single session, compared to before where it happened maybe once a day, at most.

### Steps to reproduce

Sadly, I haven't found a way to replicate it, it's just random, but is happening more often than it usually has.

**Comment by AMaribo** [comment]
Blank bags like this usually means you are receiving a Lua error. Do you have BugGrabber and BugSack installed? If so, the errors will show up there. Otherwise, please install them and post the Lua error here.

**Comment by r0xp0x** [comment]
30x BetterBags_GearFirst/main.lua:95: attempt to index local 'b' (a nil value)
[string "@BetterBags_GearFirst/main.lua"]:95: in function <BetterBags_GearFirst/main.lua:90>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@BetterBags/frames/grid.lua"]:242: in function `Sort'
[string "@BetterBags/views/gridview.lua"]:371: in function `Render'
[string "@BetterBags/frames/bag.lua"]:316: in function `Draw'
[string "@BetterBags/core/init.lua"]:290: in function `cb'
[string "@BetterBags/core/events.lua"]:49: in function <BetterBags/core/events.lua:47>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:206: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:224: in function <BetterBags/core/events.lua:223>

Locals:
kind = 0
a = <table> {
 content = <table> {
 }
 frame = Frame {
 }
 title = Button {
 }
 maxItemsPerRow = 9
}
b = nil
shouldSort = false
sortResult = false
(*temporary) = "Gear: Resto"
(*temporary) = "Recent Items"
(*temporary) = <table> {
 data = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 locale = "enUS"
 moduleName = "Localization"
 defaultModuleState = true
 name = "BetterBags_Localization"
 orderedModules = <table> {
 }
}
(*temporary) = "Recent Items"
(*temporary) = "Recent Items"
(*temporary) = "enUS"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'b' (a nil value)"
sort = <table> {
 defaultModuleLibraries = <table> {
 }
 name = "BetterBags_Sort"
 orderedModules = <table> {
 }
 enabledState = false
 baseName = "BetterBags"
 modules = <table> {
 }
 moduleName = "Sort"
 defaultModuleState = true
}
L = <table> {
 data = <table> {
 }
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 baseName = "BetterBags"
 enabledState = true
 locale = "enUS"
 moduleName = "Localization"
 defaultModuleState = true
 name = "BetterBags_Localization"
 orderedModules = <table> {
 }
}
const = <table> {
 BANK_ONLY_BAGS = <table> {
 }
 BAG_KIND = <table> {
 }
 modules = <table> {
 }
 BANK_TAB = <table> {
 }
 BANK_BAGS = <table> {
 }
 GEAR_SECTION_ORDER = <table> {
 }
 BINDING_SCOPE = <table> {
 }
 BANK_ONLY_BAGS_LIST = <table> {
 }
 baseName = "BetterBags"
 BAG_SUBTYPES = <table> {
 }
 DATABASE_DEFAULTS = <table> {
 }
 SECTION_SORT_TYPE = <table> {
 }
 FORM_LAYOUT = <table> {
 }
 INVENTORY_TYPE_TO_INVENTORY_SLOTS = <table> {
 }
 EQUIPMENT_SLOTS = <table> {
 }
 TRADESKILL_MAP = <table> {
 }
 name = "BetterBags_Constants"
 BRIEF_EXPANSION_MAP = <table> {
 }
 orderedModules = <table> {
 }
 EXPANSION_MAP = <table> {
 }
 defaultModuleState = true
 OFFSETS = <table> {
 }
 ITEM_QUALITY_COLOR = <table> {
 }
 BINDING_MAP = <table> {
 }
 ITEM_QUALITY_HIGHLIGHT = <table> {
 }
 BAG_SUBTYPE_TO_QUALITY = <table> {
 }
 ITEM_QUALITY_TO_ENUM = <table> {
 }
 EXPANSION_TYPE = <table> {
 }
 ITEM_SORT_TYPE = <table> {
 }
 BACKPACK_BAGS = <table> {
 }
 BAG_VIEW = <table> {
 }
 WINDOW_KIND = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 ITEM_QUALITY_COLOR_LOW = <table> {
 }
 BACKPACK_ONLY_BAGS_LIST = <table> {
 }
 enabledState = false
 BACKPACK_ONLY_REAGENT_BAGS = <table> {
 }
 ACCOUNT_BANK_BAGS = <table> {
 }
 GRID_COMPACT_STYLE = <table> {
 }
 MOVEMENT_FLOW = <table> {
 }
 REAGENTBANK_BAGS = <table> {
 }
 ITEM_BAG_FAMILY = <table> {
 }
 ITEM_QUALITY_COLOR_HIGH = <table> {
 }
 moduleName = "Constants"
 BACKPACK_ONLY_BAGS = <table> {
 }
}


And this:

5x BetterBags/core/events.lua:201: ctx has been cancelled: bags/Draw/Backpack/Loaded
[string "=[C]"]: in function `error'
[string "@BetterBags/core/events.lua"]:201: in function `SendMessage'
[string "@BetterBags/core/init.lua"]:294: in function <BetterBags/core/init.lua:290>
[string "@BetterBags/frames/bag.lua"]:332: in function `callback'
[string "@BetterBags/views/gridview.lua"]:438: in function `Render'
[string "@BetterBags/frames/bag.lua"]:316: in function `Draw'
[string "@BetterBags/core/init.lua"]:290: in function `cb'
[string "@BetterBags/core/events.lua"]:49: in function <BetterBags/core/events.lua:47>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:206: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:224: in function <BetterBags/core/events.lua:223>

Locals:
(*temporary) = "ctx has been cancelled: bags/Draw/Backpack/Loaded"


What I've also noticed is that switching "Show bags" in the options "usually" works as well. Meaning if the window is blank, I change the setting from one big backpack to individual backpacks, wait for the items to load, and then change it back again.

**Comment by AMaribo** [comment]
> BetterBags_GearFirst/main.lua:95

The error you are receiving is a Lua error in the plugin BetterBags - Gear First. You'll need to reach out to the author of that plugin for support.
