### ISSUE TITLE
[Feature]: Exclude items from depositing into warbank or reagents bank

### ISSUE THREAD

**Issue by Fusyion** [Cidan/BetterBags#713]
### Describe the feature

I love that I can deposit items into my warbank with a single right click. However, there are items I actually do not want to deposit, for example hearty food like: Hearty Beledar's Bounty. It would be great if I could exclude specific items from depositing.

### Describe the implementation

In a configuration menu, I would like to have a list of items that are excluded from being deposited to the warbank/reagent bank. I should be able to add and remove items from this list.

**Comment by AMaribo** [comment]
Which items get deposited into the Warbank into which tab is decided upon by Blizzard.

**Comment by Fusyion** [comment]
Thank you - I had hoped there would be some way to influence that, but sadly not.
