### ISSUE TITLE
[SUGGESTION] Plugin Template

### ISSUE THREAD

**Issue by ZehelFenris** [Cidan/BetterBags#72]
I was wondering if it would be possible to have a template somewhere people would be able to download if they want to make their own plugin that is set up so people only need to change the name of the files, variables that are shown in-game and fill out with a list of their item IDs but otherwise working. So people who want to make their custom addon they want to share but don't know LUA to be able to make one from scratch.

An example would be that I want to make a plugin for all learnable shapeshift for druids, such as Glyphs and the Marks in the Emerald Dream. I would like if I only have to rename a few things, find the item IDs on Wowhead, put them into an array in the template, and then put the files in my addons folder.

**Comment by FlyingDiver** [comment]
It's in the current code in the examples folder.

**Comment by KatyPurry** [comment]
You can check this file : https://github.com/Cidan/BetterBags/blob/main/examples/plugin/plugin.lua

**Comment by ZehelFenris** [comment]
oh the curseforge client says I have the newest version but the examples are not part of the addon folder so I thought there were none

**Comment by SpareSimian** [comment]
I suggest mentioning it in the Readme under Features.

**Comment by ZehelFenris** [comment]
I looked at it, and I still have no idea how I would go around making the plugin; I have never made an addon before, and I don't know Lua coding, which is where an actual template would help as we would just need to fill in the info without having to make the base part of the addon as well.

**Comment by Cidan** [comment]
We probably won't go beyond what we have now. I understand your desire to get into the thick of it, but ultimately, we're not equipped to support users on how to write Lua or WoW addons. There are plenty of resources on how to learn Lua.

If this isn't something that you want to do, then I suggest waiting for the UI custom section work to be done, which will do what you're looking for in a user friendly way.

Thanks!
