### ISSUE TITLE
Add ability to have more search options

### ISSUE THREAD

**Issue by jbolduan** [Cidan/BetterBags#77]
Either some short hand searches such as "boe" for bind on equip or "bop" for bind on pickup.  That and searching for item attributes like "leggings" or "chest" or words in fields within items such as "use"

It would also be possibly helpful to have a not operator for searching like "not armor".

It would also be helpful to have the ability to search for soulbound items.

**Comment by Cidan** [comment]
Some of this has been partially implemented, some not. There will be more features here in the future though.

**Comment by czarl21** [comment]
where has this been implemented?  I just installed this (from the warning in Adibags) and definetly liked being able to search for BOE (or even "binds") so I know what to send to my banker toon

ty

**Comment by Braintelligence** [comment]
It would be awesome if we could opt for a permanently available search bar; I don't like needing an extra click to view it.

**Comment by AMaribo** [comment]
> It would be awesome if we could opt for a permanently available search bar; I don't like needing an extra click to view it.

A permanent search bar is available through the Enable In-Bag Search option.



> Either some short hand searches such as "boe" for bind on equip or "bop" for bind on pickup. That and searching for item attributes like "leggings" or "chest" or words in fields within items such as "use"
> 
> It would also be possibly helpful to have a not operator for searching like "not armor".
> 
> It would also be helpful to have the ability to search for soulbound items.

Most of these search options have been added in the latest release, v.0.1.81.
Tooltip scanning has not yet been implemented, but most attributes of items can be searched. For more information, see the readme.
