### ISSUE TITLE
Gear Slot categories/sorting

### ISSUE THREAD

**Issue by plachance14** [Cidan/BetterBags#79]
We discussed this in the discord, but some option either to seperate gear the goes in different slots into categoies, or to just sort the "armor" category by slot so all the helms, rings, trinkets, weapons, etc. are placed next to each other and then sub-sorted by the global sorting choice (alphabet, etc.) would be awesome! Thanks for the great addon!

**Comment by fubbleskag** [comment]
@plachance14 here's code you could put into an addon to give you each slot as an available custom category until this is implemented (I imagine the implementation in the main addon will be cleaner than this)

```
local addon = LibStub('AceAddon-3.0'):GetAddon("BetterBags")
local categories = addon:GetModule('Categories')
local L = addon:GetModule('Localization')

-- Gear Slots
categories:RegisterCategoryFunction("Gear Slots", function (data)
	if (data.itemInfo.itemEquipLoc) then
		return L:G(_G[data.itemInfo.itemEquipLoc])
	end
	return nil
end)
```

![image](https://github.com/Cidan/BetterBags/assets/3422674/76af2d05-93c9-48c0-aa66-61450384e033)

**Comment by plachance14** [comment]
Thanks! I'll give that a shot later today!

**Comment by zeptognome** [comment]
Implemented as Equipment Location
![image](https://github.com/user-attachments/assets/8bd6455f-9e01-42b4-9462-a74d722542d9)

Further refinements will ongoing
