### ISSUE TITLE
Deleting item out of reagent bag results into persisting item-icon

### ISSUE THREAD

**Issue by Floppydin** [Cidan/BetterBags#83]
If I delete an item directly out of reagent bag the icon of the deleted item persists until reopening the bank or let the bank sort (e.g. dropping a new item into bank.
With pictures provided you can see, after deletion of item the icon still persists, but shows no more tooltip, bc the item does not exist anymore. It is interactible, but not moveable or anything.

<img width="276" alt="image" src="https://github.com/Cidan/BetterBags/assets/157397316/3f3aec41-505d-4104-9ca7-1bededb48b52">
<img width="186" alt="image" src="https://github.com/Cidan/BetterBags/assets/157397316/9e9cc729-4376-4013-9152-e2d6d852b474">

**Comment by Cidan** [comment]
Fixed in 0.1.0
