### ISSUE TITLE
Ace3 libs are loaded out of order in BetterBags.toc

### ISSUE THREAD

**Issue by Myrroddin** [Cidan/BetterBags#94]
The various Ace3 libs depend on each other to be loaded in a specific order, which [you can see in Ace3.toc](https://github.com/WoWUIDev/Ace3/blob/master/Ace3.toc). BetterBags.toc does not follow this order, which can lead to "missing" Ace3 components or APIs that are not missing but not loaded yet.

Any Ace3 libs that are unused in BetterBags do not need to be referenced or loaded. While the .pkgmeta doesn't require an order, I suggest matching .pkgmeta to the corrected BetterBags.toc to avoid confusion.

**Comment by Cidan** [comment]
Have you observed an actual error?

**Comment by Myrroddin** [comment]
No, I have not observed an error. I posted the issue because the Ace3 devs recommend loading their libs in a particular order to prevent "cart before the horse" problems. One thing I haven't tested is to disable ALL other addons, including BugSack and BugGrabber, along with a standalone Ace3; according to WoW's loading algorithm and Ace3's suggested load order, then yes, an error should be observed.

**Comment by Cidan** [comment]
Can you show me the error, please? I'm fine with reordering, but if there's no error right now, I'm not going to spend the time on it -- you're welcome of course to send a PR as well!
