### ISSUE TITLE
[Feature Request] Add built-in categories for mounts, toys, and bags.

### ISSUE THREAD

**Issue by Rycia** [Cidan/BetterBags#97]
Currently, the "mounts" and "toys" category does not seem to exist, and toys get bundled into "Consumables", when they deserve their own category.
![image](https://github.com/Cidan/BetterBags/assets/43384589/e58180db-364b-43cb-85d9-bb6711676124)

Bags also get bundled with a "BoE" category even if they're not bound.
![image](https://github.com/Cidan/BetterBags/assets/43384589/2e94ecf5-9bc3-4502-8153-84f04edc27eb)

It would be nice to have these categories built-in to the addon.

**Comment by Cidan** [comment]
This is available if you turn on the Subtype category option.
